---
# yamllint disable rule:line-length
services:
  message-queue:
    profiles: [demo, dev]
    image: "${MESSAGE_QUEUE_DOCKER_IMAGE:-nats:alpine}"  # need alpine since latest is based on scratch (no wget available)
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
    healthcheck:
      test: wget -O /dev/null http://localhost:8222/varz || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  # This is actually unused but required to not break all the other compose files requiring this service...
  cache:
    profiles: [demo, dev]
    image: "${MESSAGE_QUEUE_DOCKER_IMAGE:-nats:alpine}"
    healthcheck:
      test: wget -O /dev/null http://localhost:8222/varz || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  task-manager:
    profiles: [demo, dev]
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    command: uvicorn --host 0.0.0.0 --port 4200 --factory infrahub.prefect_server.app:create_infrahub_prefect
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:postgres@task-manager-db:5432/prefect
      PREFECT_LOCAL_STORAGE_PATH: ${PREFECT_LOCAL_STORAGE_PATH:-/opt/prefect/}
      PREFECT_WORKER_QUERY_SECONDS: 3
      PREFECT_AGENT_QUERY_INTERVAL: 3
    healthcheck:
      test: curl -s -f -o /dev/null http://localhost:4200/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      - task-manager-db
  task-manager-db:
    profiles: [demo, dev]
    image: "${POSTGRES_DOCKER_IMAGE:-pgautoupgrade/pgautoupgrade:18-alpine}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    volumes:
      - "workflow_db:${POSTGRES_DATADIR:-/var/lib/postgresql/18/docker}"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -q -d ${INFRAHUB_TASKMANAGER_DB_DATABASE:-prefect} -U ${INFRAHUB_TASKMANAGER_DB_USER:-postgres}"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  workflow_db:
