---
services:
  message-queue:
    user: rabbitmq
    image: "${MESSAGE_QUEUE_DOCKER_IMAGE:-rabbitmq:latest}"
    environment:
      - "RABBITMQ_DEFAULT_USER=infrahub"
      - "RABBITMQ_DEFAULT_PASS=infrahub"
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 3s
  cache:
    image: "${CACHE_DOCKER_IMAGE:-redis:latest}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 3
