---
# yamllint disable rule:line-length
x-infrahub-config: &infrahub_config
  AWS_ACCESS_KEY_ID:
  AWS_DEFAULT_ACL:
  AWS_QUERYSTRING_AUTH:
  AWS_S3_BUCKET_NAME:
  AWS_S3_CUSTOM_DOMAIN:
  AWS_S3_ENDPOINT_URL:
  AWS_S3_USE_SSL:
  AWS_SECRET_ACCESS_KEY:
  DB_TYPE:
  INFRAHUB_ADDRESS:
  INFRAHUB_ALLOW_ANONYMOUS_ACCESS:
  INFRAHUB_ANALYTICS_ADDRESS:
  INFRAHUB_ANALYTICS_API_KEY:
  INFRAHUB_ANALYTICS_ENABLE:
  INFRAHUB_API_CORS_ALLOW_CREDENTIALS:
  INFRAHUB_API_CORS_ALLOW_HEADERS:
  INFRAHUB_API_CORS_ALLOW_METHODS:
  INFRAHUB_API_CORS_ALLOW_ORIGINS:
  INFRAHUB_BROKER_ADDRESS:
  INFRAHUB_BROKER_ENABLE:
  INFRAHUB_BROKER_MAXIMUM_CONCURRENT_MESSAGES:
  INFRAHUB_BROKER_MAXIMUM_MESSAGE_RETRIES:
  INFRAHUB_BROKER_NAMESPACE:
  INFRAHUB_BROKER_PASSWORD:
  INFRAHUB_BROKER_PORT:
  INFRAHUB_BROKER_TLS_ENABLED:
  INFRAHUB_BROKER_USERNAME:
  INFRAHUB_BROKER_VIRTUALHOST:
  INFRAHUB_CACHE_ADDRESS:
  INFRAHUB_CACHE_DATABASE:
  INFRAHUB_CACHE_ENABLE:
  INFRAHUB_CACHE_PORT:
  INFRAHUB_CONFIG:
  INFRAHUB_DB_ADDRESS:
  INFRAHUB_DB_DATABASE:
  INFRAHUB_DB_MAX_DEPTH_SEARCH_HIERARCHY:
  INFRAHUB_DB_PASSWORD:
  INFRAHUB_DB_PORT:
  INFRAHUB_DB_PROTOCOL:
  INFRAHUB_DB_QUERY_SIZE_LIMIT:
  INFRAHUB_DB_RETRY_LIMIT:
  INFRAHUB_DB_TYPE:
  INFRAHUB_DB_USERNAME:
  INFRAHUB_DOCS_INDEX_PATH:
  INFRAHUB_EXPERIMENTAL_GRAPHQL_ENUMS:
  INFRAHUB_EXPERIMENTAL_PULL_REQUEST:
  INFRAHUB_GIT_REPOSITORIES_DIRECTORY:
  INFRAHUB_GIT_SYNC_INTERVAL:
  INFRAHUB_INITIAL_DEFAULT_BRANCH:
  INFRAHUB_INTERNAL_ADDRESS:
  INFRAHUB_LOGGING_REMOTE_API_SERVER_DSN:
  INFRAHUB_LOGGING_REMOTE_ENABLE:
  INFRAHUB_LOGGING_REMOTE_FRONTEND_DSN:
  INFRAHUB_LOGGING_REMOTE_GIT_AGENT_DSN:
  INFRAHUB_LOG_LEVEL:
  INFRAHUB_MISC_MAXIMUM_VALIDATOR_EXECUTION_TIME:
  INFRAHUB_MISC_PRINT_QUERY_DETAILS:
  INFRAHUB_MISC_START_BACKGROUND_RUNNER:
  INFRAHUB_PRODUCTION:
  INFRAHUB_SECURITY_ACCESS_TOKEN_LIFETIME:
  INFRAHUB_SECURITY_INITIAL_ADMIN_PASSWORD:
  INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN:
  INFRAHUB_SECURITY_REFRESH_TOKEN_LIFETIME:
  INFRAHUB_SECURITY_SECRET_KEY:
  INFRAHUB_STORAGE_BUCKET_NAME:
  INFRAHUB_STORAGE_CUSTOM_DOMAIN:
  INFRAHUB_STORAGE_DEFAULT_ACL:
  INFRAHUB_STORAGE_DRIVER:
  INFRAHUB_STORAGE_ENDPOINT_URL:
  INFRAHUB_STORAGE_LOCAL_PATH:
  INFRAHUB_STORAGE_QUERYTSTRING_AUTH:
  INFRAHUB_STORAGE_USE_SSL:
  INFRAHUB_TRACE_ENABLE:
  INFRAHUB_TRACE_EXPORTER_ENDPOINT:
  INFRAHUB_TRACE_EXPORTER_PROTOCOL:
  INFRAHUB_TRACE_EXPORTER_TYPE:
  INFRAHUB_TRACE_INSECURE:
  OTEL_RESOURCE_ATTRIBUTES:

services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    command: >
      gunicorn --config backend/infrahub/serve/gunicorn_config.py -w ${GUNICORN_WORKERS} --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "${INFRAHUB_SERVER_PORT:-8000}:8000"
    environment:
      <<: *infrahub_config
      INFRAHUB_CONFIG: /source/development/infrahub.toml
      INFRAHUB_PRODUCTION: false
      INFRAHUB_LOG_LEVEL: INFO"
      INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN: 06438eb2-8019-4776-878c-0941b1f1d1ec
      INFRAHUB_SECURITY_SECRET_KEY: 327f747f-efac-42be-9e73-999f08f86b92
    volumes:
      - ../:/source
      - "storage_data:/opt/infrahub/storage"
    tty: true
    labels:
      com.github.run_id: "${GITHUB_RUN_ID:-unknown}"
      com.github.job: "${JOB_NAME:-unknown}"
    healthcheck:
      test: curl -s -f -o /dev/null http://localhost:8000/api/schema/summary || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  database:
    ports:
      - "${INFRAHUB_DB_PORT:-7687}:7687"

volumes:
  storage_data:
