---
# yamllint disable rule:line-length
services:
  cache:
    deploy:
      mode: replicated
      replicas: "${NBR_WORKERS}"
  message-queue:
    deploy:
      mode: replicated
      replicas: "${NBR_WORKERS}"
  task-manager:
    deploy:
      mode: replicated
      replicas: "${NBR_WORKERS}"
