---
version: "3.4"
services:
  infrahub-server:
    ports:
      - "8000:8000"
    environment:
      - INFRAHUB_EXPERIMENTAL_IGNORE_AUTHENTICATION_REQUIREMENTS=true
  frontend:
    ports:
      - "3000:3000"
