FROM node:16-slim

ARG INFRAHUB_API_SERVER_URL=http://localhost:8000
ENV VITE_INFRAHUB_API_SERVER_URL=${INFRAHUB_API_SERVER_URL}

RUN mkdir /source

# Install Python to resolve an issue with @parcel/watch
# https://github.com/parcel-bundler/parcel/issues/6880
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y g++ python3 make build-essential && \
    apt-get clean all && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g npm@latest
COPY frontend/package.json  frontend/package-lock.json /source/

WORKDIR /source

RUN npm install
COPY frontend/ /source/

RUN  npm install serve
RUN npm run build
