---
services:
  database:
    image: "${DATABASE_DOCKER_IMAGE:-memgraph/memgraph-platform:latest}"
    entrypoint: ["/usr/bin/supervisord"]
    init: true
    volumes:
      - database_data:/var/lib/memgraph
      - database_logs:/var/log/memgraph
      - ./memgraph.conf:/etc/memgraph/memgraph.conf
    environment:
      - MGCONSOLE="--username neo4j --password admin"
      - APP_CYPHER_QUERY_MAX_LEN=10000

    healthcheck:
      test: ["CMD", "bash", "-c", 'mgconsole < <(echo "SHOW TRANSACTIONS;")']
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 3s
    labels:
      infrahub_role: "database"
      com.github.run_id: "${GITHUB_RUN_ID:-unknown}"
      com.github.job: "${JOB_NAME:-unknown}"


volumes:
  database_data:
  database_logs:
