import { describe, expect, it } from "vitest";
import { TestForm } from "../../../../../tests/components/form.story";
import { render } from "../../../../../tests/components/render";
import RelationshipField from "./relationship.field";

const props = {
  name: "fabric",
  label: "Fabric",
  defaultValue: {
    source: null,
    value: null,
  },
  disabled: false,
  rules: {
    required: true,
    validate: {},
  },
  relationship: {
    id: "181a929d-bcea-4de5-37bc-c51fac9ccccf",
    state: "present",
    name: "fabric",
    peer: "InfraFabric",
    kind: "Parent",
    label: "Fabric",
    description: null,
    identifier: "infrafabric__infrapod",
    cardinality: "one",
    min_count: 1,
    max_count: 1,
    order_weight: 2000,
    optional: false,
    branch: "aware",
    inherited: true,
    direction: "bidirectional",
    hierarchical: null,
    on_delete: "no-action",
    allow_override: "any",
    read_only: false,
    deprecation: null,
  },
  schema: {
    id: "181a929d-bbdf-cd72-37bc-c51ed61c3f25",
    state: "present",
    name: "NetworkPod",
    namespace: "Infra",
    description: null,
    label: "Networkpod",
    branch: "aware",
    default_filter: null,
    human_friendly_id: ["name__value"],
    display_labels: null,
    include_in_menu: true,
    menu_placement: null,
    icon: null,
    order_by: null,
    uniqueness_constraints: [["name__value"]],
    documentation: null,
    attributes: [
      {
        id: "181a929d-bc63-a87e-37bc-c516f17c96ae",
        state: "present",
        name: "name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Name",
        description: null,
        read_only: false,
        unique: true,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: true,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: "181a929d-bcea-4de5-37bc-c51fac9ccccf",
        state: "present",
        name: "fabric",
        peer: "InfraFabric",
        kind: "Parent",
        label: "Fabric",
        description: null,
        identifier: "infrafabric__infrapod",
        cardinality: "one",
        min_count: 1,
        max_count: 1,
        order_weight: 2000,
        optional: false,
        branch: "aware",
        inherited: true,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "181a929d-bd6e-899e-37be-c51cdebe766d",
        state: "present",
        name: "profiles",
        peer: "CoreProfile",
        kind: "Profile",
        label: "Profiles",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 3000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "181a929d-bded-c853-37bc-c51cd913f2c3",
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 4000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "181a929d-be6d-7be5-37b4-c51f0eedff85",
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 5000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    inherit_from: ["InfraPod"],
    generate_profile: true,
    hierarchy: null,
    parent: null,
    children: null,
    kind: "InfraNetworkPod",
    hash: "c6e6cd9774f56a9b7519bd21e4da7de9",
  },
};

describe("Relationship Field Component", () => {
  it("renders the relationship field correctly", async () => {
    // GIVEN
    let formValue;
    const component = render(
      <TestForm onSubmit={(formData) => (formValue = formData)}>
        <RelationshipField {...props} />
      </TestForm>
    );

    // WHEN
    await component.getByRole("button", { name: "Submit" }).click();

    // THEN
    await expect
      .element(component.getByText("This schema is not a node with hierarchy"))
      .toBeVisible();
  });
});
