---
ci_config: &ci_config
  - ".github/workflows/ci.yml"
  - ".github/file-filters.yml"

github_workflows: &github_workflows
  - ".github/workflows/*.yml"

development_files: &development_files
  - "development/**"
  - "tasks/**"

backend_files: &backend_files
  - "backend/**"

infrahub_poetry_files: &infrahub_poetry_files
  - "pyproject.toml"
  - "poetry.lock"

frontend_files: &frontend_files
  - "frontend/app/**"

e2e_test_files:
  - "frontend/app/tests/e2e/**"

demo_files: &demo_files
  - "models/**"

doc_files: &doc_files
  - "docs/**"
  - package.json
  - package-lock.json

release_files: &release_files
  - "changelog/*.md"
  - CHANGELOG.md
  - "docs/docs/relese_notes/infrahub/*.mdx"

helm_files: &helm_files
  - "helm/**"

python_all: &python_all
  - "**/*.py"

javascript_all: &javascript_all
  - "**/*.[tj]{s,sx}"

yaml_all: &yaml_all
  - "**/*.{yml,yaml}"

markdown_all: &markdown_all
  - "**/*.{md,mdx}"

backend_all:
  - *backend_files
  - *ci_config
  - *development_files
  - *infrahub_poetry_files

documentation_all:
  - *development_files
  - *doc_files
  - *markdown_all

release_all:
  - *release_files

helm_all:
  - *helm_files

frontend_all:
  - *frontend_files
  - *ci_config
  - *development_files

e2e_all:
  - *backend_files
  - *frontend_files
  - *demo_files
  - *ci_config
  - *development_files
