---
categories:
  - title: '🚀 Features'
    labels:
      - 'type/feature'
      - 'type/feature/py-sdk'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type/bug'
      - 'type/bug/py-sdk'
  - title: '🧰 Maintenance'
    labels:
      - 'type/housekeeping'
      - 'type/housekeeping/py-sdk'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
  - 'ci/skip-changelog'
include-labels:
  - 'group/python-sdk'
change-title-escapes: '\<*_&'  # You can add # and @ to disable mentions, and add ` to disable code blocks.
tag-prefix: python-sdk-v
tag-template: python-sdk-v
template: |
  ## Changelog

  $CHANGES
