---
name: from-nautobot-v1
source:
  name: nautobot
  settings:
    url: "http://nautobot:8080"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "BuiltinTag",
  "RoleGeneric",
  # "StatusGeneric",
  "CoreStandardGroup",
  "TemplateLocationType",
  "OgranizationGeneric",
  "LocationGeneric",
  "InfraRack",
  "TemplateDeviceType",
  "InfraPlatform",
  "InfraProviderNetwork",
  "TemplateCircuitType",
  "InfraCircuit",
  "InfraRouteTarget",
  "InfraVRF",
  "InfraDevice",
  "InfraVLAN",
  "InfraPrefix",
  "InfraIPAddress",
  "InfraRearPort",
  "InfraFrontPort",
  "InfraInterfaceL2L3"
]

schema_mapping:
  # Tags
  - name: BuiltinTag
    mapping: extras.tags
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  # Roles (Device Role, Rack Role, IPAM Role)
  - name: RoleGeneric
    mapping: dcim.device_roles
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: RoleGeneric
    mapping: dcim.rack_roles
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: RoleGeneric
    mapping: ipam.roles
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  # Status
  - name: StatusGeneric
    mapping: extras.statuses
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: label
        mapping: display

  # Tenancy (tenants, tenant groups)
  - name: CoreStandardGroup
    mapping: tenancy.tenant-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: OgranizationGeneric
    mapping: tenancy.tenants
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Tenant"
      - name: group
        mapping: group
        reference: CoreStandardGroup

  # Sites (Region, Sites, Location)
  - name: TemplateLocationType
    mapping: dcim.location-types
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: LocationGeneric
    mapping: dcim.regions
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: name
      - name: type
        static: "Region"
  - name: LocationGeneric
    mapping: dcim.sites
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: name
      - name: type
        static: "Site"
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
  - name: LocationGeneric
    mapping: dcim.locations
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: name
      - name: type
        static: "Location"
      - name: location_type
        mapping: location_type
        reference: TemplateLocationType
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric

  # Racks
  - name: InfraRack
    mapping: dcim.racks
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: location
        mapping: location
        reference: LocationGeneric
      - name: site
        mapping: site
        reference: LocationGeneric
      - name: height
        mapping: u_height
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: facility_id
        mapping: facility_id
      - name: role
        mapping: role
        reference: RoleGeneric
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Device (manufacturer, device types, platform, devices)
  - name: OgranizationGeneric
    mapping: dcim.manufacturers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Manufacturer"
  - name: InfraPlatform
    mapping: dcim.platforms
    identifiers: ["name", "manufacturer"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: napalm_driver
        mapping: napalm_driver
      - name: manufacturer
        mapping: manufacturer
        reference: OgranizationGeneric
  - name: TemplateDeviceType
    mapping: dcim.device-types
    identifiers: ["name", "manufacturer"]
    fields:
      - name: name
        mapping: model
      - name: part_number
        mapping: part_number
      - name: full_depth
        mapping: is_full_depth
      - name: height
        mapping: u_height
      - name: tags
        mapping: tags
        reference: BuiltinTag
      - name: manufacturer
        mapping: manufacturer
        reference: OgranizationGeneric
  # -> Device validate_unique()
  # https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/models/devices.py#L541C9-L541C24
  - name: InfraDevice
    identifiers: ["location", "organization", "name"]
    mapping: dcim.devices
    fields:
      - name: name
        mapping: name
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: model
        mapping: device_type
        reference: TemplateDeviceType
      - name: platform
        mapping: platform
        reference: InfraPlatform
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
      - name: role
        mapping: device_role
        reference: RoleGeneric
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
      - name: location
        mapping: location
        reference: LocationGeneric
      - name: rack
        mapping: rack
        reference: InfraRack
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Circuits (Provider, Provider Network, Circuits Types, Circuits)
  - name: OgranizationGeneric
    mapping: circuits.providers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: type
        static: "Provider"
  - name: InfraProviderNetwork
    mapping: circuits.provider-networks
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: vendor_id
        mapping: service_id
      - name: provider
        mapping: provider.slug
      - name: description
        mapping: description
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
      - name: tags
        mapping: tags
        reference: BuiltinTag
      - name: provider
        mapping: provider
        reference: OgranizationGeneric
  - name: TemplateCircuitType
    mapping: circuits.circuit-types
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: InfraCircuit
    mapping: circuits.circuits
    identifiers: ["circuit_id"]
    fields:
      - name: circuit_id
        mapping: cid
      - name: vendor_id
        mapping: cid
      - name: provider
        mapping: provider
        reference: OgranizationGeneric
      - name: description
        mapping: description
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
      - name: type
        mapping: type
        reference: TemplateCircuitType
      # - name: tenant
      #   mapping: tenant
      #   reference: OgranizationGeneric
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # BGP Plugin (Autonomous System, BGP Session, BGP Peer Group)
  - name: InfraAutonomousSystem
    mapping: plugin.bgp.autonomous-systems
    identifiers: ["name"]
    fields:
      - name: name
        mapping: asn
      - name: asn
        mapping: asn
      - name: description
        mapping: description
      - name: organization
        mapping: provider
        reference: OgranizationGeneric

# IPAM (VRF, VLANs Groups, VLANs, Prefixes, IPs)
  - name: InfraRouteTarget
    mapping: ipam.route-targets
    identifiers: ["name", "organization"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
  - name: InfraVRF
    mapping: ipam.vrfs
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
      - name: vrf_rd
        mapping: rd
      - name: import_rt
        mapping: import_targets
        reference: InfraRouteTarget
      - name: export_rt
        mapping: export_targets
        reference: InfraRouteTarget
  - name: CoreStandardGroup
    mapping: ipam.vlan-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      # - name: location
      #   mapping: location
      #   reference: LocationGeneric
  - name: InfraVLAN
    mapping: ipam.vlans
    identifiers: ["name", "vlan_id", "location", "organization"]
    fields:
      - name: name
        mapping: name
      - name: vlan_id
        mapping: vid
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
      - name: description
        mapping: description
      - name: location
        mapping: location
        reference: LocationGeneric
      - name: role
        mapping: role
        reference: RoleGeneric
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
      - name: vlan_group
        mapping: group
        reference: CoreStandardGroup
  - name: InfraPrefix
    mapping: ipam.prefixes
    identifiers: ["prefix", "vrf", "organization"]
    fields:
      - name: prefix
        mapping: prefix
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
      - name: vrf
        mapping: vrf
        reference: InfraVRF
      - name: role
        mapping: role
        reference: RoleGeneric
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
      - name: vlan
        mapping: vlan
        reference: InfraVLAN
      - name: location
        mapping: location
        reference: LocationGeneric
  - name: InfraIPAddress
    mapping: ipam.ip-addresses
    identifiers: ["address", "vrf"]
    fields:
      - name: address
        mapping: address
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: OgranizationGeneric
      - name: vrf
        mapping: vrf
        reference: InfraVRF
      - name: role
        mapping: role
        reference: RoleGeneric
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric

  # Interfaces (interfaces, rear port, front port)
  - name: InfraInterfaceL2L3
    identifiers: ["name", "device"]
    mapping: dcim.interfaces
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: interface_type
        mapping: type.label
      - name: l2_mode
        mapping: mode.label
      - name: mac_address
        mapping: mac_address
      - name: mgmt_only
        mapping: mgmt_only
      - name: untagged_vlan
        mapping: untagged_vlan
        reference: InfraVLAN
      - name: tagged_vlan
        mapping: tagged_vlans
        reference: InfraVLAN
      - name: device
        mapping: device
        reference: InfraDevice
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
      - name: tags
        mapping: tags
        reference: BuiltinTag
  - name: InfraFrontPort
    identifiers: ["name", "device"]
    mapping: dcim.front-ports
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: port_type
        mapping: type.label
      - name: rear_port
        mapping: rear_port
        reference: InfraRearPort
      - name: device
        mapping: device
        reference: InfraDevice
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
  - name: InfraRearPort
    identifiers: ["name", "device"]
    mapping: dcim.rear-ports
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: port_type
        mapping: type.label
      - name: device
        mapping: device
        reference: InfraDevice
      # - name: status
      #   mapping: status
      #   reference: StatusGeneric
