---
# yamllint disable rule:line-length
tasks:
  - name: CLI
    before: |
      printf 'export PATH="%s:$PATH"\n' "/home/gitpod/.local/bin" >> $HOME/.bashrc
      gp env INFRAHUB_SDK_API_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec
    init: |
      cd /workspace/infrahub
      pyenv install 3.11 --skip-existing
      pyenv local 3.11
      pip install toml invoke
      curl -sSL https://install.python-poetry.org | python3 -
      source $HOME/.bashrc
      poetry config virtualenvs.create false
      poetry install
      poetry run invoke demo.build
    command: |
      cd /workspace/infrahub
      source $HOME/.bashrc
      poetry run invoke demo.destroy demo.start demo.load-infra-schema demo.load-infra-data

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: ignore
    name: web-interface
    description: Web Interface
    visibility: public
  - port: 7474
    onOpen: ignore
    name: database-ui
    description: Graphical interface for the database
    visibility: private
  - port: 7687
    onOpen: ignore
    name: database-api
    description: API for the database
    visibility: private
  - port: 15672
    onOpen: ignore
    name: rabbitmq-1
    visibility: private
  - port: 5672
    onOpen: ignore
    name: rabbitmq-2
    visibility: private
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

workspaceLocation: "infrahub/development/gitpod.code-workspace"
additionalRepositories:
  - url: https://github.com/opsmill/infrahub-demo-edge-develop
    # checkoutLocation is relative to /workspaces
    checkoutLocation: infrahub-demo-edge

vscode:
  extensions:
    - pomdtr.excalidraw-editor
    - wholroyd.jinja
    - ms-python.vscode-pylance
    - shardulm94.trailing-spaces
    - nickmillerdev.pytest-fixtures
    - yzhang.markdown-all-in-one
    - GraphQL.vscode-graphql-syntax
