---
extends: default

ignore: |
  /.venv
  /examples
  /repositories
  /frontend/node_modules
  /node_modules
  # https://github.com/sbaudoin/yamllint/issues/16
  /helm/templates

rules:
  new-lines: disable
  comments-indentation: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
