---
name: from-observium
source:
  name: observium
  settings:
    url: "OBSERVIUM_URL"
    # api_endpoint: "api/v0"
    # auth_method: "basic"
    username: "OBSERVIUM_USERNAME"
    password: "OBSERVIUM_PASSWORD"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "CoreStandardGroup",
  "IpamIPAddress",
  "InfraDevice",
]

schema_mapping:
  - name: CoreStandardGroup
    mapping: groups
    fields:
      - name: name
        mapping: group_name
      - name: description
        mapping: group_descr

  # Primary Device IP
  - name: IpamIPAddress
    mapping: devices
    identifiers: ["address"]
    fields:
      - name: address
        mapping: ip
      - name: description
        mapping: hostname

  - name: InfraDevice
    mapping: devices
    identifiers: ["name"]
    fields:
      - name: name
        mapping: hostname
      - name: description
        mapping: serial
      # Not in the demo schema
      # - name: serial_number
      #   mapping: serial

      # /!\ Platform need to exist beforehand !
      - name: platform
        mapping: os
        reference: InfraPlatform

      # Not in the demo schema
      # - name: manufacturer
      #   mapping: vendor
      #   reference: OrganizationManufacturer

      - name: type
        mapping: serial
      - name: primary_address
        mapping: ip
        reference: IpamIPAddress
