---
name: from-observium
source:
  name: observium
  settings:
    url: "OBSERVIUM_URL"
    # api_endpoint: "api/v0"
    # auth_method: "basic"
    username: "OBSERVIUM_USERNAME"
    password: "OBSERVIUM_PASSWORD"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "CoreStandardGroup",
  "IpamIPAddress",
  "InfraDevice",
]

schema_mapping:
  - name: CoreStandardGroup
    mapping: groups
    fields:
      - name: name
        mapping: group_name
      - name: description
        mapping: group_descr

  # Primary Device IP
  - name: IpamIPAddress
    mapping: devices
    identifiers: ["address"]
    filters:
      - "netutils.ip.is_ip_within(record.get('ip'), '10.0.0.0/8')"
      - "netutils.regex.regex_search('xxx', 'hostname')"
      - "netutils.regex.regex_match('^pe-[0-9]{3}$', 'hostname')"
    fields:
      - name: address
        mapping: ip
      - name: description
        mapping: hostname

  - name: InfraDevice
    mapping: devices
    identifiers: ["name"]
    filters:
      - "device_id > 100"
      - "device_id <= 200"
      - "netutils.regex.regex_search('xxx', 'hostname')"
      - "netutils.regex.regex_match('^pe-[0-9]{3}$', 'hostname')"
    fields:
      - name: name
        mapping: hostname
      - name: description
        mapping: description
      - name: serial_number
        mapping: serial
      # /!\ Platform need to exist beforehand !
      - name: platform
        mapping: os
        reference: InfraPlatform
      # /!\ Manufacturer need to exist beforehand !
      - name: manufacturer
        mapping: vendor
        reference: OrganizationManufacturer
      - name: type
        mapping: hardware
      - name: primary_address
        mapping: ip
        reference: IpamIPAddress
