from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub.core.constants import InfrahubKind
from infrahub.core.node import Node

if TYPE_CHECKING:
    from infrahub.database import InfrahubDatabase


async def create_stored_artifact(
    db: InfrahubDatabase, car_person_data_generic: dict[str, Node], storage_id: str, checksum: str
) -> Node:
    """Create an artifact of the first car, generated by a Python transform, that references a stored object."""
    transform = await Node.init(db=db, schema=InfrahubKind.TRANSFORMPYTHON)
    await transform.new(
        db=db,
        name="transform01",
        query=str(car_person_data_generic["q1"].id),
        repository=str(car_person_data_generic["r1"].id),
        file_path="transform01.py",
        class_name="Transform01",
    )
    await transform.save(db=db)
    group = await Node.init(db=db, schema=InfrahubKind.STANDARDGROUP)
    await group.new(db=db, name="group1", members=[car_person_data_generic["c1"]])
    await group.save(db=db)
    definition = await Node.init(db=db, schema=InfrahubKind.ARTIFACTDEFINITION)
    await definition.new(
        db=db,
        name="artifactdef01",
        targets=group,
        transformation=transform,
        content_type="application/json",
        artifact_name="myartifact",
        parameters={"value": {"name": "name__value"}},
    )
    await definition.save(db=db)
    artifact = await Node.init(db=db, schema=InfrahubKind.ARTIFACT)
    await artifact.new(
        db=db,
        name="myartifact",
        definition=definition,
        status="Ready",
        object=car_person_data_generic["c1"],
        storage_id=storage_id,
        checksum=checksum,
        content_type="application/json",
    )
    await artifact.save(db=db)
    return artifact
