# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateTask(BaseModel):
    infrahub_task_create: Optional["CreateTaskInfrahubTaskCreate"] = Field(
        alias="InfrahubTaskCreate"
    )


class CreateTaskInfrahubTaskCreate(BaseModel):
    ok: Optional[bool]
