# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateTag(BaseModel):
    builtin_tag_create: Optional["CreateTagBuiltinTagCreate"] = Field(
        alias="BuiltinTagCreate"
    )


class CreateTagBuiltinTagCreate(BaseModel):
    ok: Optional[bool]
    object: Optional["CreateTagBuiltinTagCreateObject"]


class CreateTagBuiltinTagCreateObject(BaseModel):
    id: str
