# Generated by ariadne-codegen
# Source: schema/schema.graphql

from enum import Enum


class CheckType(str, Enum):
    ARTIFACT = "ARTIFACT"
    DATA = "DATA"
    REPOSITORY = "REPOSITORY"
    SCHEMA = "SCHEMA"
    TEST = "TEST"
    USER = "USER"
    ALL = "ALL"


class TaskConclusion(str, Enum):
    UNKNOWN = "UNKNOWN"
    FAILURE = "FAILURE"
    SUCCESS = "SUCCESS"


class Severity(str, Enum):
    SUCCESS = "SUCCESS"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
