# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetTags(BaseModel):
    builtin_tag: Optional["GetTagsBuiltinTag"] = Field(alias="BuiltinTag")


class GetTagsBuiltinTag(BaseModel):
    edges: Optional[List[Optional["GetTagsBuiltinTagEdges"]]]


class GetTagsBuiltinTagEdges(BaseModel):
    node: Optional["GetTagsBuiltinTagEdgesNode"]


class GetTagsBuiltinTagEdgesNode(BaseModel):
    id: str
    display_label: Optional[str]
