# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetBranch(BaseModel):
    branch: Optional[List[Optional["GetBranchBranch"]]] = Field(alias="Branch")


class GetBranchBranch(BaseModel):
    id: str
    name: str
    description: Optional[str]
    origin_branch: Optional[str]
    branched_from: Optional[str]
    is_default: Optional[bool]
    is_data_only: Optional[bool]
