# Generated by ariadne-codegen
# Source: schema/schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CheckType, Severity, TaskConclusion


class CoreStandardGroupCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    members: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscribers: Optional[List[Optional["RelatedNodeInput"]]] = None
    parent: Optional["RelatedNodeInput"] = None
    children: Optional[List[Optional["RelatedNodeInput"]]] = None


class TextAttributeInput(BaseModel):
    is_visible: Optional[bool] = None
    is_protected: Optional[bool] = None
    source: Optional[str] = None
    owner: Optional[str] = None
    value: Optional[str] = None


class RelatedNodeInput(BaseModel):
    id: str
    relation_is_visible: Optional[bool] = Field(
        alias="_relation__is_visible", default=None
    )
    relation_is_protected: Optional[bool] = Field(
        alias="_relation__is_protected", default=None
    )
    relation_owner: Optional[str] = Field(alias="_relation__owner", default=None)
    relation_source: Optional[str] = Field(alias="_relation__source", default=None)


class CoreStandardGroupUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    members: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscribers: Optional[List[Optional["RelatedNodeInput"]]] = None
    parent: Optional["RelatedNodeInput"] = None
    children: Optional[List[Optional["RelatedNodeInput"]]] = None


class DeleteInput(BaseModel):
    id: str


class CoreGraphQLQueryGroupCreateInput(BaseModel):
    id: Optional[str] = None
    parameters: Optional["JSONAttributeInput"] = None
    name: "TextAttributeInput"
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    query: "RelatedNodeInput"
    members: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscribers: Optional[List[Optional["RelatedNodeInput"]]] = None
    parent: Optional["RelatedNodeInput"] = None
    children: Optional[List[Optional["RelatedNodeInput"]]] = None


class JSONAttributeInput(BaseModel):
    is_visible: Optional[bool] = None
    is_protected: Optional[bool] = None
    source: Optional[str] = None
    owner: Optional[str] = None
    value: Optional[Any] = None


class CoreGraphQLQueryGroupUpdateInput(BaseModel):
    id: str
    parameters: Optional["JSONAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    query: Optional["RelatedNodeInput"] = None
    members: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscribers: Optional[List[Optional["RelatedNodeInput"]]] = None
    parent: Optional["RelatedNodeInput"] = None
    children: Optional[List[Optional["RelatedNodeInput"]]] = None


class BuiltinTagCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class BuiltinTagUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreAccountCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    password: "TextAttributeInput"
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    type: Optional["TextAttributeInput"] = None
    role: Optional["TextAttributeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreAccountUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    password: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    type: Optional["TextAttributeInput"] = None
    role: Optional["TextAttributeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreProposedChangeCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    source_branch: "TextAttributeInput"
    destination_branch: "TextAttributeInput"
    state: Optional["TextAttributeInput"] = None
    approved_by: Optional[List[Optional["RelatedNodeInput"]]] = None
    reviewers: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    threads: Optional[List[Optional["RelatedNodeInput"]]] = None
    validations: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreProposedChangeUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    source_branch: Optional["TextAttributeInput"] = None
    destination_branch: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    approved_by: Optional[List[Optional["RelatedNodeInput"]]] = None
    reviewers: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    threads: Optional[List[Optional["RelatedNodeInput"]]] = None
    validations: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreChangeThreadCreateInput(BaseModel):
    id: Optional[str] = None
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: "RelatedNodeInput"
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CheckboxAttributeInput(BaseModel):
    is_visible: Optional[bool] = None
    is_protected: Optional[bool] = None
    source: Optional[str] = None
    owner: Optional[str] = None
    value: Optional[bool] = None


class CoreChangeThreadUpdateInput(BaseModel):
    id: str
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: Optional["RelatedNodeInput"] = None
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreFileThreadCreateInput(BaseModel):
    id: Optional[str] = None
    file: Optional["TextAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    line_number: Optional["NumberAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    repository: "RelatedNodeInput"
    change: "RelatedNodeInput"
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class NumberAttributeInput(BaseModel):
    is_visible: Optional[bool] = None
    is_protected: Optional[bool] = None
    source: Optional[str] = None
    owner: Optional[str] = None
    value: Optional[int] = None


class CoreFileThreadUpdateInput(BaseModel):
    id: str
    file: Optional["TextAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    line_number: Optional["NumberAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    change: Optional["RelatedNodeInput"] = None
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactThreadCreateInput(BaseModel):
    id: Optional[str] = None
    artifact_id: Optional["TextAttributeInput"] = None
    storage_id: Optional["TextAttributeInput"] = None
    line_number: Optional["NumberAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: "RelatedNodeInput"
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactThreadUpdateInput(BaseModel):
    id: str
    artifact_id: Optional["TextAttributeInput"] = None
    storage_id: Optional["TextAttributeInput"] = None
    line_number: Optional["NumberAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: Optional["RelatedNodeInput"] = None
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreObjectThreadCreateInput(BaseModel):
    id: Optional[str] = None
    object_path: "TextAttributeInput"
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: "RelatedNodeInput"
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreObjectThreadUpdateInput(BaseModel):
    id: str
    object_path: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    resolved: Optional["CheckboxAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: Optional["RelatedNodeInput"] = None
    comments: Optional[List[Optional["RelatedNodeInput"]]] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreChangeCommentCreateInput(BaseModel):
    id: Optional[str] = None
    text: "TextAttributeInput"
    created_at: Optional["TextAttributeInput"] = None
    change: "RelatedNodeInput"
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreChangeCommentUpdateInput(BaseModel):
    id: str
    text: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    change: Optional["RelatedNodeInput"] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreThreadCommentCreateInput(BaseModel):
    id: Optional[str] = None
    text: "TextAttributeInput"
    created_at: Optional["TextAttributeInput"] = None
    thread: "RelatedNodeInput"
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreThreadCommentUpdateInput(BaseModel):
    id: str
    text: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    thread: Optional["RelatedNodeInput"] = None
    created_by: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreRepositoryCreateInput(BaseModel):
    id: Optional[str] = None
    default_branch: Optional["TextAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    location: "TextAttributeInput"
    username: Optional["TextAttributeInput"] = None
    password: Optional["TextAttributeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    transformations: Optional[List[Optional["RelatedNodeInput"]]] = None
    queries: Optional[List[Optional["RelatedNodeInput"]]] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreRepositoryUpdateInput(BaseModel):
    id: str
    default_branch: Optional["TextAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    location: Optional["TextAttributeInput"] = None
    username: Optional["TextAttributeInput"] = None
    password: Optional["TextAttributeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    transformations: Optional[List[Optional["RelatedNodeInput"]]] = None
    queries: Optional[List[Optional["RelatedNodeInput"]]] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreReadOnlyRepositoryCreateInput(BaseModel):
    id: Optional[str] = None
    ref: Optional["TextAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    location: "TextAttributeInput"
    username: Optional["TextAttributeInput"] = None
    password: Optional["TextAttributeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    transformations: Optional[List[Optional["RelatedNodeInput"]]] = None
    queries: Optional[List[Optional["RelatedNodeInput"]]] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreReadOnlyRepositoryUpdateInput(BaseModel):
    id: str
    ref: Optional["TextAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    location: Optional["TextAttributeInput"] = None
    username: Optional["TextAttributeInput"] = None
    password: Optional["TextAttributeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    transformations: Optional[List[Optional["RelatedNodeInput"]]] = None
    queries: Optional[List[Optional["RelatedNodeInput"]]] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreTransformJinja2CreateInput(BaseModel):
    id: Optional[str] = None
    template_path: "TextAttributeInput"
    name: "TextAttributeInput"
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    timeout: Optional["NumberAttributeInput"] = None
    rebase: Optional["CheckboxAttributeInput"] = None
    query: "RelatedNodeInput"
    repository: "RelatedNodeInput"
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreTransformJinja2UpdateInput(BaseModel):
    id: str
    template_path: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    timeout: Optional["NumberAttributeInput"] = None
    rebase: Optional["CheckboxAttributeInput"] = None
    query: Optional["RelatedNodeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreDataCheckCreateInput(BaseModel):
    id: Optional[str] = None
    conflicts: "JSONAttributeInput"
    keep_branch: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: "TextAttributeInput"
    kind: "TextAttributeInput"
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreDataCheckUpdateInput(BaseModel):
    id: str
    conflicts: Optional["JSONAttributeInput"] = None
    keep_branch: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: Optional["TextAttributeInput"] = None
    kind: Optional["TextAttributeInput"] = None
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreStandardCheckCreateInput(BaseModel):
    id: Optional[str] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: "TextAttributeInput"
    kind: "TextAttributeInput"
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreStandardCheckUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: Optional["TextAttributeInput"] = None
    kind: Optional["TextAttributeInput"] = None
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreSchemaCheckCreateInput(BaseModel):
    id: Optional[str] = None
    conflicts: "JSONAttributeInput"
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: "TextAttributeInput"
    kind: "TextAttributeInput"
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreSchemaCheckUpdateInput(BaseModel):
    id: str
    conflicts: Optional["JSONAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: Optional["TextAttributeInput"] = None
    kind: Optional["TextAttributeInput"] = None
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreFileCheckCreateInput(BaseModel):
    id: Optional[str] = None
    files: Optional["ListAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: "TextAttributeInput"
    kind: "TextAttributeInput"
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class ListAttributeInput(BaseModel):
    is_visible: Optional[bool] = None
    is_protected: Optional[bool] = None
    source: Optional[str] = None
    owner: Optional[str] = None
    value: Optional[Any] = None


class CoreFileCheckUpdateInput(BaseModel):
    id: str
    files: Optional["ListAttributeInput"] = None
    commit: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: Optional["TextAttributeInput"] = None
    kind: Optional["TextAttributeInput"] = None
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactCheckCreateInput(BaseModel):
    id: Optional[str] = None
    changed: Optional["CheckboxAttributeInput"] = None
    checksum: Optional["TextAttributeInput"] = None
    artifact_id: Optional["TextAttributeInput"] = None
    storage_id: Optional["TextAttributeInput"] = None
    line_number: Optional["NumberAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: "TextAttributeInput"
    kind: "TextAttributeInput"
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactCheckUpdateInput(BaseModel):
    id: str
    changed: Optional["CheckboxAttributeInput"] = None
    checksum: Optional["TextAttributeInput"] = None
    artifact_id: Optional["TextAttributeInput"] = None
    storage_id: Optional["TextAttributeInput"] = None
    line_number: Optional["NumberAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    origin: Optional["TextAttributeInput"] = None
    kind: Optional["TextAttributeInput"] = None
    message: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    severity: Optional["TextAttributeInput"] = None
    created_at: Optional["TextAttributeInput"] = None
    validator: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreDataValidatorCreateInput(BaseModel):
    id: Optional[str] = None
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    proposed_change: "RelatedNodeInput"
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreDataValidatorUpdateInput(BaseModel):
    id: str
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    proposed_change: Optional["RelatedNodeInput"] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreRepositoryValidatorCreateInput(BaseModel):
    id: Optional[str] = None
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    repository: "RelatedNodeInput"
    proposed_change: "RelatedNodeInput"
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreRepositoryValidatorUpdateInput(BaseModel):
    id: str
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    proposed_change: Optional["RelatedNodeInput"] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreUserValidatorCreateInput(BaseModel):
    id: Optional[str] = None
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    check_definition: "RelatedNodeInput"
    repository: "RelatedNodeInput"
    proposed_change: "RelatedNodeInput"
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreUserValidatorUpdateInput(BaseModel):
    id: str
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    check_definition: Optional["RelatedNodeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    proposed_change: Optional["RelatedNodeInput"] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreSchemaValidatorCreateInput(BaseModel):
    id: Optional[str] = None
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    proposed_change: "RelatedNodeInput"
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreSchemaValidatorUpdateInput(BaseModel):
    id: str
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    proposed_change: Optional["RelatedNodeInput"] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactValidatorCreateInput(BaseModel):
    id: Optional[str] = None
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    definition: "RelatedNodeInput"
    proposed_change: "RelatedNodeInput"
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactValidatorUpdateInput(BaseModel):
    id: str
    label: Optional["TextAttributeInput"] = None
    state: Optional["TextAttributeInput"] = None
    conclusion: Optional["TextAttributeInput"] = None
    completed_at: Optional["TextAttributeInput"] = None
    started_at: Optional["TextAttributeInput"] = None
    definition: Optional["RelatedNodeInput"] = None
    proposed_change: Optional["RelatedNodeInput"] = None
    checks: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreCheckDefinitionCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    file_path: "TextAttributeInput"
    class_name: "TextAttributeInput"
    timeout: Optional["NumberAttributeInput"] = None
    rebase: Optional["CheckboxAttributeInput"] = None
    parameters: Optional["JSONAttributeInput"] = None
    repository: "RelatedNodeInput"
    query: Optional["RelatedNodeInput"] = None
    targets: Optional["RelatedNodeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreCheckDefinitionUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    file_path: Optional["TextAttributeInput"] = None
    class_name: Optional["TextAttributeInput"] = None
    timeout: Optional["NumberAttributeInput"] = None
    rebase: Optional["CheckboxAttributeInput"] = None
    parameters: Optional["JSONAttributeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    query: Optional["RelatedNodeInput"] = None
    targets: Optional["RelatedNodeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreTransformPythonCreateInput(BaseModel):
    id: Optional[str] = None
    file_path: "TextAttributeInput"
    class_name: "TextAttributeInput"
    name: "TextAttributeInput"
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    timeout: Optional["NumberAttributeInput"] = None
    rebase: Optional["CheckboxAttributeInput"] = None
    query: "RelatedNodeInput"
    repository: "RelatedNodeInput"
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreTransformPythonUpdateInput(BaseModel):
    id: str
    file_path: Optional["TextAttributeInput"] = None
    class_name: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    label: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    timeout: Optional["NumberAttributeInput"] = None
    rebase: Optional["CheckboxAttributeInput"] = None
    query: Optional["RelatedNodeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreGraphQLQueryCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    query: "TextAttributeInput"
    variables: Optional["JSONAttributeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreGraphQLQueryUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    query: Optional["TextAttributeInput"] = None
    variables: Optional["JSONAttributeInput"] = None
    repository: Optional["RelatedNodeInput"] = None
    tags: Optional[List[Optional["RelatedNodeInput"]]] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    status: "TextAttributeInput"
    content_type: "TextAttributeInput"
    checksum: Optional["TextAttributeInput"] = None
    storage_id: Optional["TextAttributeInput"] = None
    parameters: Optional["JSONAttributeInput"] = None
    object: "RelatedNodeInput"
    definition: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    status: Optional["TextAttributeInput"] = None
    content_type: Optional["TextAttributeInput"] = None
    checksum: Optional["TextAttributeInput"] = None
    storage_id: Optional["TextAttributeInput"] = None
    parameters: Optional["JSONAttributeInput"] = None
    object: Optional["RelatedNodeInput"] = None
    definition: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactDefinitionCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    artifact_name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    parameters: "JSONAttributeInput"
    content_type: "TextAttributeInput"
    targets: "RelatedNodeInput"
    transformation: "RelatedNodeInput"
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreArtifactDefinitionUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    artifact_name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    parameters: Optional["JSONAttributeInput"] = None
    content_type: Optional["TextAttributeInput"] = None
    targets: Optional["RelatedNodeInput"] = None
    transformation: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreStandardWebhookCreateInput(BaseModel):
    id: Optional[str] = None
    shared_key: "TextAttributeInput"
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    url: "TextAttributeInput"
    validate_certificates: Optional["CheckboxAttributeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreStandardWebhookUpdateInput(BaseModel):
    id: str
    shared_key: Optional["TextAttributeInput"] = None
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    url: Optional["TextAttributeInput"] = None
    validate_certificates: Optional["CheckboxAttributeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreCustomWebhookCreateInput(BaseModel):
    id: Optional[str] = None
    name: "TextAttributeInput"
    description: Optional["TextAttributeInput"] = None
    url: "TextAttributeInput"
    validate_certificates: Optional["CheckboxAttributeInput"] = None
    transformation: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreCustomWebhookUpdateInput(BaseModel):
    id: str
    name: Optional["TextAttributeInput"] = None
    description: Optional["TextAttributeInput"] = None
    url: Optional["TextAttributeInput"] = None
    validate_certificates: Optional["CheckboxAttributeInput"] = None
    transformation: Optional["RelatedNodeInput"] = None
    member_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None
    subscriber_of_groups: Optional[List[Optional["RelatedNodeInput"]]] = None


class CoreAccountTokenCreateInput(BaseModel):
    name: Optional[str] = None
    expiration: Optional[str] = None


class CoreAccountUpdateSelfInput(BaseModel):
    password: Optional[str] = None
    description: Optional[str] = None


class ProposedChangeRequestRunCheckInput(BaseModel):
    id: str
    check_type: Optional[CheckType] = None


class BranchCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    origin_branch: Optional[str] = None
    branched_from: Optional[str] = None
    is_data_only: Optional[bool] = None


class BranchNameInput(BaseModel):
    name: Optional[str] = None


class BranchUpdateInput(BaseModel):
    name: str
    description: str


class TaskCreateInput(BaseModel):
    id: Optional[Any] = None
    title: str
    created_by: Optional[str] = None
    conclusion: TaskConclusion
    related_node: Optional[str] = None
    logs: Optional[List[Optional["RelatedTaskLogCreateInput"]]] = None


class RelatedTaskLogCreateInput(BaseModel):
    message: str
    severity: Severity


class TaskUpdateInput(BaseModel):
    id: Any
    title: Optional[str] = None
    conclusion: Optional[TaskConclusion] = None
    logs: Optional[List[Optional["RelatedTaskLogCreateInput"]]] = None


class RelationshipNodesInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    nodes: Optional[List[Optional["RelatedNodeInput"]]] = None


class SchemaDropdownAddInput(BaseModel):
    kind: str
    attribute: str
    dropdown: str
    color: Optional[str] = None
    description: Optional[str] = None
    label: Optional[str] = None


class SchemaDropdownRemoveInput(BaseModel):
    kind: str
    attribute: str
    dropdown: str


class SchemaEnumInput(BaseModel):
    kind: str
    attribute: str
    enum: str
