# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RebaseBranch(BaseModel):
    branch_rebase: Optional["RebaseBranchBranchRebase"] = Field(alias="BranchRebase")


class RebaseBranchBranchRebase(BaseModel):
    ok: Optional[bool]
