# Generated by ariadne-codegen
# Source: queries/sdk/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateTask(BaseModel):
    infrahub_task_update: Optional["UpdateTaskInfrahubTaskUpdate"] = Field(
        alias="InfrahubTaskUpdate"
    )


class UpdateTaskInfrahubTaskUpdate(BaseModel):
    ok: Optional[bool]
