import { gql } from "@apollo/client";
import { Icon } from "@iconify-icon/react";
import { useAtomValue } from "jotai";
import { useEffect, useState } from "react";
import type { ITreeViewOnLoadDataProps, NodeId } from "react-accessible-treeview";
import { Link, useNavigate } from "react-router";

import { useLazyQuery } from "@/shared/api/graphql/useQuery";
import { Tree, type TreeItemProps, type TreeProps } from "@/shared/components/ui/tree";
import useFilters, { type Filter } from "@/shared/hooks/useFilters";
import { datetimeAtom } from "@/shared/stores/time.atom";
import { isElementInViewport } from "@/shared/utils/element";

import { useCurrentBranch } from "@/entities/branches/ui/branches-provider";
import { TREE_ROOT_ID } from "@/entities/ipam/constants";
import { EMPTY_TREE, updateTreeData } from "@/entities/ipam/ipam-tree/utils";
import {
  objectAncestorsQuery,
  objectChildrenQuery,
  objectTopLevelTreeQuery,
} from "@/entities/nodes/api/objectTreeQuery";
import type { NodeCore } from "@/entities/nodes/types";
import { getObjectDetailsUrl } from "@/entities/nodes/utils";
import { genericSchemasAtom, nodeSchemasAtom } from "@/entities/schema/stores/schema.atom";
import type { ModelSchema } from "@/entities/schema/types";

export const HIDE_AUTO_GENERATED_FILTER: Filter = { name: "group_type__value", value: "default" };

export type HierarchicalTreeProps = {
  schema: ModelSchema;
  className?: string;
  currentNodeId?: string;
};

export const HierarchicalTree = ({ schema, currentNodeId, className }: HierarchicalTreeProps) => {
  const navigate = useNavigate();
  const { currentBranch } = useCurrentBranch();
  const currentDate = useAtomValue(datetimeAtom);
  const [filters] = useFilters();
  const hasAutoGeneratedFiltered = filters.some(
    (filter) =>
      filter.name === HIDE_AUTO_GENERATED_FILTER.name &&
      filter.value === HIDE_AUTO_GENERATED_FILTER.value
  );

  const [treeData, setTreeData] = useState<TreeProps["data"]>(EMPTY_TREE);
  const [expandedIds, setExpandedIds] = useState<NodeId[]>([]);
  const [selectedIds, setSelectedIds] = useState<NodeId[]>([]);

  const [getObjectTopLevelTree] = useLazyQuery(
    gql(
      objectTopLevelTreeQuery({
        kind: schema.kind,
        filters: hasAutoGeneratedFiltered ? `group_type__value: "default"` : undefined,
      })
    )
  );
  const [getObjectAncestors] = useLazyQuery(gql(objectAncestorsQuery({ kind: schema.kind })));
  const [getTreeItemChildren] = useLazyQuery(gql(objectChildrenQuery({ kind: schema.kind })));
  const [isLoading, setLoading] = useState(true);

  const fetchTree = async () => {
    setLoading(true);
    const { data } = await getObjectTopLevelTree();
    if (!data) return;

    const topLevelTreeItems = formatResponseDataForTreeView(data[schema.kind!]);
    const treeWithTopLevelPrefixesOnly = updateTreeData(
      EMPTY_TREE,
      TREE_ROOT_ID,
      topLevelTreeItems
    );

    if (!currentNodeId) {
      return treeWithTopLevelPrefixesOnly;
    }

    const { data: objectAncestorsData } = await getObjectAncestors({
      variables: { ids: [currentNodeId] },
    });

    const currentObjectData = objectAncestorsData[schema.kind!].edges[0];

    if (!currentObjectData) {
      console.error(`Prefix ${currentNodeId} not found.`);
      return treeWithTopLevelPrefixesOnly;
    }

    const ancestors = currentObjectData.node.ancestors.edges;
    const orderedAncestors: typeof ancestors = [];

    const traverseHierarchy = (map: typeof ancestors, parentId: string | null) => {
      const child = map.find(({ node }: any) => {
        return node.parent.node === parentId || node.parent.node?.id === parentId;
      });
      if (!child) return;

      orderedAncestors.push(child);

      if (child?.node?.children?.count > 0) {
        child.node.children.edges.forEach((c: any) => orderedAncestors.push(c));
      }
      traverseHierarchy(map, child.node.id);
    };

    traverseHierarchy(ancestors, null);

    const orderedAncestorsFormattedForTree = formatResponseDataForTreeView({
      edges: [...orderedAncestors, currentObjectData],
    });
    setExpandedIds(ancestors.map((x: any) => x.node.id));
    return updateHierarchicalTree(treeWithTopLevelPrefixesOnly, orderedAncestorsFormattedForTree);
  };

  useEffect(() => {
    setLoading(true);
    setSelectedIds([]);
    setExpandedIds([]);

    let isCancelled = false;
    fetchTree().then((tree) => {
      if (isCancelled) return;
      if (!tree) return;

      setLoading(false);
      setTreeData(tree);
      if (currentNodeId) {
        setSelectedIds([currentNodeId]);
      }
    });

    return () => {
      isCancelled = true;
    };
  }, [schema.kind, currentBranch, currentDate, hasAutoGeneratedFiltered]);

  useEffect(() => {
    const selectedId = selectedIds[0];
    if (!selectedId) return;

    const element = document.getElementById(selectedId.toString());
    if (!element) return;

    const isInViewport = isElementInViewport(element);
    if (!isInViewport) {
      element.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "start" });
    }
  }, [selectedIds]);

  useEffect(() => {
    if (currentNodeId) {
      setSelectedIds([currentNodeId]);
    } else {
      setSelectedIds([]);
    }
  }, [currentNodeId]);

  const onLoadData = async ({ element }: ITreeViewOnLoadDataProps) => {
    if (!element.isBranch || element.children.length > 0) return; // To avoid refetching data

    const { data } = await getTreeItemChildren({
      variables: { parentIds: [element.id.toString()] },
    });

    if (!data) return;

    const treeNodes = formatResponseDataForTreeView(data[schema.kind!]);
    setTreeData((tree) => updateTreeData(tree, element.id.toString(), treeNodes));
  };

  return (
    <Tree
      loading={isLoading}
      data={treeData}
      itemContent={ObjectTreeItem}
      defaultExpandedIds={expandedIds}
      selectedIds={selectedIds}
      onLoadData={onLoadData}
      onNodeSelect={({ element, isSelected }) => {
        if (!isSelected) return;

        const url = getObjectDetailsUrl(element.metadata?.kind as string, element.id.toString());
        navigate(url);
      }}
      className={className}
      data-testid="hierarchical-tree"
    />
  );
};

const ObjectTreeItem = ({ element }: TreeItemProps) => {
  const nodes = useAtomValue(nodeSchemasAtom);
  const generics = useAtomValue(genericSchemasAtom);

  const schema = [...nodes, ...generics].find(({ kind }) => kind === element.metadata?.kind);

  const url = getObjectDetailsUrl(schema?.kind as string, element.id.toString());
  return (
    <Link
      to={url}
      tabIndex={-1}
      className="flex items-center gap-2"
      data-testid="hierarchical-tree-item"
      id={element.id.toString()}
    >
      {schema?.icon ? (
        <Icon icon={schema.icon as string} className="w-4" />
      ) : (
        <div className="w-4" />
      )}
      <span className="whitespace-nowrap">{element.name}</span>
    </Link>
  );
};

export const formatResponseDataForTreeView = (data: {
  edges: Array<{ node: any }>;
}): TreeItemProps["element"][] => {
  return data.edges.map(({ node }) => ({
    id: node.id,
    name: node.display_label,
    parent: node.parent.node?.id ?? TREE_ROOT_ID,
    children: node.children?.edges?.map(({ node }: { node: NodeCore }) => node.id) ?? [],
    isBranch: node.children.count > 0,
    metadata: {
      kind: node.__typename,
    },
  }));
};

export const updateHierarchicalTree = (list: TreeProps["data"], children: TreeProps["data"]) => {
  return children.reduce((acc, currentChild) => {
    // new tree item needs to be added in 2 locations:
    // 1. new tree item should be ths in list (once only)
    // 2. new tree item's id should be in its parent's children array (once only)
    const data = acc.map((node) => {
      if (node.id === currentChild.parent) {
        node.children = [...new Set([...node.children, currentChild.id])];
      }
      return node;
    });

    const isChildrenAlreadyPresent = data.some(({ id }) => id === currentChild.id);

    return isChildrenAlreadyPresent ? data : [...data, currentChild];
  }, list);
};
