import { Icon } from "@iconify-icon/react";
import { Button } from "@infrahub/ui";
import { useState } from "react";

import { Col, Row } from "@/shared/components/container";
import ErrorScreen from "@/shared/components/errors/error-screen";
import { SearchInput } from "@/shared/components/inputs/search-input";
import { LoadingIndicator } from "@/shared/components/loading/loading-indicator";

import { AddGroupTriggerButton } from "@/entities/groups/ui/add-group-trigger-button";
import { ObjectGroupsList } from "@/entities/groups/ui/object-groups-list";
import { useGetGroups } from "@/entities/groups/ui/queries/get-groups.query";
import { getNodeLabel } from "@/entities/nodes/object/utils/get-node-label";
import type { ModelSchema } from "@/entities/schema/types";

export interface GroupsManagerProps {
  className?: string;
  schema: ModelSchema;
  objectId: string;
}

export function GroupsManager({ className, schema, objectId }: GroupsManagerProps) {
  const [query, setQuery] = useState("");
  const [displayAutoGenerated, setDisplayAutoGenerated] = useState(false);

  const { isPending, error, data } = useGetGroups({
    objectKind: schema.kind!,
    objectId,
  });

  if (isPending) {
    return <LoadingIndicator className="p-4" />;
  }

  if (error) {
    return <ErrorScreen message={error.message} />;
  }

  const { groups: currentObjectGroups, permission } = data;

  const hasAutoGeneratedGroups = currentObjectGroups.some(
    (group) => group.group_type?.value === "internal"
  );

  const groupsFilteredBySearch =
    query === ""
      ? currentObjectGroups
      : currentObjectGroups.filter((group) =>
          getNodeLabel(group).toLowerCase().includes(query.toLowerCase())
        );

  const filteredVisibleGroups = groupsFilteredBySearch.filter(
    (group) => displayAutoGenerated || group.group_type?.value !== "internal"
  );

  return (
    <Col className={className}>
      <Row>
        <SearchInput onChange={setQuery} placeholder="filter groups..." />

        <AddGroupTriggerButton
          schema={schema}
          objectId={objectId}
          currentGroups={currentObjectGroups}
          permission={permission}
        />
      </Row>

      {hasAutoGeneratedGroups && (
        <Button
          onPress={() => setDisplayAutoGenerated((v) => !v)}
          className="ml-auto shrink-0 text-custom-blue-700"
          variant="ghost"
          size="sm"
        >
          auto-generated
          <Icon icon={displayAutoGenerated ? "mdi:eye" : "mdi:eye-off"} />
        </Button>
      )}

      <ObjectGroupsList
        objectId={objectId}
        groups={filteredVisibleGroups}
        className="grow overflow-auto"
      />
    </Col>
  );
}
