import { Icon } from "@iconify-icon/react";
import { useState } from "react";

import ErrorScreen from "@/shared/components/errors/error-screen";
import NoDataFound from "@/shared/components/errors/no-data-found";
import { LoadingIndicator } from "@/shared/components/loading/loading-indicator";
import { Button } from "@/shared/components/ui/button";
import { SearchInput } from "@/shared/components/ui/search-input";
import { classNames } from "@/shared/utils/common";

import AddGroupTriggerButton from "@/entities/groups/ui/add-group-trigger-button";
import ObjectGroupsList from "@/entities/groups/ui/object-groups-list";
import { useGetGroups } from "@/entities/groups/ui/queries/get-groups.query";
import { getNodeLabel } from "@/entities/nodes/object/utils/get-node-label";
import type { ModelSchema } from "@/entities/schema/types";

export type GroupsManagerProps = {
  className?: string;
  schema: ModelSchema;
  objectId: string;
  onUpdateCompleted?: () => void;
};

export const GroupsManager = ({ className, schema, objectId }: GroupsManagerProps) => {
  const [query, setQuery] = useState("");
  const [displayAutoGenerated, setDisplayAutoGenerated] = useState(false);

  const { isLoading, error, data } = useGetGroups({
    objectKind: schema.kind!,
    objectId,
  });

  if (isLoading) {
    return <LoadingIndicator className="p-4" />;
  }

  if (error) {
    return <ErrorScreen message={error.message} />;
  }

  if (!data?.objectFound) {
    return (
      <NoDataFound
        message={
          <div>
            <div className="mb-4 text-center">No data found.</div>
            <div className="text-sm">
              <span className="font-semibold">Kind</span>: {schema.kind}
            </div>
            <div className="text-sm">
              <span className="font-semibold">Id</span>: {objectId}
            </div>
          </div>
        }
      />
    );
  }

  const { groups: currentObjectGroups, permission } = data;

  const hasAutoGeneratedGroups = currentObjectGroups.some(
    (group) => group.group_type?.value === "internal"
  );

  const groupsFilteredBySearch =
    query === ""
      ? currentObjectGroups
      : currentObjectGroups.filter((group) =>
          getNodeLabel(group).toLowerCase().includes(query.toLowerCase())
        );

  const filteredVisibleGroups = groupsFilteredBySearch.filter(
    (n) => displayAutoGenerated || n.group_type?.value !== "internal"
  );

  return (
    <div className={classNames("flex h-full flex-col gap-2", className)}>
      <div className="flex gap-2">
        <SearchInput
          containerClassName="grow"
          className="h-9"
          onChange={(e) => setQuery(e.target.value)}
          placeholder="filter groups..."
        />

        <AddGroupTriggerButton
          schema={schema}
          objectId={objectId}
          currentGroups={currentObjectGroups}
          permission={permission}
        />
      </div>

      {hasAutoGeneratedGroups && (
        <Button
          onClick={() => setDisplayAutoGenerated((v) => !v)}
          className="ml-auto shrink-0 text-custom-blue-700"
          variant="ghost"
          size="sm"
        >
          auto-generated
          <Icon className="ml-1" icon={displayAutoGenerated ? "mdi:eye" : "mdi:eye-off"} />
        </Button>
      )}

      <ObjectGroupsList
        objectId={objectId}
        groups={filteredVisibleGroups}
        className="grow overflow-auto"
      />
    </div>
  );
};
