import { ACCOUNT_TOKEN_OBJECT } from "@/config/constants";
import { NodeSchema } from "@/entities/schema/types";

export const tokenSchema: NodeSchema = {
  id: "17e2a71e-2ac0-bf55-3105-c516dbe1b504",
  state: "present",
  name: "AccountToken",
  namespace: "Infrahub",
  description: "A User Token used for API access.",
  label: "Account Token",
  branch: "aware",
  default_filter: null,
  human_friendly_id: null,
  display_labels: ["name__value"],
  include_in_menu: true,
  menu_placement: null,
  icon: null,
  order_by: null,
  uniqueness_constraints: null,
  documentation: null,
  generate_template: false,
  attributes: [
    {
      id: "17e2a71e-4faa-2e82-3109-c51dff39f069",
      state: "present",
      name: "name",
      kind: "Text",
      enum: null,
      choices: null,
      regex: null,
      max_length: null,
      min_length: null,
      label: "Name",
      description: "Name of the user token.",
      read_only: false,
      unique: false,
      optional: false,
      branch: "aware",
      order_weight: 1000,
      default_value: null,
      inherited: false,
      allow_override: "any",
    },
    {
      id: "17e2a71e-7c88-723c-3102-c51bff58788b",
      state: "present",
      name: "expiration",
      kind: "DateTime",
      enum: null,
      choices: null,
      regex: null,
      max_length: null,
      min_length: null,
      label: "Expiration",
      description: "Expiration date.",
      read_only: false,
      unique: false,
      optional: true,
      branch: "aware",
      order_weight: 4000,
      default_value: null,
      inherited: false,
      allow_override: "any",
    },
  ],
  relationships: [],
  inherit_from: [],
  generate_profile: false,
  hierarchy: null,
  parent: null,
  children: null,
  kind: ACCOUNT_TOKEN_OBJECT,
  hash: "2cfd9af9d6fcac49527fca295de251b8",
};
