export const QSP = {
  BRANCH: "branch",
  SOURCE_BRANCH: "source_branch",
  KIND: "kind",
  DATETIME: "at",
  FILTER: "filters",
  HIDE_COLUMNS: "hide_columns",
  SHOW_COLUMNS: "show_columns",
  PAGINATION: "pagination",
  PROPOSED_CHANGES_STATE: "pr_state",
  QUERY: "query",
  SEARCH: "search",
  SORT: "sort",
  IPAM_NAMESPACE: "namespace",
  STATUS: "status",
  HIGHLIGHT: "highlight",
} as const;
