export const QSP = {
  BRANCH_TAB: "branch_tab",
  BRANCH: "branch",
  SOURCE_BRANCH: "source_branch",
  KIND: "kind",
  DATETIME: "at",
  FILTER: "filters",
  PAGINATION: "pagination",
  PROPOSED_CHANGES_TAB: "tab",
  PROPOSED_CHANGES_STATE: "pr_state",
  QUERY: "query",
  TAB: "tab",
  TASK_ID: "task_id",
  SEARCH: "search",
  STATUS: "status",
} as const;
