[project]
name = "infrahub-testcontainers"
version = "1.3.0a0"
description = "Testcontainers instance for Infrahub to easily build integration tests"
authors = [{ name = "OpsMill", email = "info@opsmill.com" }]
requires-python = ">=3.9"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "testcontainers>=4.8,<4.9",
    "psutil",
    "pytest",
    "httpx<0.28",
    "pydantic>=2.10.6,<3",
]

[project.urls]
Homepage = "https://opsmill.com"
Repository = "https://github.com/opsmill/infrahub"

[project.entry-points.pytest11]
pytest-infrahub-performance-test = "infrahub_testcontainers.plugin"

[dependency-groups]
dev = ["rich>=13.9.4,<14"]

[tool.hatch.build.targets.sdist]
include = [
    "infrahub_testcontainers",
    "infrahub_testcontainers/docker-compose.test.yml",
    "infrahub_testcontainers/haproxy.cfg",
    "infrahub_testcontainers/prometheus.yml",
]

[tool.hatch.build.targets.wheel]
include = [
    "infrahub_testcontainers",
    "infrahub_testcontainers/docker-compose.test.yml",
    "infrahub_testcontainers/haproxy.cfg",
    "infrahub_testcontainers/prometheus.yml",
]
