[project]
name = "infrahub-testcontainers"
version = "1.10.0b0"
requires-python = ">=3.10"

description = "Testcontainers instance for Infrahub to easily build integration tests"
authors = [{ name = "OpsMill", email = "info@opsmill.com" }]
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

dependencies = [
    "testcontainers>=4.8,<4.9",
    "psutil",
    "pytest",
    "httpx>=0.20",
    "pydantic>=2.10.6,<3",
    "prefect-client==3.7.4",
]

[project.urls]
Homepage = "https://opsmill.com"
Repository = "https://github.com/opsmill/infrahub"

[project.entry-points.pytest11]
pytest-infrahub-performance-test = "infrahub_testcontainers.plugin"

[dependency-groups]
dev = [
    "rich>=13.9.4,<14",
    "pytest-cov==7.0.0",
    "pytest-xdist>=3.4,<3.5",
]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
preview = true


select = ["ALL"]

ignore = [
    "D",        # pydocstyle
    "DOC",      # pydoclint
    "CPY",      # flake8-copyright
    "T201",     # use of `print`
    "ISC",      # flake8-implicit-str-concat
    "COM812",   # missing-trailing-comma
    "S101",     # Use of assert allowed as the producation code is used within tests
]

[tool.ruff.lint.per-file-ignores]

"infrahub_testcontainers/**.py" = [
    ##################################################################################################
    # Rules below needs to be Investigated                                                           #
    ##################################################################################################
    "BLE001",   # Do not catch blind exception: `Exception`
    "C901",     # `database_restore_backup` is too complex (22 > 10)
    "E501",     # Line too long
    "EM101",    # Exception must not use a string literal, assign to variable first
    "EM102",    # Exception must not use an f-string literal, assign to variable first
    "FBT001",   # Boolean-typed positional argument in function definition — breaking change to fix
    "FBT002",   # Boolean default positional argument in function definition — breaking change to fix
    "PERF203",  # `try`-`except` within a loop incurs performance overhead
    "PLR0912",  # Too many branches
    "PLR0914",  # Too many local variables
    "PLR6301",  # Method `infrahub_app` could be a function, class method, or static method
    "SLF001",   # Private member accessed: `_session` (pytest internal API, no public alternative)
    "TRY002",   # Create your own exception
    "TRY003",   # Avoid specifying long messages outside the exception class
]


[tool.hatch.build.targets.sdist]
include = [
    "infrahub_testcontainers",
    "infrahub_testcontainers/docker-compose.test.yml",
    "infrahub_testcontainers/haproxy.cfg",
    "infrahub_testcontainers/prometheus.yml",
]

[tool.hatch.build.targets.wheel]
include = [
    "infrahub_testcontainers",
    "infrahub_testcontainers/docker-compose.test.yml",
    "infrahub_testcontainers/haproxy.cfg",
    "infrahub_testcontainers/prometheus.yml",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
