{
 "title": "Infrahub Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "datasource_loki", "label": "Loki", "query": "loki" },
   { "name": "app_name", "label": "Application", "query": { "query": "label_values(app_name)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "job_loki",
    "label": "Loki Job",
    "query": {}
   },
   { "name": "job_prometheus", "label": "Job Prometheus", "query": { "query": "label_values(job)" } },
   {
    "name": "percentile",
    "label": "percentile",
    "query": "p99 : 0.99 , p95 : 0.95 , p90 : 0.90"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Availability (Success Rate)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(infrahub_requests_total{status_code=~\"2..\"}[5m])) / sum(rate(infrahub_requests_total[5m])) * 100",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Error Rates (4XX & 5XX)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(infrahub_requests_total{status_code=~\"4..\"}[5m])) / sum(rate(infrahub_requests_total[5m])) * 100",
     "legendFormat": "4XX Error Rate"
    },
    {
     "expr": "sum(rate(infrahub_requests_total{status_code=~\"5..\"}[5m])) / sum(rate(infrahub_requests_total[5m])) * 100",
     "legendFormat": "5XX Error Rate"
    }
   ]
  },
  {
   "title": "Average Response Time (HTTP & GraphQL)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(infrahub_request_duration_seconds_sum[5m])) / avg(rate(infrahub_request_duration_seconds_count[5m]))",
     "legendFormat": "HTTP Avg Response Time"
    },
    {
     "expr": "avg(rate(infrahub_graphql_duration_seconds_sum[5m])) / avg(rate(infrahub_graphql_duration_seconds_count[5m]))",
     "legendFormat": "GraphQL Avg Response Time"
    }
   ]
  },
  {
   "title": "Request Volume (Requests per Second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(infrahub_requests_total[5m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Warning logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{container=~\".*(database|server|task|git|cache|queue).*\", container!~\".*run.*\", container=~\"$container\" , level=~\"(?i)WARN.*\"}| line_format \"{{__timestamp__ | date `2006-01-02 15:04:05.00` }}\\t{{.container| replace `infrahub-` ``}}\\t{{.level}}\\t{{.logger}}\\t{{.message}}\""
    }
   ]
  },
  {
   "title": "Error/Critical logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "{container=~\".*(database|server|task|git|cache).*\", container!~\".*run.*\", container=~\"$container\" , level=~\"(?i)ERR.*|CRIT|FATAL.*\"}| line_format \"{{__timestamp__ | date `2006-01-02 15:04:05.00` }}\\t{{.container| replace `infrahub-` ``}}\\t{{.level}}\\t{{.logger}}\\t{{.message}}\""
    }
   ]
  },
  { "title": "Details Requests [$app_name]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "app_name" },
  {
   "title": "Percent of 4XX Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", status_code=~\"4.+\", path!=\"/metrics\"}) / sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}) or vector(0)",
     "legendFormat": "{{methode}} - {{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5XX Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", status_code=~\"5.+\", path!=\"/metrics\"}) / sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}) or vector(0)",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_request_duration_seconds_bucket[1m])) by (le, method, path, status_code))",
     "legendFormat": "{{method}} {{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(infrahub_requests_total{app_name=\"$app_name\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "infrahub_requests_in_progress{app_name=\"$app_name\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Details DB Query/GraphQL [$app_name]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "app_name"
  },
  {
   "title": "GraphQL Query Duration ($percentile percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_duration_seconds_bucket[1m])) by (le, branch, name, operation, query_id, type))",
     "legendFormat": "{{branch}} - {{name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "DB Query Execution Time ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_db_query_execution_seconds_bucket[1m])) by (le, query, type))",
     "legendFormat": "{{query}} - {{type}}"
    }
   ]
  },
  {
   "title": "Number Slow Queries (>0.5s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(infrahub_db_query_execution_seconds_count[5m]) - ignoring(le) increase(infrahub_db_query_execution_seconds_bucket{le=\"0.5\"}[5m]) > 0",
     "legendFormat": "{{query}} {{type}}"
    }
   ]
  },
  {
   "title": "Lock Reserved Duration ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_lock_reserved_duration_seconds_bucket[1m])) by (le, lock, type))",
     "legendFormat": "{{lock}} - {{type}}"
    }
   ]
  },
  {
   "title": "Lock Acquire Time ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_lock_acquire_seconds_bucket[1m])) by (le, lock, type))",
     "legendFormat": "{{lock}} - {{type}}"
    }
   ]
  },
  {
   "title": "GraphQL Response Size ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_response_size_bytes_bucket[1m])) by (le, branch, name, operation, query_id, type))",
     "legendFormat": "{{branch}} - {{name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "GraphQL Query Objects ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_query_objects_bucket[1m])) by (le, branch, name, operation, query_id, type))",
     "legendFormat": "{{branch}} - {{name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "GraphQL Schema Generation Time ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_generate_schema_bucket[1m])) by (le, branch))",
     "legendFormat": "{{branch}}"
    }
   ]
  },
  {
   "title": "GraphQL Query Height ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_query_height_bucket[1m])) by (le, branch, name, operation, query_id, type))",
     "legendFormat": "{{branch}} - {{name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "GraphQL Query Depth ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_query_depth_bucket[1m])) by (le, branch, name, operation, query_id, type))",
     "legendFormat": "{{branch}} - {{name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "GraphQL Top Level Queries ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(infrahub_graphql_top_level_queries_bucket[1m])) by (le, branch, name, operation, query_id, type))",
     "legendFormat": "{{branch}} - {{name}} - {{operation}}"
    }
   ]
  },
  { "title": "Logs [$app_name]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }, "repeat": "app_name" },
  {
   "title": "Logs Type Rate  (per Container and Level)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by (container, level) (rate({container=~\".*(queue|database|server|git|task|cache).*\", container!~\".*run.*\", container=~\"$container\"} | label_format container=`{{.container| replace \"infrahub-\" \"\"}}`| label_format level=`{{.level|lower}}` | level != \"\" [1m]))",
     "legendFormat": "{{ container }} - {{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 18, "x": 6, "y": 95 },
   "targets": [
    {
     "expr": "{container=~\".*(queue|database|server|git|task|cache).*\", container!~\".*run.*\", container=~\"$container\"} | line_format \"{{__timestamp__ | date `2006-01-02 15:04:05.00` }}\\t{{.container| replace `infrahub-` ``}}\\t{{.level}}\\t{{.logger}}\\t{{.message}}\""
    }
   ]
  }
 ]
}