{
 "title": "Infrahub",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(infrahub_request_duration_seconds_sum[$__rate_interval]) / rate(infrahub_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Number of API queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(infrahub_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Database Query Read Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(infrahub_db_query_read_execution_seconds_sum[$__rate_interval]) / rate(infrahub_db_query_read_execution_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}