PROCESS_AUTOMATION_NAME_PREFIX = "Computed-attribute-process"
QUERY_AUTOMATION_NAME_PREFIX = "Computed-attribute-query"

PROCESS_AUTOMATION_NAME = PROCESS_AUTOMATION_NAME_PREFIX + "::{identifier}::{scope}"
QUERY_AUTOMATION_NAME = QUERY_AUTOMATION_NAME_PREFIX + "::{identifier}::{scope}"
