export const QSP = {
  BRANCH_TAB: "branch_tab",
  BRANCH_DIFF_TAB: "branch_diff_tab",
  BRANCH_FILTER_BRANCH_ONLY: "branch_only",
  BRANCH_FILTER_TIME_FROM: "time_from",
  BRANCH_FILTER_TIME_TO: "time_to",
  BRANCH: "branch",
  VALIDATOR_DETAILS: "validator",
  DATETIME: "at",
  FILTER: "filters",
  PAGINATION: "pagination",
  PROPOSED_CHANGES_TAB: "pr_tab",
  TAB: "tab",
  TASK_ID: "task_id",
};
