import fs from "node:fs";
import path from "node:path";

import type { Plugin, ResolvedConfig } from "vite";

const VIRTUAL_MODULE_ID = "virtual:infrahub-plugins";
const RESOLVED_VIRTUAL_MODULE_ID = `\0${VIRTUAL_MODULE_ID}`;
const CONFIG_FILE_NAME = "infrahub-plugins.config";

interface PluginConfigEntry {
  package: string;
  overrides?: Record<string, unknown>;
  enabled?: boolean;
}

interface PluginsConfigFile {
  plugins: PluginConfigEntry[];
}

/**
 * Vite plugin that discovers and bundles Infrahub UI plugins.
 *
 * This plugin:
 * 1. Reads the infrahub-plugins.config.ts file
 * 2. Discovers all configured plugins
 * 3. Generates a virtual module that exports the plugin registry
 *
 * Usage in infrahub-plugins.config.ts:
 * ```ts
 * import type { PluginsConfig } from "@/entities/plugins/types";
 *
 * const config: PluginsConfig = {
 *   plugins: [
 *     { package: "@infrahub/plugin-device-metrics" },
 *     { package: "./src/plugins/custom-panel", overrides: { priority: 10 } },
 *   ],
 * };
 *
 * export default config;
 * ```
 */
export function infrahubPlugins(): Plugin {
  let config: ResolvedConfig;
  let pluginsConfig: PluginsConfigFile | null = null;

  return {
    name: "vite-plugin-infrahub-plugins",

    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
      return null;
    },

    async load(id) {
      if (id !== RESOLVED_VIRTUAL_MODULE_ID) {
        return null;
      }

      // Try to load the plugins config file
      pluginsConfig = await loadPluginsConfig(config.root);

      if (!pluginsConfig || pluginsConfig.plugins.length === 0) {
        // Return empty registry if no plugins configured
        return generateEmptyModule();
      }

      // Generate the virtual module with dynamic imports
      // Pass the root path so relative imports can be resolved
      return generatePluginModule(pluginsConfig.plugins, config.root);
    },

    configureServer(server) {
      // Watch the config file for changes in dev mode
      const configPath = findConfigFile(config.root);
      if (configPath) {
        server.watcher.add(configPath);
        server.watcher.on("change", (changedPath) => {
          if (changedPath === configPath) {
            // Invalidate the virtual module to reload plugins
            const module = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
            if (module) {
              server.moduleGraph.invalidateModule(module);
              server.ws.send({ type: "full-reload" });
            }
          }
        });
      }
    },
  };
}

function findConfigFile(root: string): string | null {
  const extensions = [".ts", ".js", ".mjs"];
  for (const ext of extensions) {
    const configPath = path.join(root, `${CONFIG_FILE_NAME}${ext}`);
    if (fs.existsSync(configPath)) {
      return configPath;
    }
  }
  return null;
}

async function loadPluginsConfig(root: string): Promise<PluginsConfigFile | null> {
  const configPath = findConfigFile(root);
  if (!configPath) {
    return null;
  }

  try {
    // For TypeScript/ESM configs, we'll rely on Vite's transform
    // The actual loading happens through the generated module
    let configContent = fs.readFileSync(configPath, "utf-8");

    // Strip comments before parsing to avoid matching example code in JSDoc/comments
    // Remove block comments (/* ... */ and /** ... */)
    configContent = configContent.replace(/\/\*[\s\S]*?\*\//g, "");
    // Remove single-line comments (// ...)
    configContent = configContent.replace(/\/\/.*$/gm, "");

    // Simple parsing to extract plugin packages
    // This is a basic approach - in production you might want to use a proper TS parser
    const pluginMatches = configContent.matchAll(/package:\s*["']([^"']+)["']/g);
    const plugins: PluginConfigEntry[] = [];

    for (const match of pluginMatches) {
      plugins.push({ package: match[1] ?? "", enabled: true });
    }

    // Check for enabled: false patterns
    const disabledMatches = configContent.matchAll(
      /package:\s*["']([^"']+)["'][^}]*enabled:\s*false/g
    );
    const disabledPackages = new Set<string>();
    for (const match of disabledMatches) {
      disabledPackages.add(match[1] ?? "");
    }

    return {
      plugins: plugins
        .filter((p) => !disabledPackages.has(p.package))
        .filter((p) => p.package.length > 0),
    };
  } catch {
    console.warn(`[infrahub-plugins] Failed to load config from ${configPath}`);
    return null;
  }
}

function generateEmptyModule(): string {
  return `
// Auto-generated by vite-plugin-infrahub-plugins
// No plugins configured

export const plugins = [];
export default { plugins };
`;
}

function resolveImportPath(packagePath: string, root: string): string {
  if (packagePath.startsWith("./src/") || packagePath.startsWith("src/")) {
    // Convert src/ paths to use the @/ alias (configured in tsconfig/vite)
    // ./src/plugins/foo -> @/plugins/foo
    // src/plugins/foo -> @/plugins/foo
    return packagePath.replace(/^(\.\/)?src\//, "@/");
  } else if (packagePath.startsWith("./") || packagePath.startsWith("../")) {
    // Other relative paths - resolve to absolute and use /@fs/ prefix for Vite
    const absolutePath = path.resolve(root, packagePath);
    // Vite uses /@fs/ prefix to serve files from the file system
    return `/@fs${absolutePath.split(path.sep).join("/")}`;
  } else if (packagePath.startsWith("/")) {
    // Absolute paths - use /@fs/ prefix for Vite
    return `/@fs${packagePath}`;
  } else {
    // npm package - use as-is
    return packagePath;
  }
}

function generatePluginModule(plugins: PluginConfigEntry[], root: string): string {
  const imports: string[] = [];
  const registrations: string[] = [];

  plugins.forEach((plugin, index) => {
    const varName = `plugin${index}`;
    const importPath = resolveImportPath(plugin.package, root);

    imports.push(`import * as ${varName} from "${importPath}";`);

    const overrides = plugin.overrides ? JSON.stringify(plugin.overrides) : "{}";

    // Support both single plugin (manifest + default) and multi-plugin (plugins array) exports
    // At runtime, we check if the module exports a 'plugins' array
    registrations.push(`
  // Check if package exports multiple plugins via 'plugins' array
  ...(${varName}.plugins
    ? ${varName}.plugins.map(p => ({ manifest: { ...p.manifest, ...${overrides} }, component: p.component }))
    : [{ manifest: { ...${varName}.manifest, ...${overrides} }, component: ${varName}.default }]
  )`);
  });

  return `
// Auto-generated by vite-plugin-infrahub-plugins
// This module is regenerated when infrahub-plugins.config.ts changes

${imports.join("\n")}

export const plugins = [${registrations.join(",\n")}];
export default { plugins };
`;
}

export default infrahubPlugins;
