# Generated by "invoke backend.generate", do not edit directly

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols_base import CoreNode

if TYPE_CHECKING:
    from infrahub_sdk.node import RelationshipManager
    from infrahub_sdk.protocols_base import (
        IntegerOptional,
        String,
        StringOptional,
    )

# pylint: disable=too-many-ancestors

# ---------------------------------------------
# ASYNC
# ---------------------------------------------


class TestingPerson(CoreNode):
    name: String
    description: StringOptional
    height: IntegerOptional
    age: IntegerOptional
    cars: RelationshipManager


class TestingCar(CoreNode):
    name: String
    description: StringOptional
    color: StringOptional
