# Generated by "invoke backend.generate", do not edit directly

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from infrahub.core.attribute import (
        URL,
        Boolean,
        Dropdown,
        HashedPassword,
        Integer,
        IPHost,
        IPNetwork,
        JSONAttribute,
        ListAttribute,
        String,
    )
    from infrahub.core.relationship import RelationshipManager


class CoreNode(Protocol):
    pass


class LineageOwner(Protocol):
    pass


class CoreProfile(Protocol):
    profile_name: String
    profile_priority: Integer


class LineageSource(Protocol):
    pass


class CoreComment(Protocol):
    text: String
    created_at: String
    created_by: RelationshipManager


class CoreThread(Protocol):
    label: String
    resolved: Boolean
    created_at: String
    change: RelationshipManager
    comments: RelationshipManager
    created_by: RelationshipManager


class CoreGroup(Protocol):
    name: String
    label: String
    description: String
    members: RelationshipManager
    subscribers: RelationshipManager


class CoreValidator(Protocol):
    label: String
    state: String
    conclusion: String
    completed_at: String
    started_at: String
    proposed_change: RelationshipManager
    checks: RelationshipManager


class CoreCheck(Protocol):
    name: String
    label: String
    origin: String
    kind: String
    message: String
    conclusion: String
    severity: String
    created_at: String
    validator: RelationshipManager


class CoreTransformation(Protocol):
    name: String
    label: String
    description: String
    timeout: Integer
    query: RelationshipManager
    repository: RelationshipManager
    tags: RelationshipManager


class CoreArtifactTarget(Protocol):
    artifacts: RelationshipManager


class CoreTaskTarget(Protocol):
    pass


class CoreWebhook(Protocol):
    name: String
    description: String
    url: URL
    validate_certificates: Boolean


class CoreGenericRepository(Protocol):
    name: String
    description: String
    location: String
    username: String
    password: String
    tags: RelationshipManager
    transformations: RelationshipManager
    queries: RelationshipManager
    checks: RelationshipManager
    generators: RelationshipManager


class BuiltinIPNamespace(Protocol):
    name: String
    description: String
    ip_prefixes: RelationshipManager
    ip_addresses: RelationshipManager


class BuiltinIPPrefix(Protocol):
    prefix: IPNetwork
    description: String
    member_type: Dropdown
    is_pool: Boolean
    is_top_level: Boolean
    utilization: Integer
    netmask: String
    hostmask: String
    network_address: String
    broadcast_address: String
    ip_namespace: RelationshipManager
    ip_addresses: RelationshipManager


class BuiltinIPAddress(Protocol):
    address: IPHost
    description: String
    ip_namespace: RelationshipManager
    ip_prefix: RelationshipManager


class CoreResourcePool(Protocol):
    name: String
    description: String


class CoreStandardGroup(CoreGroup):
    pass


class CoreGeneratorGroup(CoreGroup):
    pass


class CoreGraphQLQueryGroup(CoreGroup):
    parameters: JSONAttribute
    query: RelationshipManager


class BuiltinTag(Protocol):
    name: String
    description: String


class CoreAccount(LineageOwner, LineageSource):
    name: String
    password: HashedPassword
    label: String
    description: String
    type: String
    role: String
    tokens: RelationshipManager


class InternalAccountToken(Protocol):
    name: String
    token: String
    expiration: String
    account: RelationshipManager


class InternalRefreshToken(Protocol):
    expiration: String
    account: RelationshipManager


class CoreProposedChange(CoreTaskTarget):
    name: String
    description: String
    source_branch: String
    destination_branch: String
    state: String
    approved_by: RelationshipManager
    reviewers: RelationshipManager
    created_by: RelationshipManager
    comments: RelationshipManager
    threads: RelationshipManager
    validations: RelationshipManager


class CoreChangeThread(CoreThread):
    pass


class CoreFileThread(CoreThread):
    file: String
    commit: String
    line_number: Integer
    repository: RelationshipManager


class CoreArtifactThread(CoreThread):
    artifact_id: String
    storage_id: String
    line_number: Integer


class CoreObjectThread(CoreThread):
    object_path: String


class CoreChangeComment(CoreComment):
    change: RelationshipManager


class CoreThreadComment(CoreComment):
    thread: RelationshipManager


class CoreRepository(LineageOwner, LineageSource, CoreGenericRepository, CoreTaskTarget):
    default_branch: String
    commit: String


class CoreReadOnlyRepository(LineageOwner, LineageSource, CoreGenericRepository, CoreTaskTarget):
    ref: String
    commit: String


class CoreTransformJinja2(CoreTransformation):
    template_path: String


class CoreDataCheck(CoreCheck):
    conflicts: JSONAttribute
    keep_branch: String


class CoreStandardCheck(CoreCheck):
    pass


class CoreSchemaCheck(CoreCheck):
    conflicts: JSONAttribute


class CoreFileCheck(CoreCheck):
    files: ListAttribute
    commit: String


class CoreArtifactCheck(CoreCheck):
    changed: Boolean
    checksum: String
    artifact_id: String
    storage_id: String
    line_number: Integer


class CoreGeneratorCheck(CoreCheck):
    instance: String


class CoreDataValidator(CoreValidator):
    pass


class CoreRepositoryValidator(CoreValidator):
    repository: RelationshipManager


class CoreUserValidator(CoreValidator):
    check_definition: RelationshipManager
    repository: RelationshipManager


class CoreSchemaValidator(CoreValidator):
    pass


class CoreArtifactValidator(CoreValidator):
    definition: RelationshipManager


class CoreGeneratorValidator(CoreValidator):
    definition: RelationshipManager


class CoreCheckDefinition(CoreTaskTarget):
    name: String
    description: String
    file_path: String
    class_name: String
    timeout: Integer
    parameters: JSONAttribute
    repository: RelationshipManager
    query: RelationshipManager
    targets: RelationshipManager
    tags: RelationshipManager


class CoreTransformPython(CoreTransformation):
    file_path: String
    class_name: String


class CoreGraphQLQuery(Protocol):
    name: String
    description: String
    query: String
    variables: JSONAttribute
    operations: ListAttribute
    models: ListAttribute
    depth: Integer
    height: Integer
    repository: RelationshipManager
    tags: RelationshipManager


class CoreArtifact(CoreTaskTarget):
    name: String
    status: String
    content_type: String
    checksum: String
    storage_id: String
    parameters: JSONAttribute
    object: RelationshipManager
    definition: RelationshipManager


class CoreArtifactDefinition(CoreTaskTarget):
    name: String
    artifact_name: String
    description: String
    parameters: JSONAttribute
    content_type: String
    targets: RelationshipManager
    transformation: RelationshipManager


class CoreGeneratorDefinition(CoreTaskTarget):
    name: String
    description: String
    parameters: JSONAttribute
    file_path: String
    class_name: String
    convert_query_response: Boolean
    query: RelationshipManager
    repository: RelationshipManager
    targets: RelationshipManager


class CoreGeneratorInstance(CoreTaskTarget):
    name: String
    status: String
    object: RelationshipManager
    definition: RelationshipManager


class CoreStandardWebhook(CoreWebhook, CoreTaskTarget):
    shared_key: String


class CoreCustomWebhook(CoreWebhook, CoreTaskTarget):
    transformation: RelationshipManager


class IpamNamespace(BuiltinIPNamespace):
    default: Boolean


class CoreIPPrefixPool(CoreResourcePool, LineageSource):
    default_prefix_length: Integer
    default_member_type: String
    default_prefix_type: String
    resources: RelationshipManager
    ip_namespace: RelationshipManager


class CoreIPAddressPool(CoreResourcePool, LineageSource):
    default_address_type: String
    default_prefix_length: Integer
    resources: RelationshipManager
    ip_namespace: RelationshipManager
