# Generated by "invoke backend.generate", do not edit directly

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub.core.protocols_base import CoreNode

if TYPE_CHECKING:
    from enum import Enum

    from infrahub.core.attribute import (
        URL,
        Boolean,
        BooleanOptional,
        DateTime,
        DateTimeOptional,
        Dropdown,
        HashedPassword,
        Integer,
        IntegerOptional,
        IPHost,
        IPNetwork,
        JSONAttribute,
        JSONAttributeOptional,
        ListAttributeOptional,
        String,
        StringOptional,
    )
    from infrahub.core.relationship import RelationshipManager


class BuiltinIPAddress(CoreNode):
    address: IPHost
    description: StringOptional
    ip_namespace: RelationshipManager[BuiltinIPNamespace]
    ip_prefix: RelationshipManager[BuiltinIPPrefix]


class BuiltinIPNamespace(CoreNode):
    name: String
    description: StringOptional
    ip_prefixes: RelationshipManager[BuiltinIPPrefix]
    ip_addresses: RelationshipManager[BuiltinIPAddress]


class BuiltinIPPrefix(CoreNode):
    prefix: IPNetwork
    description: StringOptional
    member_type: Dropdown
    is_pool: Boolean
    is_top_level: BooleanOptional
    utilization: IntegerOptional
    netmask: StringOptional
    hostmask: StringOptional
    network_address: StringOptional
    broadcast_address: StringOptional
    ip_namespace: RelationshipManager[BuiltinIPNamespace]
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    resource_pool: RelationshipManager[CoreIPAddressPool]
    parent: RelationshipManager[BuiltinIPPrefix]
    children: RelationshipManager[BuiltinIPPrefix]


class CoreAction(CoreNode):
    name: String
    description: StringOptional
    triggers: RelationshipManager[CoreTriggerRule]


class CoreArtifactTarget(CoreNode):
    artifacts: RelationshipManager[CoreArtifact]


class CoreBasePermission(CoreNode):
    description: StringOptional
    identifier: StringOptional
    roles: RelationshipManager[CoreAccountRole]


class CoreCheck(CoreNode):
    name: StringOptional
    label: StringOptional
    origin: String
    kind: String
    message: StringOptional
    conclusion: Enum
    severity: Enum
    created_at: DateTimeOptional
    validator: RelationshipManager[CoreValidator]


class CoreComment(CoreNode):
    text: String


class CoreCredential(CoreNode):
    name: String
    label: StringOptional
    description: StringOptional


class CoreFileObject(CoreNode):
    file_name: String
    checksum: String
    file_size: Integer
    file_type: String
    storage_id: String


class CoreGenericAccount(CoreNode):
    name: String
    password: HashedPassword
    label: StringOptional
    description: StringOptional
    account_type: Enum
    status: Dropdown
    tokens: RelationshipManager[InternalAccountToken]
    external_identities: RelationshipManager[InternalExternalIdentity]


class CoreGenericRepository(CoreNode):
    name: String
    description: StringOptional
    location: String
    internal_status: Dropdown
    operational_status: Dropdown
    sync_status: Dropdown
    credential: RelationshipManager[CoreCredential]
    tags: RelationshipManager[BuiltinTag]
    transformations: RelationshipManager[CoreTransformation]
    queries: RelationshipManager[CoreGraphQLQuery]
    checks: RelationshipManager[CoreCheckDefinition]
    generators: RelationshipManager[CoreGeneratorDefinition]
    groups_objects: RelationshipManager[CoreRepositoryGroup]


class CoreGroup(CoreNode):
    name: String
    label: StringOptional
    description: StringOptional
    group_type: Enum
    members: RelationshipManager[CoreNode]
    subscribers: RelationshipManager[CoreNode]
    parent: RelationshipManager[CoreGroup]
    children: RelationshipManager[CoreGroup]


class CoreIPPool(CoreNode):
    pass


class CoreKeyValue(CoreNode):
    name: String
    key: String
    description: StringOptional
    value: String


class CoreMenu(CoreNode):
    namespace: String
    name: String
    label: StringOptional
    kind: StringOptional
    path: StringOptional
    description: StringOptional
    icon: StringOptional
    protected: Boolean
    order_weight: Integer
    required_permissions: ListAttributeOptional
    section: Enum
    parent: RelationshipManager[CoreMenu]
    children: RelationshipManager[CoreMenu]


class CoreNodeTriggerMatch(CoreNode):
    trigger: RelationshipManager[CoreNodeTriggerRule]


class CoreObjectComponentTemplate(CoreNode):
    template_name: String


class CoreObjectTemplate(CoreNode):
    template_name: String


class CoreProfile(CoreNode):
    profile_name: String
    profile_priority: IntegerOptional


class CoreResourcePool(CoreNode):
    name: String
    description: StringOptional


class CoreTaskTarget(CoreNode):
    pass


class CoreThread(CoreNode):
    label: StringOptional
    resolved: Boolean
    change: RelationshipManager[CoreProposedChange]
    comments: RelationshipManager[CoreThreadComment]


class CoreTransformation(CoreNode):
    name: String
    label: StringOptional
    description: StringOptional
    timeout: Integer
    query: RelationshipManager[CoreGraphQLQuery]
    repository: RelationshipManager[CoreGenericRepository]
    tags: RelationshipManager[BuiltinTag]


class CoreTriggerRule(CoreNode):
    name: String
    description: StringOptional
    active: Boolean
    branch_scope: Dropdown
    action: RelationshipManager[CoreAction]


class CoreValidator(CoreNode):
    label: StringOptional
    state: Enum
    conclusion: Enum
    completed_at: DateTimeOptional
    started_at: DateTimeOptional
    proposed_change: RelationshipManager[CoreProposedChange]
    checks: RelationshipManager[CoreCheck]


class CoreWebhook(CoreNode):
    name: String
    event_type: Enum
    active: Boolean
    branch_scope: Dropdown
    node_kind: StringOptional
    description: StringOptional
    url: URL
    validate_certificates: BooleanOptional
    headers: RelationshipManager[CoreKeyValue]


class CoreWeightedPoolResource(CoreNode):
    allocation_weight: IntegerOptional


class LineageOwner(CoreNode):
    pass


class LineageSource(CoreNode):
    pass


class BuiltinTag(CoreNode):
    name: String
    description: StringOptional


class CoreAccount(LineageOwner, LineageSource, CoreGenericAccount):
    pass


class CoreAccountGroup(LineageOwner, LineageSource, CoreGroup):
    roles: RelationshipManager[CoreAccountRole]


class CoreAccountRole(CoreNode):
    name: String
    groups: RelationshipManager[CoreAccountGroup]
    permissions: RelationshipManager[CoreBasePermission]


class CoreArtifact(CoreTaskTarget):
    name: String
    status: Enum
    content_type: Enum
    checksum: StringOptional
    storage_id: StringOptional
    parameters: JSONAttributeOptional
    object: RelationshipManager[CoreArtifactTarget]
    definition: RelationshipManager[CoreArtifactDefinition]


class CoreArtifactCheck(CoreCheck):
    changed: BooleanOptional
    checksum: StringOptional
    artifact_id: StringOptional
    storage_id: StringOptional
    line_number: IntegerOptional


class CoreArtifactDefinition(CoreTaskTarget):
    name: String
    artifact_name: String
    description: StringOptional
    parameters: JSONAttribute
    content_type: Enum
    targets: RelationshipManager[CoreGroup]
    transformation: RelationshipManager[CoreTransformation]


class CoreArtifactThread(CoreThread):
    artifact_id: StringOptional
    storage_id: StringOptional
    line_number: IntegerOptional


class CoreArtifactValidator(CoreValidator):
    definition: RelationshipManager[CoreArtifactDefinition]


class CoreChangeComment(CoreComment):
    change: RelationshipManager[CoreProposedChange]


class CoreChangeThread(CoreThread):
    pass


class CoreCheckDefinition(CoreTaskTarget):
    name: String
    description: StringOptional
    file_path: String
    class_name: String
    timeout: Integer
    parameters: JSONAttributeOptional
    repository: RelationshipManager[CoreGenericRepository]
    query: RelationshipManager[CoreGraphQLQuery]
    targets: RelationshipManager[CoreGroup]
    tags: RelationshipManager[BuiltinTag]


class CoreCustomWebhook(CoreWebhook, CoreTaskTarget):
    shared_key: StringOptional
    transformation: RelationshipManager[CoreTransformPython]


class CoreDataCheck(CoreCheck):
    conflicts: JSONAttribute
    keep_branch: Enum
    enriched_conflict_id: StringOptional


class CoreDataValidator(CoreValidator):
    pass


class CoreEnvKeyValue(CoreKeyValue):
    pass


class CoreFileCheck(CoreCheck):
    files: ListAttributeOptional
    commit: StringOptional


class CoreFileThread(CoreThread):
    file: StringOptional
    commit: StringOptional
    line_number: IntegerOptional
    repository: RelationshipManager[CoreRepository]


class CoreGeneratorAction(CoreAction):
    generator: RelationshipManager[CoreGeneratorDefinition]


class CoreGeneratorAwareGroup(CoreGroup):
    pass


class CoreGeneratorCheck(CoreCheck):
    instance: String


class CoreGeneratorDefinition(CoreTaskTarget):
    name: String
    description: StringOptional
    parameters: JSONAttribute
    file_path: String
    class_name: String
    convert_query_response: BooleanOptional
    execute_in_proposed_change: BooleanOptional
    execute_after_merge: BooleanOptional
    query: RelationshipManager[CoreGraphQLQuery]
    repository: RelationshipManager[CoreGenericRepository]
    targets: RelationshipManager[CoreGroup]


class CoreGeneratorGroup(CoreGroup):
    pass


class CoreGeneratorInstance(CoreTaskTarget):
    name: String
    status: Enum
    object: RelationshipManager[CoreNode]
    definition: RelationshipManager[CoreGeneratorDefinition]


class CoreGeneratorValidator(CoreValidator):
    definition: RelationshipManager[CoreGeneratorDefinition]


class CoreGlobalPermission(CoreBasePermission):
    action: Dropdown
    decision: Enum


class CoreGraphQLQuery(CoreNode):
    name: String
    description: StringOptional
    query: String
    variables: JSONAttributeOptional
    operations: ListAttributeOptional
    models: ListAttributeOptional
    depth: IntegerOptional
    height: IntegerOptional
    repository: RelationshipManager[CoreGenericRepository]
    tags: RelationshipManager[BuiltinTag]


class CoreGraphQLQueryGroup(CoreGroup):
    parameters: JSONAttributeOptional
    query: RelationshipManager[CoreGraphQLQuery]


class CoreGroupAction(CoreAction):
    member_action: Dropdown
    group: RelationshipManager[CoreGroup]


class CoreGroupTriggerRule(CoreTriggerRule):
    member_update: Dropdown
    group: RelationshipManager[CoreGroup]


class CoreIPAddressPool(CoreResourcePool, LineageSource, CoreIPPool):
    default_address_type: String
    default_prefix_length: IntegerOptional
    resources: RelationshipManager[BuiltinIPPrefix]
    ip_namespace: RelationshipManager[BuiltinIPNamespace]


class CoreIPPrefixPool(CoreResourcePool, LineageSource, CoreIPPool):
    default_prefix_length: IntegerOptional
    default_member_type: Enum
    default_prefix_type: StringOptional
    resources: RelationshipManager[BuiltinIPPrefix]
    ip_namespace: RelationshipManager[BuiltinIPNamespace]


class CoreMenuItem(CoreMenu):
    pass


class CoreNodeTriggerAttributeMatch(CoreNodeTriggerMatch):
    attribute_name: String
    value: StringOptional
    value_previous: StringOptional
    value_match: Dropdown


class CoreNodeTriggerRelationshipMatch(CoreNodeTriggerMatch):
    relationship_name: String
    modification_type: Dropdown
    peer: StringOptional


class CoreNodeTriggerRule(CoreTriggerRule):
    node_kind: String
    mutation_action: Enum
    matches: RelationshipManager[CoreNodeTriggerMatch]


class CoreNumberPool(CoreResourcePool, LineageSource):
    node: String
    node_attribute: String
    start_range: Integer
    end_range: Integer
    pool_type: Enum


class CoreObjectPermission(CoreBasePermission):
    namespace: String
    name: String
    action: Enum
    decision: Enum


class CoreObjectThread(CoreThread):
    object_path: String


class CorePasswordCredential(CoreCredential):
    username: StringOptional
    password: StringOptional


class CoreProposedChange(CoreTaskTarget):
    name: String
    description: StringOptional
    source_branch: String
    destination_branch: String
    state: Enum
    is_draft: Boolean
    total_comments: IntegerOptional
    approved_by: RelationshipManager[CoreGenericAccount]
    rejected_by: RelationshipManager[CoreGenericAccount]
    reviewers: RelationshipManager[CoreGenericAccount]
    comments: RelationshipManager[CoreChangeComment]
    threads: RelationshipManager[CoreThread]
    validations: RelationshipManager[CoreValidator]


class CoreReadOnlyRepository(LineageOwner, LineageSource, CoreGenericRepository, CoreTaskTarget):
    ref: String
    commit: StringOptional


class CoreRepository(LineageOwner, LineageSource, CoreGenericRepository, CoreTaskTarget):
    default_branch: String
    commit: StringOptional


class CoreRepositoryGroup(CoreGroup):
    content: Dropdown
    repository: RelationshipManager[CoreGenericRepository]


class CoreRepositoryValidator(CoreValidator):
    repository: RelationshipManager[CoreGenericRepository]


class CoreSchemaCheck(CoreCheck):
    conflicts: JSONAttribute
    enriched_conflict_id: StringOptional


class CoreSchemaValidator(CoreValidator):
    pass


class CoreStandardCheck(CoreCheck):
    pass


class CoreStandardGroup(CoreGroup):
    pass


class CoreStandardWebhook(CoreWebhook, CoreTaskTarget):
    shared_key: String


class CoreStaticKeyValue(CoreKeyValue):
    pass


class CoreThreadComment(CoreComment):
    thread: RelationshipManager[CoreThread]


class CoreTransformJinja2(CoreTransformation):
    template_path: String


class CoreTransformPython(CoreTransformation):
    file_path: String
    class_name: String
    convert_query_response: BooleanOptional


class CoreUserValidator(CoreValidator):
    check_definition: RelationshipManager[CoreCheckDefinition]
    repository: RelationshipManager[CoreGenericRepository]


class InternalAccountToken(CoreNode):
    name: StringOptional
    token: String
    expiration: DateTimeOptional
    account: RelationshipManager[CoreGenericAccount]


class InternalExternalIdentity(CoreNode):
    sub: String
    provider_name: String
    protocol: String
    account: RelationshipManager[CoreGenericAccount]


class InternalIPPrefixAvailable(BuiltinIPPrefix):
    pass


class InternalIPRangeAvailable(BuiltinIPAddress):
    last_address: IPHost


class InternalRefreshToken(CoreNode):
    expiration: DateTime
    account: RelationshipManager[CoreGenericAccount]


class IpamNamespace(BuiltinIPNamespace):
    default: BooleanOptional
