query ComputedAttributeFetchTransform($transform_name: String) {
    CoreTransformPython(name__value: $transform_name) {
        edges {
            node {
                id
                file_path {
                    value
                }
                class_name {
                    value
                }
                timeout {
                    value
                }
                convert_query_response {
                    value
                }
                repository {
                    node {
                        id
                        __typename
                        name {
                            value
                        }
                    }
                }
                query {
                    node {
                        id
                        name {
                            value
                        }
                    }
                }
            }
        }
    }
}
