{
 "title": "Infrahub Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "datasource_loki", "label": "Loki", "query": "loki" },
   { "name": "app_name", "label": "Application", "query": { "query": "label_values(app_name)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "job_loki",
    "label": "Loki Job",
    "query": {}
   },
   { "name": "job_prometheus", "label": "Job Prometheus", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Overview [$app_name]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app_name" },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "infrahub_request_duration_seconds_sum{app_name=\"$app_name\"} / infrahub_request_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "2XX Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\", status_code=~\"2.+\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "4XX Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\", status_code=~\"4.+\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "5XX Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\", status_code=~\"5.+\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "# of Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method, path) (increase(infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}[$__rate_interval]) > 0 OR infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Details DB Query [$app_name]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "app_name",
   "collapsed": true,
   "panels": [
    {
     "title": "DB Query Write Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 2, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (query) (rate(infrahub_db_query_execution_seconds_sum{type=\"write\"}[$__rate_interval])) / sum by (query) (rate(infrahub_db_query_execution_seconds_count{type=\"write\"}[$__rate_interval]) > 0 OR infrahub_db_query_execution_seconds_count{type=\"write\"})",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "DB Query Read Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (query) (rate(infrahub_db_query_execution_seconds_sum{type=\"read\"}[$__rate_interval])) / sum by (query) (rate(infrahub_db_query_execution_seconds_count{type=\"read\"}[$__rate_interval]) > 0 OR infrahub_db_query_execution_seconds_count{type=\"read\"})",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details Requests [$app_name]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "app_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Percent of 2XX Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", status_code=~\"2.+\", path!=\"/metrics\"}) / sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"})",
       "legendFormat": "{{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "Percent of 4XX Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", status_code=~\"4.+\", path!=\"/metrics\"}) / sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}) or vector(0)",
       "legendFormat": "{{methode}} - {{path}}"
      }
     ]
    },
    {
     "title": "Percent of 5XX Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", status_code=~\"5.+\", path!=\"/metrics\"}) / sum by(path, method) (infrahub_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}) or vector(0)",
       "legendFormat": "{{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "PR 99 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(infrahub_request_duration_seconds_bucket{app_name=\"$app_name\", path!=\"/metrics\"}[$__rate_interval])) by(path, le))",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Request In Process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "targets": [
      {
       "expr": "infrahub_requests_in_progress{app_name=\"$app_name\", path!=\"/metrics\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Request Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(infrahub_requests_total{app_name=\"$app_name\"}[$__rate_interval])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs [$app_name]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "app_name" },
  {
   "title": "Logs Type Rate  (per Container and Level)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (container, level) (rate({container=~\".*(queue|database|server|git).*\", container!~\".*run.*\", container=~\"$container\"} | label_format container=`{{.container| replace \"infrahub-\" \"\"}}`| label_format level=`{{.level|lower}}` | level != \"\" [1m]))",
     "legendFormat": "{{ container }} - {{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "{container=~\".*(queue|database|server|git).*\", container!~\".*run.*\", container=~\"$container\"} | line_format \"{{__timestamp__ | date `2006-01-02 15:04:05.00` }}\\t{{.container| replace `infrahub-` ``}}\\t{{.level}}\\t{{.logger}}\\t{{.message}}\""
    }
   ]
  }
 ]
}