import type {
  AttributeSchema,
  GenericSchema,
  NodeSchema,
  ProfileSchema,
  RelationshipSchema,
  TemplateSchema,
} from "@/entities/schema/types";

export const generateNodeSchema = (
  overrides?: Partial<NodeSchema & { kind: string }>
): NodeSchema & { kind: string } => {
  return {
    id: "18262e04-2168-8370-3f45-c51733049c99",
    state: "present",
    name: "Tag",
    namespace: "Builtin",
    description: "Standard Tag object to attach to other objects to provide some context.",
    label: "Tag",
    branch: "aware",
    default_filter: "name__value",
    human_friendly_id: ["name__value"],
    display_labels: ["name__value"],
    include_in_menu: true,
    menu_placement: null,
    icon: "mdi:tag-multiple",
    order_by: ["name__value"],
    uniqueness_constraints: [["name__value"]],
    documentation: null,
    attributes: [
      {
        id: "18262e04-21f2-2762-3f4d-c515c0bc4f6c",
        state: "present",
        name: "name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Name",
        description: null,
        read_only: false,
        unique: true,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
        parameters: {
          state: "present",
          regex: null,
          min_length: null,
          max_length: null,
        },
      },
      {
        id: "18262e04-2276-99bd-3f45-c514f0b9917c",
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
        parameters: {
          state: "present",
          regex: null,
          min_length: null,
          max_length: null,
        },
      },
    ],
    relationships: [
      {
        id: "18262e04-236f-aad5-3f44-c51d19f95474",
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 4000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18262e04-23e8-2be3-3f40-c51614e2f9a8",
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 5000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18262e04-22f2-5a7f-3f49-c5125233994e",
        state: "present",
        name: "profiles",
        peer: "CoreProfile",
        kind: "Profile",
        label: "Profiles",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 3000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    inherit_from: [],
    generate_profile: true,
    generate_template: false,
    hierarchy: null,
    parent: null,
    children: null,
    kind: "BuiltinTag",
    hash: "b4169708f7c88ab351fdde0164591bd9",
    ...overrides,
  };
};

export const generateGenericSchema = (overrides?: Partial<GenericSchema>): GenericSchema => {
  return {
    id: "18262e0c-e58e-4ca4-3f41-c5185b7c4b5a",
    state: "present",
    name: "Interface",
    namespace: "Infra",
    description: "Generic Network Interface",
    label: "Interface",
    branch: "aware",
    default_filter: null,
    human_friendly_id: ["device__name__value", "name__value"],
    display_labels: ["name__value"],
    include_in_menu: true,
    menu_placement: null,
    icon: "mdi:ethernet",
    order_by: ["name__value"],
    uniqueness_constraints: [["device", "name__value"]],
    documentation: null,
    attributes: [
      {
        id: "18262e0c-e615-d315-3f49-c5164b705df4",
        state: "present",
        name: "name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Name",
        description: null,
        read_only: false,
        unique: false,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18262e0c-e696-c205-3f4e-c514d289fce4",
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18262e0c-e716-60da-3f40-c511e7f45973",
        state: "present",
        name: "speed",
        kind: "Number",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Speed",
        description: null,
        read_only: false,
        unique: false,
        optional: false,
        branch: "aware",
        order_weight: 3000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18262e0c-e79a-c99a-3f4a-c51ed0981745",
        state: "present",
        name: "mtu",
        kind: "Number",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "MTU",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 4000,
        default_value: 1500,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18262e0c-e848-9fb0-3f47-c5121b1979e2",
        state: "present",
        name: "enabled",
        kind: "Boolean",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Enabled",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 5000,
        default_value: true,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18262e0c-e8ea-45d0-3f46-c518da52f7cd",
        state: "present",
        name: "status",
        kind: "Dropdown",
        enum: null,
        computed_attribute: null,
        choices: [
          {
            id: null,
            state: "present",
            name: "provisioning",
            description: "In the process of being set up and configured",
            color: "#ffff7f",
            label: "Provisioning",
          },
          {
            id: null,
            state: "present",
            name: "maintenance",
            description: "Undergoing routine maintenance or repairs",
            color: "#ffd27f",
            label: "Maintenance",
          },
          {
            id: null,
            state: "present",
            name: "drained",
            description: "Temporarily taken out of service",
            color: "#bfbfbf",
            label: "Drained",
          },
          {
            id: null,
            state: "present",
            name: "active",
            description: "Fully operational and currently in service",
            color: "#7fbf7f",
            label: "Active",
          },
        ],
        regex: null,
        max_length: null,
        min_length: null,
        label: "Status",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 6000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18262e0c-e97c-3041-3f47-c511345dcdc2",
        state: "present",
        name: "role",
        kind: "Dropdown",
        enum: null,
        computed_attribute: null,
        choices: [
          {
            id: null,
            state: "present",
            name: "upstream",
            description: "Connect to Internet service provider",
            color: "#9090de",
            label: "Upstream",
          },
          {
            id: null,
            state: "present",
            name: "uplink",
            description: "Connect to higher device",
            color: "#ff6b6b",
            label: "Uplink",
          },
          {
            id: null,
            state: "present",
            name: "spare",
            description: "Reserve resources for future use",
            color: "#d3d3d3",
            label: "Spare",
          },
          {
            id: null,
            state: "present",
            name: "server",
            description: "Dedicated to interfaces connected to servers",
            color: "#98b2d1",
            label: "Server",
          },
          {
            id: null,
            state: "present",
            name: "peering",
            description: "Connect with other networks via IX",
            color: "#ffa07a",
            label: "Peering",
          },
          {
            id: null,
            state: "present",
            name: "peer",
            description: "Equal-status connections for direct interchange",
            color: "#faa446",
            label: "Peer",
          },
          {
            id: null,
            state: "present",
            name: "management",
            description: "Dedicated network for control and monitoring",
            color: "#ccc28a",
            label: "Management",
          },
          {
            id: null,
            state: "present",
            name: "loopback",
            description: "Internal interface",
            color: "#93e9be",
            label: "Loopback",
          },
          {
            id: null,
            state: "present",
            name: "leaf",
            description: "Connect to leaf device",
            color: "#e6e6fa",
            label: "Leaf",
          },
          {
            id: null,
            state: "present",
            name: "backbone",
            description: "Provide main data routes",
            color: "#6a5acd",
            label: "Backbone",
          },
        ],
        regex: null,
        max_length: null,
        min_length: null,
        label: "Role",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 7000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: "18262e0c-ea16-1311-3f42-c51c950a2d97",
        state: "present",
        name: "device",
        peer: "InfraDevice",
        kind: "Parent",
        label: "Device",
        description: null,
        identifier: "device__interface",
        cardinality: "one",
        min_count: 1,
        max_count: 1,
        order_weight: 1,
        optional: false,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18262e0c-eaaf-4a7e-3f42-c51d6f43f5f4",
        state: "present",
        name: "tags",
        peer: "BuiltinTag",
        kind: "Attribute",
        label: "Tags",
        description: null,
        identifier: "builtintag__infrainterface",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 9000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18262e0c-eb40-fb51-3f48-c518d22f9a5c",
        state: "present",
        name: "profiles",
        peer: "CoreProfile",
        kind: "Profile",
        label: "Profiles",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 10_000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18262e0c-ebe3-f549-3f4c-c51f812de7c6",
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 11_000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18262e0c-ec78-66b4-3f44-c51764fbe306",
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 12_000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    hierarchical: false,
    generate_profile: true,
    used_by: ["InfraInterfaceL2", "InfraInterfaceL3", "InfraLagInterfaceL2", "InfraLagInterfaceL3"],
    kind: "InfraInterface",
    hash: "46e4f878e399f34035224421ab419517",
    ...overrides,
  };
};

export const generateProfileSchema = (overrides?: Partial<ProfileSchema>): ProfileSchema => {
  return {
    id: null,
    state: "present",
    name: "BuiltinTag",
    namespace: "Profile",
    description: "Profile for BuiltinTag",
    label: "Profile Tag",
    branch: "aware",
    default_filter: "profile_name__value",
    human_friendly_id: ["profile_name__value"],
    display_labels: ["profile_name__value"],
    include_in_menu: false,
    menu_placement: null,
    icon: null,
    order_by: null,
    uniqueness_constraints: null,
    documentation: null,
    attributes: [
      {
        id: null,
        state: "present",
        name: "profile_name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: 32,
        min_length: 3,
        label: "Profile Name",
        description: null,
        read_only: false,
        unique: true,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "profile_priority",
        kind: "Number",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Profile Priority",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: 1000,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: null,
        state: "present",
        name: "related_nodes",
        peer: "BuiltinTag",
        kind: "Profile",
        label: "Related Nodes",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 4000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 5000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 6000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    inherit_from: ["LineageSource", "CoreProfile", "CoreNode"],
    kind: "ProfileBuiltinTag",
    hash: "b32d59e55c5088dd461882d7ab104160",
    ...overrides,
  };
};

export const generateTemplateSchema = (overrides?: Partial<TemplateSchema>): TemplateSchema => {
  return {
    id: null,
    state: "present",
    name: "BuiltinTag",
    namespace: "Template",
    description: "Object template for BuiltinTag",
    label: "Object template Tag",
    branch: "aware",
    default_filter: "template_name__value",
    human_friendly_id: ["template_name__value"],
    display_labels: ["template_name__value"],
    include_in_menu: true,
    menu_placement: null,
    icon: null,
    order_by: null,
    uniqueness_constraints: null,
    documentation: null,
    attributes: [
      {
        id: null,
        state: "present",
        name: "template_name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Template Name",
        description: null,
        read_only: false,
        unique: true,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: null,
        state: "present",
        name: "related_nodes",
        peer: "BuiltinTag",
        kind: "Template",
        label: "Related Nodes",
        description: null,
        identifier: "node__objecttemplate",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 3000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 4000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 5000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    inherit_from: ["LineageSource", "CoreObjectTemplate", "CoreNode"],
    kind: "TemplateBuiltinTag",
    hash: "786abdfef996bd6e6c4900005ce4c384",
    ...overrides,
  };
};

export const generateAttributeSchema = (overrides?: Partial<AttributeSchema>): AttributeSchema => {
  return {
    id: null,
    state: "present",
    name: "name",
    kind: "Text",
    label: "Name",
    description: "description",
    enum: null,
    computed_attribute: null,
    default_value: null,
    order_weight: 0,
    optional: true,
    unique: false,
    allow_override: "any",
    branch: "aware",
    inherited: false,
    read_only: false,
    deprecation: null,
    parameters: {
      id: null,
      state: "present",
    },
    ...overrides,
  };
};

export const generateRelationshipSchema = (
  overrides?: Partial<RelationshipSchema>
): RelationshipSchema => ({
  id: "test-id",
  state: "present",
  name: "test_relationship",
  peer: "TestRelationship",
  kind: "Attribute",
  label: "Relationship test",
  description: null,
  identifier: "test_relationship__testrelationship",
  cardinality: "many",
  min_count: 0,
  max_count: 0,
  order_weight: 9000,
  optional: true,
  branch: "aware",
  inherited: false,
  direction: "bidirectional",
  hierarchical: null,
  on_delete: "no-action",
  allow_override: "any",
  read_only: false,
  deprecation: null,
  ...overrides,
});
