import { IProfileSchema, iGenericSchema, iNodeSchema } from "@/entities/schema/stores/schema.atom";
import { AttributeSchema, RelationshipSchema } from "@/entities/schema/types";

export const generateNodeSchema = (
  overrides?: Partial<iNodeSchema>
): iNodeSchema & { kind: string } => {
  return {
    id: "18102d49-2480-33e9-3cbd-c51702dfa1e2",
    state: "present",
    name: "Tag",
    namespace: "Builtin",
    description: "Standard Tag object to attached to other objects to provide some context.",
    label: "Tag",
    branch: "aware",
    default_filter: "name__value",
    human_friendly_id: ["name__value"],
    display_labels: ["name__value"],
    include_in_menu: true,
    menu_placement: null,
    icon: "mdi:tag-multiple",
    order_by: ["name__value"],
    uniqueness_constraints: [["name__value"]],
    documentation: null,
    attributes: [
      {
        id: "18102d49-2528-9c9f-3cb7-c51b530bfb5f",
        state: "present",
        name: "name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Name",
        description: null,
        read_only: false,
        unique: true,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102d49-25b6-e556-3cbf-c51ebba50701",
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: "18102d49-2631-08cf-3cbf-c5178fdcf302",
        state: "present",
        name: "profiles",
        peer: "CoreProfile",
        kind: "Profile",
        label: "Profiles",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 3000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18102d49-26a9-2d8b-3cb5-c514cff99737",
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 4000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18102d49-272a-ae1d-3cb3-c51499c4b693",
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 5000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    inherit_from: [],
    generate_profile: true,
    hierarchy: null,
    parent: null,
    children: null,
    kind: "BuiltinTag",
    hash: "1d7949127b4d0b13f7df8169e34152aa",
    ...overrides,
  };
};

export const generateGenericSchema = (overrides?: Partial<iGenericSchema>): iGenericSchema => {
  return {
    id: "18102fa4-23c7-dbe0-3cb6-c515f0d8bc92",
    state: "present",
    name: "Interface",
    namespace: "Infra",
    description: "Generic Network Interface",
    label: "Interface",
    branch: "aware",
    default_filter: null,
    human_friendly_id: ["device__name__value", "name__value"],
    display_labels: ["name__value"],
    include_in_menu: true,
    menu_placement: null,
    icon: "mdi:ethernet",
    order_by: ["name__value"],
    uniqueness_constraints: [["device", "name__value"]],
    documentation: null,
    attributes: [
      {
        id: "18102fa4-2449-45ed-3cb6-c512216580db",
        state: "present",
        name: "name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Name",
        description: null,
        read_only: false,
        unique: false,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102fa4-24d2-f995-3cb5-c51c563be4e9",
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102fa4-2556-10ad-3cb7-c518561f9b46",
        state: "present",
        name: "speed",
        kind: "Number",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Speed",
        description: null,
        read_only: false,
        unique: false,
        optional: false,
        branch: "aware",
        order_weight: 3000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102fa4-25d8-cf3a-3cb8-c5107d79388c",
        state: "present",
        name: "mtu",
        kind: "Number",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "MTU",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 4000,
        default_value: 1500,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102fa4-2652-aa33-3cb4-c51533e459aa",
        state: "present",
        name: "enabled",
        kind: "Boolean",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Enabled",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 5000,
        default_value: true,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102fa4-26d9-2812-3cb5-c51c9353d48a",
        state: "present",
        name: "status",
        kind: "Dropdown",
        enum: null,
        computed_attribute: null,
        choices: [
          {
            id: null,
            state: "present",
            name: "provisioning",
            description: "In the process of being set up and configured",
            color: "#ffff7f",
            label: "Provisioning",
          },
          {
            id: null,
            state: "present",
            name: "maintenance",
            description: "Undergoing routine maintenance or repairs",
            color: "#ffd27f",
            label: "Maintenance",
          },
          {
            id: null,
            state: "present",
            name: "drained",
            description: "Temporarily taken out of service",
            color: "#bfbfbf",
            label: "Drained",
          },
          {
            id: null,
            state: "present",
            name: "active",
            description: "Fully operational and currently in service",
            color: "#7fbf7f",
            label: "Active",
          },
        ],
        regex: null,
        max_length: null,
        min_length: null,
        label: "Status",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 6000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: "18102fa4-2762-1c7b-3cb9-c5157efcdef5",
        state: "present",
        name: "role",
        kind: "Dropdown",
        enum: null,
        computed_attribute: null,
        choices: [
          {
            id: null,
            state: "present",
            name: "upstream",
            description: "Connect to Internet service provider",
            color: "#9090de",
            label: "Upstream",
          },
          {
            id: null,
            state: "present",
            name: "uplink",
            description: "Connect to higher device",
            color: "#ff6b6b",
            label: "Uplink",
          },
          {
            id: null,
            state: "present",
            name: "spare",
            description: "Reserve resources for future use",
            color: "#d3d3d3",
            label: "Spare",
          },
          {
            id: null,
            state: "present",
            name: "server",
            description: "Dedicated to interfaces connected to servers",
            color: "#98b2d1",
            label: "Server",
          },
          {
            id: null,
            state: "present",
            name: "peering",
            description: "Connect with other networks via IX",
            color: "#ffa07a",
            label: "Peering",
          },
          {
            id: null,
            state: "present",
            name: "peer",
            description: "Equal-status connections for direct interchange",
            color: "#faa446",
            label: "Peer",
          },
          {
            id: null,
            state: "present",
            name: "management",
            description: "Dedicated network for control and monitoring",
            color: "#ccc28a",
            label: "Management",
          },
          {
            id: null,
            state: "present",
            name: "loopback",
            description: "Internal interface",
            color: "#93e9be",
            label: "Loopback",
          },
          {
            id: null,
            state: "present",
            name: "leaf",
            description: "Connect to leaf device",
            color: "#e6e6fa",
            label: "Leaf",
          },
          {
            id: null,
            state: "present",
            name: "backbone",
            description: "Provide main data routes",
            color: "#6a5acd",
            label: "Backbone",
          },
        ],
        regex: null,
        max_length: null,
        min_length: null,
        label: "Role",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 7000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: "18102fa4-27e7-bcd5-3cb4-c51b6f10b79b",
        state: "present",
        name: "device",
        peer: "InfraDevice",
        kind: "Parent",
        label: "Device",
        description: null,
        identifier: "device__interface",
        cardinality: "one",
        min_count: 1,
        max_count: 1,
        order_weight: 1,
        optional: false,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18102fa4-2867-f879-3cb1-c51601070828",
        state: "present",
        name: "tags",
        peer: "BuiltinTag",
        kind: "Attribute",
        label: "Tags",
        description: null,
        identifier: "builtintag__infrainterface",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 9000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18102fa4-28dc-230d-3cb5-c515463abaee",
        state: "present",
        name: "profiles",
        peer: "CoreProfile",
        kind: "Profile",
        label: "Profiles",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 10000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18102fa4-2951-bc2b-3cb8-c5136d49ec8d",
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 11000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: "18102fa4-29d2-20fd-3cbb-c512236a96b9",
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 12000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    hierarchical: false,
    generate_profile: true,
    used_by: ["InfraInterfaceL2", "InfraInterfaceL3", "InfraLagInterfaceL2", "InfraLagInterfaceL3"],
    kind: "InfraInterface",
    hash: "0bcda5f40962693143c8f74347b58890",
    ...overrides,
  };
};

export const generateProfileSchema = (overrides?: Partial<IProfileSchema>): IProfileSchema => {
  return {
    id: null,
    state: "present",
    name: "BuiltinTag",
    namespace: "Profile",
    description: "Profile for BuiltinTag",
    label: "Profile Tag",
    branch: "aware",
    default_filter: "profile_name__value",
    human_friendly_id: ["profile_name__value"],
    display_labels: ["profile_name__value"],
    include_in_menu: false,
    menu_placement: null,
    icon: null,
    order_by: null,
    uniqueness_constraints: null,
    documentation: null,
    attributes: [
      {
        id: null,
        state: "present",
        name: "profile_name",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: 32,
        min_length: 3,
        label: "Profile Name",
        description: null,
        read_only: false,
        unique: true,
        optional: false,
        branch: "aware",
        order_weight: 1000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "profile_priority",
        kind: "Number",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Profile Priority",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: 1000,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "description",
        kind: "Text",
        enum: null,
        computed_attribute: null,
        choices: null,
        regex: null,
        max_length: null,
        min_length: null,
        label: "Description",
        description: null,
        read_only: false,
        unique: false,
        optional: true,
        branch: "aware",
        order_weight: 2000,
        default_value: null,
        inherited: false,
        allow_override: "any",
        deprecation: null,
      },
    ],
    relationships: [
      {
        id: null,
        state: "present",
        name: "related_nodes",
        peer: "BuiltinTag",
        kind: "Profile",
        label: "Related Nodes",
        description: null,
        identifier: "node__profile",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 4000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "member_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Member Of Groups",
        description: null,
        identifier: "group_member",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 5000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
      {
        id: null,
        state: "present",
        name: "subscriber_of_groups",
        peer: "CoreGroup",
        kind: "Group",
        label: "Subscriber Of Groups",
        description: null,
        identifier: "group_subscriber",
        cardinality: "many",
        min_count: 0,
        max_count: 0,
        order_weight: 6000,
        optional: true,
        branch: "aware",
        inherited: false,
        direction: "bidirectional",
        hierarchical: null,
        on_delete: "no-action",
        allow_override: "any",
        read_only: false,
        deprecation: null,
      },
    ],
    inherit_from: ["LineageSource", "CoreProfile", "CoreNode"],
    kind: "ProfileBuiltinTag",
    hash: "b32d59e55c5088dd461882d7ab104160",
    ...overrides,
  };
};

export const generateAttributeSchema = (overrides?: Partial<AttributeSchema>): AttributeSchema => {
  return {
    id: null,
    state: "present",
    name: "name",
    kind: "Text",
    label: "Name",
    description: "description",
    enum: null,
    computed_attribute: null,
    default_value: null,
    order_weight: 0,
    optional: true,
    unique: false,
    allow_override: "any",
    branch: "aware",
    inherited: false,
    read_only: false,
    deprecation: null,
    ...overrides,
  };
};

export const generateRelationshipSchema = (
  overrides: Partial<RelationshipSchema>
): RelationshipSchema => ({
  id: "test-id",
  state: "present",
  name: "test_relationship",
  peer: "TestRelationship",
  kind: "Attribute",
  label: "Relationship test",
  description: null,
  identifier: "test_relationship__testrelationship",
  cardinality: "many",
  min_count: 0,
  max_count: 0,
  order_weight: 9000,
  optional: true,
  branch: "aware",
  inherited: false,
  direction: "bidirectional",
  hierarchical: null,
  on_delete: "no-action",
  allow_override: "any",
  read_only: false,
  deprecation: null,
  ...overrides,
});
