{{- if .Values.cloud.enabled }}
{{- range $value := .Values.cloud.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}
type: {{ $value.type }}
data:
  {{- toYaml $value.data | nindent 2 }}
{{- end }}
{{- end }}
