---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'infrahub-server'
    dns_sd_configs:
      - names:
          - server
        type: A
        port: 8000

  - job_name: 'infrahub-worker'
    dns_sd_configs:
      - names:
          - task-worker
        type: A
        port: 8000
