/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/schema/": {
    /** Get Schema */
    get: operations["get_schema_schema__get"];
  };
  "/rfile/{rfile_id}": {
    /** Generate Rfile */
    get: operations["generate_rfile_rfile__rfile_id__get"];
  };
  "/query/{query_id}": {
    /** Graphql Query */
    get: operations["graphql_query_query__query_id__get"];
  };
  "/transform/{transform_url}": {
    /** Transform Python */
    get: operations["transform_python_transform__transform_url__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AttributeSchema */
    AttributeSchema: {
      /** Name */
      name: string;
      /** Kind */
      kind: string;
      /** Label */
      label?: string;
      /** Description */
      description?: string;
      /** Default Value */
      default_value?: Record<string, never>;
      /** Enum */
      enum?: (Record<string, never>)[];
      /** Regex */
      regex?: string;
      /** Max Length */
      max_length?: number;
      /** Min Length */
      min_length?: number;
      /**
       * Inherited
       * @default false
       */
      inherited?: boolean;
      /**
       * Unique
       * @default false
       */
      unique?: boolean;
      /**
       * Branch
       * @default true
       */
      branch?: boolean;
      /**
       * Optional
       * @default false
       */
      optional?: boolean;
    };
    /** FilterSchema */
    FilterSchema: {
      /** Name */
      name: string;
      kind: components["schemas"]["FilterSchemaKind"];
      /** Enum */
      enum?: (Record<string, never>)[];
      /** Object Kind */
      object_kind?: string;
      /** Description */
      description?: string;
    };
    /**
     * FilterSchemaKind
     * @description An enumeration.
     * @enum {string}
     */
    FilterSchemaKind: "String" | "Integer" | "Boolean" | "Object" | "MultiObject" | "Enum";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /** NodeSchema */
    NodeSchema: {
      /** Name */
      name: string;
      /** Kind */
      kind: string;
      /** Description */
      description?: string;
      /** Attributes */
      attributes?: (components["schemas"]["AttributeSchema"])[];
      /** Relationships */
      relationships?: (components["schemas"]["RelationshipSchema"])[];
      /** Label */
      label?: string;
      /** Inherit From */
      inherit_from?: (string)[];
      /** Groups */
      groups?: (string)[];
      /**
       * Branch
       * @default true
       */
      branch?: boolean;
      /** Default Filter */
      default_filter?: string;
      /** Display Label */
      display_label?: (string)[];
      /** Filters */
      filters?: (components["schemas"]["FilterSchema"])[];
    };
    /** RelationshipSchema */
    RelationshipSchema: {
      /** Name */
      name: string;
      /** Peer */
      peer: string;
      /**
       * Kind
       * @default Generic
       */
      kind?: string;
      /** Label */
      label?: string;
      /** Description */
      description?: string;
      /** Identifier */
      identifier?: string;
      /**
       * Inherited
       * @default false
       */
      inherited?: boolean;
      /**
       * Cardinality
       * @default many
       */
      cardinality?: string;
      /**
       * Branch
       * @default true
       */
      branch?: boolean;
      /**
       * Optional
       * @default true
       */
      optional?: boolean;
      /** Filters */
      filters?: (components["schemas"]["FilterSchema"])[];
    };
    /** SchemaAPI */
    SchemaAPI: {
      /** Nodes */
      nodes: (components["schemas"]["NodeSchema"])[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  get_schema_schema__get: {
    /** Get Schema */
    parameters: {
      query: {
        branch?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SchemaAPI"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_rfile_rfile__rfile_id__get: {
    /** Generate Rfile */
    parameters: {
      query: {
        branch?: string;
        at?: string;
        rebase?: boolean;
      };
      path: {
        rfile_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  graphql_query_query__query_id__get: {
    /** Graphql Query */
    parameters: {
      query: {
        branch?: string;
        at?: string;
        rebase?: boolean;
      };
      path: {
        query_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transform_python_transform__transform_url__get: {
    /** Transform Python */
    parameters: {
      query: {
        branch?: string;
        at?: string;
        rebase?: boolean;
      };
      path: {
        transform_url: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
