---
global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/minio
mode: distributed
statefulset:
  replicaCount: 3
  drivesPerNode: 2
auth:
  rootUser: admin
  rootPassword: password
provisioning:
  enabled: true
  buckets:
    - name: infrahub-data
podAntiAffinityPreset: hard
volumePermissions:
  image:
    repository: bitnamilegacy/os-shell
