---
replicaCount: 3
podLabels:
  infrahub/service: message-queue
image:
  repository: bitnamilegacy/rabbitmq
auth:
  username: infrahub
  password: infrahub
metrics:
  enabled: true
startupProbe:
  enabled: true
podAntiAffinityPreset: hard
