---
replicaCount: 3
podLabels:
  infrahub/service: message-queue
image:
  repository: bitnamilegacy/rabbitmq
  tag: 4.1.3-debian-12-r1
auth:
  username: infrahub
  password: infrahub
metrics:
  enabled: true
startupProbe:
  enabled: true
podAntiAffinityPreset: hard
