---
nameOverride: cache
image:
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0
architecture: replication
auth:
  enabled: false
master:
  podLabels:
    infrahub/service: cache
  podAntiAffinityPreset: hard
  persistence:
    enabled: true
  service:
    ports:
      redis: 6379
replicas:
  replicaCount: 3
  podAntiAffinityPreset: hard
sentinel:
  enabled: true
  image:
    repository: bitnamilegacy/redis-sentinel
    tag: 8.2.1-debian-12-r0
