---
nameOverride: redis
image:
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0
architecture: replication
auth:
  enabled: false
replica:
  replicaCount: 3
  podAntiAffinityPreset: hard
  podLabels:
    infrahub/service: cache
sentinel:
  enabled: true
  image:
    repository: bitnamilegacy/redis-sentinel
    tag: 8.2.1-debian-12-r0
