---
nameOverride: cache
image:
  repository: bitnamilegacy/redis
architecture: replication
auth:
  enabled: false
master:
  podAntiAffinityPreset: hard
  persistence:
    enabled: true
  service:
    ports:
      redis: 6379
replicas:
  replicaCount: 3
  podAntiAffinityPreset: hard
sentinel:
  enabled: true
  image:
    repository: bitnamilegacy/redis-sentinel
