infrastructure_models = {
    "nodes": [
        {
            "name": "device",
            "kind": "Device",
            "default_filter": "name__value",
            "display_label": ["label__value"],
            "branch": True,
            "attributes": [
                {"name": "name", "kind": "String", "unique": True},
                {"name": "description", "kind": "String", "optional": True},
                {"name": "type", "kind": "String"},
            ],
            "relationships": [
                {"name": "site", "peer": "Location", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "status", "peer": "Status", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "role", "peer": "Role", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {
                    "name": "interfaces",
                    "peer": "Interface",
                    "optional": True,
                    "cardinality": "many",
                    "kind": "Component",
                },
                {
                    "name": "asn",
                    "peer": "AutonomousSystem",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {"name": "tags", "peer": "Tag", "optional": True, "cardinality": "many", "kind": "Attribute"},
            ],
        },
        {
            "name": "interface",
            "kind": "Interface",
            "display_label": ["label__value"],
            "branch": True,
            "attributes": [
                {"name": "name", "kind": "String"},
                {"name": "description", "kind": "String", "optional": True},
                {"name": "speed", "kind": "Integer"},
                {"name": "enabled", "kind": "Boolean", "default_value": True},
            ],
            "relationships": [
                {"name": "status", "peer": "Status", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "role", "peer": "Role", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "device", "peer": "Device", "optional": False, "cardinality": "one", "kind": "Parent"},
                {"name": "tags", "peer": "Tag", "optional": True, "cardinality": "many", "kind": "Attribute"},
                {
                    "name": "ip_addresses",
                    "peer": "IPAddress",
                    "optional": True,
                    "cardinality": "many",
                    "kind": "Component",
                },
                {"name": "connected_circuit", "peer": "CircuitEndpoint", "optional": True, "cardinality": "one"},
                {"name": "connected_interface", "peer": "Interface", "optional": True, "cardinality": "one"},
            ],
        },
        {
            "name": "ipaddress",
            "kind": "IPAddress",
            "default_filter": "address__value",
            "display_label": ["label__value"],
            "branch": True,
            "attributes": [
                {"name": "address", "kind": "String"},
                {"name": "description", "kind": "String", "optional": True},
            ],
            "relationships": [
                {"name": "interface", "peer": "Interface", "optional": True, "cardinality": "one", "kind": "Parent"},
            ],
        },
        {
            "name": "circuit",
            "kind": "Circuit",
            "default_filter": "circuit_id__value",
            "display_label": ["circuit_id__value"],
            "branch": True,
            "attributes": [
                {"name": "circuit_id", "kind": "String", "unique": True},
                {"name": "description", "kind": "String", "optional": True},
                {"name": "vendor_id", "kind": "String", "optional": True},
            ],
            "relationships": [
                {"name": "status", "peer": "Status", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "role", "peer": "Role", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {
                    "name": "provider",
                    "peer": "Organization",
                    "optional": False,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {
                    "name": "endpoints",
                    "peer": "CircuitEndpoint",
                    "optional": True,
                    "cardinality": "many",
                    "kind": "Component",
                },
            ],
        },
        {
            "name": "circuit_endpoint",
            "kind": "CircuitEndpoint",
            "branch": True,
            "attributes": [
                {"name": "description", "kind": "String", "optional": True},
            ],
            "relationships": [
                {"name": "site", "peer": "Location", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "circuit", "peer": "Circuit", "optional": False, "cardinality": "one", "kind": "Parent"},
                {"name": "connected_interface", "peer": "Interface", "optional": True, "cardinality": "one"},
            ],
        },
        {
            "name": "autonomous_system",
            "kind": "AutonomousSystem",
            "default_filter": "name__value",
            "display_label": ["name__value", "asn__value"],
            "branch": True,
            "attributes": [
                {"name": "name", "kind": "String", "unique": True},
                {"name": "asn", "kind": "Integer", "unique": True},
                {"name": "description", "kind": "String", "optional": True},
            ],
            "relationships": [
                {
                    "name": "organization",
                    "peer": "Organization",
                    "optional": False,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
            ],
        },
        {
            "name": "bgp_peer_group",
            "kind": "BGPPeerGroup",
            "default_filter": "name__value",
            "display_label": ["label__value"],
            "branch": True,
            "attributes": [
                {"name": "name", "kind": "String"},
                {"name": "description", "kind": "String", "optional": True},
                {"name": "import_policies", "kind": "String", "optional": True},
                {"name": "export_policies", "kind": "String", "optional": True},
            ],
            "relationships": [
                {
                    "name": "local_as",
                    "identifier": "bgppeergroup__local_as",
                    "peer": "AutonomousSystem",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {
                    "name": "remote_as",
                    "identifier": "bgppeergroup__remote_as",
                    "peer": "AutonomousSystem",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
            ],
        },
        {
            "name": "bgp_session",
            "kind": "BGPSession",
            "branch": True,
            "attributes": [
                {"name": "type", "kind": "String", "enum": ["EXTERNAL", "INTERNAL"]},
                {"name": "description", "kind": "String", "optional": True},
                {"name": "import_policies", "kind": "String", "optional": True},
                {"name": "export_policies", "kind": "String", "optional": True},
            ],
            "relationships": [
                {"name": "status", "peer": "Status", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {"name": "role", "peer": "Role", "optional": False, "cardinality": "one", "kind": "Attribute"},
                {
                    "name": "local_as",
                    "identifier": "bgpsession__local_as",
                    "peer": "AutonomousSystem",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {
                    "name": "remote_as",
                    "identifier": "bgpsession__remote_as",
                    "peer": "AutonomousSystem",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {
                    "name": "local_ip",
                    "identifier": "bgpsession__local_ip",
                    "peer": "IPAddress",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {
                    "name": "remote_ip",
                    "identifier": "bgpsession__remote_ip",
                    "peer": "IPAddress",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {"name": "device", "peer": "Device", "optional": True, "cardinality": "one"},
                {
                    "name": "peer_group",
                    "peer": "BGPPeerGroup",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
                {
                    "name": "peer_session",
                    "peer": "BGPSession",
                    "optional": True,
                    "cardinality": "one",
                    "kind": "Attribute",
                },
            ],
        },
    ]
}
