export const TASK_STATE_COMPLETED = "COMPLETED";
export const TASK_STATE_RUNNING = "RUNNING";
export const TASK_STATE_PENDING = "PENDING";
export const TASK_STATE_FAILED = "FAILED";

export const TASK_STATE_SCHEDULED = "SCHEDULED";
export const TASK_STATE_CANCELING = "CANCELLING";
export const TASK_STATE_CANCELLED = "CANCELLED";
export const TASK_STATE_CRASHED = "CRASHED";
export const TASK_STATE_PAUSED = "PAUSED";

export const TASK_STATES = [
  TASK_STATE_SCHEDULED,
  TASK_STATE_PENDING,
  TASK_STATE_RUNNING,
  TASK_STATE_COMPLETED,
  TASK_STATE_FAILED,
  TASK_STATE_CANCELLED,
  TASK_STATE_CRASHED,
  TASK_STATE_PAUSED,
  TASK_STATE_CANCELING,
];

export const TASK_ONGOING_STATES = [
  TASK_STATE_SCHEDULED,
  TASK_STATE_PENDING,
  TASK_STATE_RUNNING,
  TASK_STATE_CANCELING,
];

export const MORE_TASKS_STATES = [
  TASK_STATE_SCHEDULED,
  TASK_STATE_CANCELING,
  TASK_STATE_CANCELLED,
  TASK_STATE_CRASHED,
  TASK_STATE_PAUSED,
];

export const BRANCH_VALIDATE_WORKFLOW = "branch-validate";
export const BRANCH_REBASE_WORKFLOW = "branch-rebase";
export const BRANCH_MERGE_WORKFLOW = "merge-branch-mutation";
export const PROPOSED_CHANGE_MERGE_WORKFLOW = "proposed-change-merge";
