export const REPOSITORY_COMMITS_PAGE_SIZE = 20;
export const REPOSITORY_COMMITS_STALE_TIME_MS = 60_000;
export const REPOSITORY_COMMITS_RETRY_DELAY_MS = 10_000;
export const REPOSITORY_COMMITS_MAX_RETRIES = 30;
