from infrahub.computed_attribute.triggers import (
    TRIGGER_COMPUTED_ATTRIBUTE_ALL_SCHEMA,
    TRIGGER_COMPUTED_ATTRIBUTE_PYTHON_CLEAN_BRANCH,
    TRIGGER_COMPUTED_ATTRIBUTE_PYTHON_SETUP_BRANCH,
    TRIGGER_COMPUTED_ATTRIBUTE_PYTHON_SETUP_COMMIT,
)
from infrahub.webhook.triggers import TRIGGER_WEBHOOK_SETUP_UPDATE

triggers = [
    TRIGGER_COMPUTED_ATTRIBUTE_ALL_SCHEMA,
    TRIGGER_COMPUTED_ATTRIBUTE_PYTHON_CLEAN_BRANCH,
    TRIGGER_COMPUTED_ATTRIBUTE_PYTHON_SETUP_BRANCH,
    TRIGGER_COMPUTED_ATTRIBUTE_PYTHON_SETUP_COMMIT,
    TRIGGER_WEBHOOK_SETUP_UPDATE,
]
