---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'infrahub-server'
    dns_sd_configs:
      - names:
          - server
        type: A
        port: 8000

  - job_name: 'infrahub-worker'
    dns_sd_configs:
      - names:
          - task-worker
        type: A
        port: 8000

  - job_name: 'message-queue'
    static_configs:
      - targets: ['message-queue:15692']

  - job_name: 'database'
    static_configs:
      - targets: ['database:2004']
      # - targets: ['memgraph_exp:9115']

  - job_name: 'task-manager'
    static_configs:
      - targets: ['task-manager-exporter:8000']
    relabel_configs:
      - source_labels: [__meta_docker_container_label_namespace]
        target_label: namespace

  - job_name: 'logs'
    static_configs:
      - targets: ['loki:3100']
      - targets: ['promtail:9080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [container_label_namespace]
        target_label: namespace
      - source_labels: [container_label_pod]
        target_label: pod

  - job_name: 'task-worker'
    static_configs:
      - targets: ['prefect-server:4200']
    metrics_path: '/api/metrics'
