---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'infrahub'
    static_configs:
      - targets: ['server:8000']
      - targets: ['task-worker:8000']

  - job_name: 'message-queue'
    static_configs:
      - targets: ['message-queue:15692']

  - job_name: 'database'
    static_configs:
      - targets: ['database:2004']
      - targets: ['memgraph_exp:9115']

  - job_name: 'logs'
    static_configs:
      - targets: ['loki:3100']
      - targets: ['promtail:9080']
