from infrahub_sdk.generator import InfrahubGenerator

VLAN_POOL = "Customer vlan pool"
PREFIX_POOL = "Customer prefixes pool"
GATEWAY_POOL = "Management IP pool"


class DedicatedInternetAllocate(InfrahubGenerator):
    """Allocate the VLAN, the customer /29 prefix and the gateway address of a service."""

    async def generate(self, data: dict) -> None:
        service_data = data["ServiceDedicatedInternet"]["edges"][0]["node"]
        name: str = service_data["name"]["value"]

        # The pool allocates vlan_id at creation, so reuse the VLAN on re-runs instead of upserting it.
        vlan = await self.client.get(kind="IpamVLAN", name__value=f"vlan-{name}", raise_when_missing=False)
        if vlan is None:
            vlan_pool = await self.client.get(kind="CoreNumberPool", name__value=VLAN_POOL)
            vlan = await self.client.create(kind="IpamVLAN", name=f"vlan-{name}", vlan_id=vlan_pool)
        await vlan.save()

        # Pool allocations keyed on the service name return the same resource on every run.
        prefix_pool = await self.client.get(kind="CoreIPPrefixPool", name__value=PREFIX_POOL)
        prefix = await self.client.allocate_next_ip_prefix(prefix_pool, identifier=name)
        await prefix.save()

        gateway_pool = await self.client.get(kind="CoreIPAddressPool", name__value=GATEWAY_POOL)
        gateway = await self.client.allocate_next_ip_address(gateway_pool, identifier=name)
        await gateway.save()

        service = await self.client.get(kind="ServiceDedicatedInternet", id=service_data["id"])
        service.vlan = vlan
        service.prefix = prefix
        service.gateway_ip_address = gateway
        # The target is not generated by this run: keep it out of the tracking group so cleanup never deletes it.
        await service.save(update_group_context=False)
