---
name: from-netbox
source:
  name: netbox
  settings:
    url: "https://demo.netbox.dev"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "BuiltinTag",
  "BuiltinRole",
  "CoreStandardGroup",
  "CoreOrganization",
  "BuiltinLocation",
  "InfraRack",
  "TemplateDeviceType",
  "InfraProviderNetwork",
  "TemplateCircuitType",
  "InfraCircuit",
  "InfraRouteTarget",
  "InfraVRF",
  "InfraDevice",
  "InfraVLAN",
  "InfraPrefix",
  "InfraIPAddress"
]

schema_mapping:
  # Tags
  - name: BuiltinTag
    mapping: extras.tags
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  # Roles (DCIM, IPAM, Devices)
  - name: BuiltinRole
    mapping: dcim.device_roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: BuiltinRole
    mapping: dcim.rack_roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: BuiltinRole
    mapping: ipam.roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  # Tenancy (tenants, tenant groups)
  - name: CoreStandardGroup
    mapping: tenancy.tenant-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: CoreOrganization
    mapping: tenancy.tenants
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Tenant"
      - name: group
        mapping: group
        reference: CoreStandardGroup

  # Sites (Site Groups, Region, Sites, Location)
  - name: CoreStandardGroup
    mapping: dcim.site-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: BuiltinLocation
    mapping: dcim.regions
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: name
      - name: type
        static: "Region"
      - name: tags
        mapping: tags
        reference: BuiltinTag
  - name: BuiltinLocation
    mapping: dcim.sites
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: name
      - name: type
        static: "Site"
      - name: group
        mapping: group
        reference: CoreStandardGroup
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: tags
        mapping: tags
        reference: BuiltinTag
  - name: BuiltinLocation
    mapping: dcim.locations
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: name
      - name: type
        static: "Location"
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Racks
  - name: InfraRack
    mapping: dcim.racks
    identifiers: ["name", "location"]
    fields:
      - name: name
        mapping: name
      - name: location
        mapping: site.slug
      - name: height
        mapping: u_height
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: facility_id
        mapping: facility_id
      - name: role
        mapping: role.name
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Device (manufacturer, device types, devices)
  - name: CoreOrganization
    mapping: dcim.manufacturers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Manufacturer"
  - name: TemplateDeviceType
    mapping: dcim.device-types
    identifiers: ["name", "manufacturer"]
    fields:
      - name: name
        mapping: model
      - name: part_number
        mapping: part_number
      - name: tags
        mapping: tags
        reference: BuiltinTag
      - name: manufacturer
        mapping: manufacturer
        reference: CoreOrganization
  # -> if the device in netbox have no name, no serial and no asset, which identifiers could we use ?
  - name: InfraDevice
    identifiers: ["name", "serial_number", "asset_tag", "model", "site"]
    mapping: dcim.devices
    fields:
      - name: name
        mapping: name
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: description
        mapping: description
      - name: model
        mapping: device_type
        reference: TemplateDeviceType
      - name: role
        mapping: role.name
      # - name: status
      #   mapping: status.value
      - name: site
        mapping: site.slug
      - name: rack
        mapping: rack
        reference: InfraRack
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Circuits (Provider, Provider Network, Circuits Types, Circuits)
  - name: CoreOrganization
    mapping: circuits.providers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Provider"
  - name: InfraProviderNetwork
    mapping: circuits.provider-networks
    fields:
      - name: name
        mapping: name
        identifier: true
      - name: vendor_id
        mapping: service_id
      - name: provider
        mapping: provider.slug
      - name: description
        mapping: description
      # - name: status
      #   mapping: status.value
      - name: tags
        mapping: tags
        reference: BuiltinTag
      - name: provider
        mapping: provider
        reference: CoreOrganization
  - name: TemplateCircuitType
    mapping: circuits.circuit-types
    fields:
      - name: name
        mapping: name
        identifier: true
      - name: description
        mapping: description
      - name: tags
        mapping: tags
        reference: BuiltinTag
  - name: InfraCircuit
    mapping: circuits.circuits
    fields:
      - name: circuit_id
        mapping: cid
        identifier: true
      - name: vendor_id
        mapping: cid
      - name: provider
        mapping: provider
        reference: CoreOrganization
      - name: description
        mapping: description
      # - name: status
      #   mapping: status.value
      - name: type
        mapping: type.name
      - name: provider
        mapping: provider
        reference: CoreOrganization
      - name: tags
        mapping: tags
        reference: BuiltinTag

# IPAM (VRF, VLANs Groups, VLANs, Prefixes, IPs)
  - name: InfraRouteTarget
    mapping: ipam.route-targets
    identifiers: ["name", "organization"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
  - name: InfraVRF
    mapping: ipam.vrfs
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: vrf_rd
        mapping: rd
      # - name: importRT
      #   mapping: import_target
      #   reference: InfraRouteTarget
      # - name: exportRT
      #   mapping: export_target
      #   reference: InfraRouteTarget
  - name: CoreStandardGroup
    mapping: ipam.vlan-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: InfraVLAN
    mapping: ipam.vlans
    identifiers: ["name", "vlan_id", "site", "vlan_group"]
    fields:
      - name: name
        mapping: name
      - name: vlan_id
        mapping: vid
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: description
        mapping: description
      - name: site
        mapping: site.slug
      - name: vlan_group
        mapping: group
        reference: CoreStandardGroup
  - name: InfraPrefix
    mapping: ipam.prefixes
    identifiers: ["prefix", "vrf"]
    fields:
      - name: prefix
        mapping: prefix
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: role
        mapping: role.name
      - name: vrf
        mapping: vrf.name
      - name: site
        mapping: site.slug
      # - name: status
      #   mapping: status.value
      # - name: vlan
      #   mapping: vlan.name
      # - name: site
      #   mapping: site.slug
      # - name: location
      #   mapping: location.slug
  - name: InfraIPAddress
    mapping: ipam.ip-addresses
    identifiers: ["address", "vrf"]
    fields:
      - name: address
        mapping: address
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: role
        mapping: role.name
      # - name: status
      #   mapping: status.value
      - name: vrf
        mapping: vrf.name
