---
name: from-netbox
source:
  name: netbox
  settings:
    url: "https://demo.netbox.dev"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "BuiltinTag",
  "BuiltinRole",
  "OrgaManufacturer",
  "OrgaProvider",
  "BuiltinLocation",
  "InfraRack",
  "TemplateDeviceType",
  # "InfraDevice",
  "TemplateCircuitType",
  "InfraCircuit"
]

schema_mapping:
  - name: BuiltinTag
    mapping: extras.tags
    fields:
      - name: name
        mapping: name
        identifier: true
      - name: description
        mapping: description

  - name: BuiltinLocation
    mapping: dcim.sites
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: description
      - name: type
        static: "SITE"

  - name: InfraRack
    mapping: dcim.racks
    identifiers: ["location", "name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: location
        mapping: site.slug
      - name: height
        mapping: u_height
      - name: tags
        mapping: tags
        reference: tag
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: facility_id
        mapping: facility_id
      - name: role
        mapping: role.name

  - name: BuiltinRole
    mapping: dcim.device_roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  - name: BuiltinRole
    mapping: dcim.rack_roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  - name: BuiltinRole
    mapping: ipam.roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  - name: OrgaManufacturer
    mapping: dcim.manufacturers
    fields:
      - name: name
        mapping: name
        identifier: true
      - name: description
        mapping: description
      - name: tags
        mapping: tags
        reference: tag

  - name: OrgaProvider
    mapping: circuits.providers
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: tags
        mapping: tags
        reference: tag

  - name: TemplateDeviceType
    mapping: dcim.device-types
    fields:
      - name: name
        mapping: model
        identifier: true
      - name: part_number
        mapping: part_number
      - name: description
        mapping: description
      - name: tags
        mapping: tags
        reference: tag
      - name: manufacturer
        mapping: manufacturer.name

  # TODO -> if the device in netbox have no name, no serial and no asset, which identifiers could we use ?
  # - name: InfraDevice
  #   mapping: dcim.devices
  #   fields:
  #     - name: name
  #       mapping: name
  #     - name: serial_number
  #       mapping: serial
  #     - name: asset_tag
  #       mapping: asset_tag
  #     - name: description
  #       mapping: description
  #     - name: tags
  #       mapping: tags
  #       reference: tag
  #     - name: model
  #       mapping: device_type.model
  #     - name: role
  #       mapping: role.name
  #     - name: site
  #       mapping: site.name
  #     - name: rack
  #       mapping: rack.name

  - name: TemplateCircuitType
    mapping: circuits.circuit-types
    fields:
      - name: name
        mapping: name
        identifier: true
      - name: description
        mapping: description
      - name: tags
        mapping: tags
        reference: tag

  - name: InfraCircuit
    mapping: circuits.circuits
    fields:
      - name: circuit_id
        mapping: cid
        identifier: true
      - name: provider
        mapping: provider.name
      - name: description
        mapping: description
      - name: status
        mapping: status.value
      - name: type
        mapping: type.name
      - name: tags
        mapping: tags
        reference: tag
      - name: provider
        mapping: provider.name
