import { TagGroup, type TagGroupProps, TagList } from "react-aria-components";

import { ScrollArea } from "@/shared/components/ui/scroll-area";
import { formatFullDate } from "@/shared/utils/date";

import {
  AVAILABLE_IP_FILTER_NAME,
  HIDE_AVAILABLE_IP,
  HIDE_AVAILABLE_IP_FILTER,
  IP_ADDRESS_GENERIC,
  IP_PREFIX_GENERIC,
  SHOW_AVAILABLE_IP,
} from "@/entities/ipam/constants";
import { IpAddressAvailabilityFilterTag } from "@/entities/ipam/ip-addresses/ui/ip-address-availability-filter-tag";
import { IpPrefixAvailabilityFilterTag } from "@/entities/ipam/ip-prefixes/ui/ip-prefix-availability-filter-tag";
import type { AttributeType } from "@/entities/nodes/getObjectItemDisplayValue";
import { FilterResetButton } from "@/entities/nodes/object/ui/filters/filter-reset-button";
import { FilterTag } from "@/entities/nodes/object/ui/filters/filter-tag";
import {
  HIDE_INTERNAL_GROUPS_FILTER,
  HIDE_INTERNAL_GROUPS_ID,
  InternalGroupsFilterTag,
  SHOW_INTERNAL_GROUPS_ID,
} from "@/entities/nodes/object/ui/filters/internal-groups-filter-tag";
import { useObjectTableContext } from "@/entities/nodes/object/ui/object-table/object-table-context";
import { ATTRIBUTE_KIND } from "@/entities/schema/constants";
import type { AttributeKind, ModelSchema } from "@/entities/schema/types";
import { isOfKind } from "@/entities/schema/utils/is-of-kind";

export function formatAttributeFilterValue({
  kind,
  value,
}: {
  kind: AttributeKind;
  value: AttributeType["value"];
}) {
  switch (kind) {
    case ATTRIBUTE_KIND.BOOLEAN:
      return value.toString();
    case ATTRIBUTE_KIND.DATETIME:
      return formatFullDate(value);
    default:
      return value;
  }
}

export interface ActiveObjectsFilterTagsProps extends TagGroupProps {
  schema: ModelSchema;
}

export function ActiveObjectFilterTags({ schema, ...props }: ActiveObjectsFilterTagsProps) {
  const { filters, setFilters } = useObjectTableContext();

  const handleRemoveFilter = (filterName: string) => {
    setFilters(filters.filter((f) => f.name !== filterName));
  };

  return (
    <>
      <ScrollArea scrollX>
        <TagGroup
          selectionMode="single"
          aria-label="Active filters"
          onSelectionChange={(keys) => {
            const filterName = Array.from(keys)[0]?.toString();
            if (!filterName) return;

            switch (filterName) {
              case HIDE_INTERNAL_GROUPS_ID: {
                return setFilters([HIDE_INTERNAL_GROUPS_FILTER, ...filters]);
              }
              case SHOW_INTERNAL_GROUPS_ID: {
                return setFilters(
                  filters.filter((filter) => filter.name !== HIDE_INTERNAL_GROUPS_FILTER.name)
                );
              }
              case SHOW_AVAILABLE_IP: {
                return setFilters(
                  filters.filter((filter) => filter.name !== AVAILABLE_IP_FILTER_NAME)
                );
              }
              case HIDE_AVAILABLE_IP: {
                return setFilters([HIDE_AVAILABLE_IP_FILTER, ...filters]);
              }
              default: {
                return handleRemoveFilter(filterName);
              }
            }
          }}
          onRemove={(keys) => {
            const filterName = Array.from(keys)[0]?.toString();
            if (!filterName) return;

            handleRemoveFilter(filterName);
          }}
          {...props}
        >
          <TagList className="flex items-center gap-2 py-3">
            {isOfKind("CoreGroup", schema) && <InternalGroupsFilterTag />}
            {isOfKind(IP_PREFIX_GENERIC, schema) && <IpPrefixAvailabilityFilterTag />}
            {isOfKind(IP_ADDRESS_GENERIC, schema) && <IpAddressAvailabilityFilterTag />}

            {filters.map((filter) => {
              if (filter.name === HIDE_INTERNAL_GROUPS_FILTER.name) return null; // Handled by GroupsAutoGeneratedFilterButton

              const [fieldName, fieldKey] = filter.name.split("__");

              if (!fieldName || !fieldKey) {
                return null;
              }

              if (fieldKey === "value" || fieldKey === "values") {
                const attributeSchema = schema?.attributes?.find(({ name }) => name === fieldName);
                if (!attributeSchema) {
                  return null;
                }

                return (
                  <FilterTag
                    key={filter.name}
                    id={filter.name}
                    label={attributeSchema.label ?? attributeSchema.name}
                    value={formatAttributeFilterValue({
                      kind: attributeSchema.kind as AttributeKind,
                      value: filter.value,
                    })}
                  />
                );
              }

              if (fieldKey === "ids") {
                const relationshipSchema = schema?.relationships?.find(
                  ({ name }) => name === fieldName
                );
                if (!relationshipSchema) {
                  return null;
                }

                const value = filter.value
                  .map(({ display_label }: { display_label: string }) => display_label)
                  .join(", ");

                return (
                  <FilterTag
                    key={filter.name}
                    id={filter.name}
                    label={relationshipSchema.label ?? relationshipSchema.name}
                    value={value}
                  />
                );
              }

              if (fieldKey === "isnull") {
                const fieldSchema = [
                  ...(schema?.attributes ?? []),
                  ...(schema?.relationships ?? []),
                ].find(({ name }) => name === fieldName);

                if (!fieldSchema) return null;

                return (
                  <FilterTag
                    key={filter.name}
                    id={filter.name}
                    label={fieldSchema.label ?? fieldSchema.name}
                    value={filter.value ? "empty" : "not empty"}
                  />
                );
              }

              return null;
            })}
          </TagList>
        </TagGroup>
      </ScrollArea>

      {filters.length > 0 && <FilterResetButton />}
    </>
  );
}
