import { AttributeType } from "@/entities/nodes/getObjectItemDisplayValue";
import { FilterTag } from "@/entities/nodes/object/ui/filters/filter-tag";
import {
  GroupsAutoGeneratedFilterButton,
  HIDE_AUTO_GENERATED_FILTER,
  HIDE_INTERNAL_GROUPS_ID,
  SHOW_INTERNAL_GROUPS_ID,
} from "@/entities/nodes/object/ui/filters/groups-auto-generated-filter-button";
import { useObjectTableContext } from "@/entities/nodes/object/ui/object-table/object-table-context";
import { ATTRIBUTE_KIND } from "@/entities/schema/constants";
import { AttributeKind, ModelSchema } from "@/entities/schema/types";
import { isOfKind } from "@/entities/schema/utils/is-of-kind";
import { formatFullDate } from "@/shared/utils/date";
import { TagGroup, TagGroupProps, TagList } from "react-aria-components";

export function formatAttributeFilterValue({
  kind,
  value,
}: { kind: AttributeKind; value: AttributeType["value"] }) {
  switch (kind) {
    case ATTRIBUTE_KIND.BOOLEAN:
      return value.toString();
    case ATTRIBUTE_KIND.DATETIME:
      return formatFullDate(value);
    default:
      return value;
  }
}

export interface ObjectsFilterTagsProps extends TagGroupProps {
  schema?: ModelSchema;
}

export function ActiveFilterTags({ schema, ...props }: ObjectsFilterTagsProps) {
  const { filters, setFilters } = useObjectTableContext();

  const handleRemoveFilter = (filterName: string) => {
    setFilters(filters.filter((f) => f.name !== filterName));
  };

  return (
    <TagGroup
      selectionMode="single"
      aria-label="Active filters"
      onSelectionChange={(keys) => {
        const filterName = Array.from(keys)[0]?.toString();
        if (!filterName) return;

        if (filterName === HIDE_INTERNAL_GROUPS_ID) {
          return setFilters([HIDE_AUTO_GENERATED_FILTER, ...filters]);
        }

        if (filterName === SHOW_INTERNAL_GROUPS_ID) {
          return setFilters(
            filters.filter((filter) => filter.name !== HIDE_AUTO_GENERATED_FILTER.name)
          );
        }

        handleRemoveFilter(filterName);
      }}
      onRemove={(keys) => {
        const filterName = Array.from(keys)[0]?.toString();
        if (!filterName) return;

        handleRemoveFilter(filterName);
      }}
      {...props}
    >
      <TagList className="flex items-center gap-2 py-3">
        {schema && isOfKind("CoreGroup", schema) && <GroupsAutoGeneratedFilterButton />}

        {filters.map((filter) => {
          if (filter.name === HIDE_AUTO_GENERATED_FILTER.name) return null; // Handled by GroupsAutoGeneratedFilterButton
          if (filter.name === "kind__value") return null; // Handled by ObjectTableSchemaSelector

          const [fieldName, fieldKey] = filter.name.split("__");

          if (!fieldName || !fieldKey) {
            return null;
          }

          if (fieldKey === "value" || fieldKey === "values") {
            const attributeSchema = schema?.attributes?.find(({ name }) => name === fieldName);
            if (!attributeSchema) {
              return null;
            }

            return (
              <FilterTag
                key={filter.name}
                id={filter.name}
                label={attributeSchema.label ?? attributeSchema.name}
                value={formatAttributeFilterValue({
                  kind: attributeSchema.kind as AttributeKind,
                  value: filter.value,
                })}
              />
            );
          }

          if (fieldKey === "ids") {
            const relationshipSchema = schema?.relationships?.find(
              ({ name }) => name === fieldName
            );
            if (!relationshipSchema) {
              return null;
            }

            const value = filter.value
              .map(({ display_label }: { display_label: string }) => display_label)
              .join(", ");

            return (
              <FilterTag
                key={filter.name}
                id={filter.name}
                label={relationshipSchema.label ?? relationshipSchema.name}
                value={value}
              />
            );
          }

          if (fieldKey === "isnull") {
            const fieldSchema = [
              ...(schema?.attributes ?? []),
              ...(schema?.relationships ?? []),
            ].find(({ name }) => name === fieldName);

            if (!fieldSchema) return null;

            return (
              <FilterTag
                key={filter.name}
                id={filter.name}
                label={fieldSchema.label ?? fieldSchema.name}
                value={filter.value ? "empty" : "not empty"}
              />
            );
          }

          return null;
        })}
      </TagList>
    </TagGroup>
  );
}
