import { FilterSuggestionTag } from "@/entities/nodes/object/ui/filters/filter-suggestion-tag";
import { FilterTag } from "@/entities/nodes/object/ui/filters/filter-tag";
import useFilters, { Filter } from "@/shared/hooks/useFilters";
import { useEffect } from "react";
import type { TagProps } from "react-aria-components";

////////////////////////////////////////////////////////////////////////////////////////////////////

export const HIDE_AUTO_GENERATED_FILTER: Filter = { name: "group_type__value", value: "default" };
export const HIDE_INTERNAL_GROUPS_ID = "hide-internal-groups";
export const SHOW_INTERNAL_GROUPS_ID = "show-internal-groups";

////////////////////////////////////////////////////////////////////////////////////////////////////

export const GroupsAutoGeneratedFilterButton = ({ ...props }: TagProps) => {
  const [filters, setFilters] = useFilters();

  useEffect(() => {
    if (filters.length === 0) {
      setFilters([HIDE_AUTO_GENERATED_FILTER]);
    }
  }, []);

  const groupTypeFilter = filters.find((filter) => filter.name === HIDE_AUTO_GENERATED_FILTER.name);

  if (!groupTypeFilter || groupTypeFilter.value !== HIDE_AUTO_GENERATED_FILTER.value) {
    return (
      <FilterSuggestionTag id={HIDE_INTERNAL_GROUPS_ID} label="Hide internal groups" {...props} />
    );
  }

  return <FilterTag id={SHOW_INTERNAL_GROUPS_ID} label="Internal groups" value="hide" {...props} />;
};
