query GeneratorInstanceFetch($definition_id: ID, $object_id: ID) {
    CoreGeneratorInstance(definition__ids: [$definition_id], object__ids: [$object_id], limit: 1) {
        edges {
            node {
                id
                status {
                    value
                }
            }
        }
    }
}
