import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// NOTE: External "↗" links below are stubbed with https://TODO-FILL-IN-*.example.com
// URLs. Replace each TODO URL with the real destination before merging this PR.

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'home',
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'doc', id: 'overview/overview', label: 'What is Infrahub?' },
        { type: 'doc', id: 'overview/concepts', label: 'Key Concepts' },
        { type: 'doc', id: 'topics/architecture', label: 'Architecture' },
        { type: 'doc', id: 'topics/community-vs-enterprise', label: 'Community vs Enterprise' },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'doc', id: 'overview/quickstart', label: 'Quickstart' },
        { type: 'doc', id: 'overview/explore', label: 'Explore Infrahub' },
        { type: 'doc', id: 'overview/next-steps', label: 'Next Steps' },
      ],
    },
    {
      type: 'category',
      label: 'Deploying & Managing Infrahub',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'guides/installation', label: 'Installation' },
        { type: 'doc', id: 'guides/production-deployment', label: 'Production Deployment' },
        { type: 'doc', id: 'topics/hardware-requirements', label: 'Hardware Requirements' },
        { type: 'doc', id: 'reference/configuration', label: 'Configuration' },
        { type: 'doc', id: 'guides/configuration-changes', label: 'Configuration Changes' },
        { type: 'doc', id: 'topics/database-backup', label: 'Database Backup (Topic)' },
        { type: 'doc', id: 'guides/database-backup', label: 'Database Backup (Guide)' },
        { type: 'doc', id: 'guides/upgrade', label: 'Upgrade' },
        { type: 'doc', id: 'topics/tasks', label: 'Tasks' },
        { type: 'doc', id: 'reference/task-worker', label: 'Task Worker' },
        { type: 'link', label: 'Infrahubctl CLI ↗', href: 'https://TODO-FILL-IN-infrahubctl.example.com' },
        { type: 'link', label: 'Infrahub Backup Tool ↗', href: 'https://TODO-FILL-IN-infrahub-backup.example.com' },
      ],
    },
    {
      type: 'category',
      label: 'Schema & Data Modeling',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/schema', label: 'Understanding Schemas' },
        { type: 'doc', id: 'guides/create-schema', label: 'Create a Schema' },
        { type: 'doc', id: 'guides/import-schema', label: 'Import a Schema' },
        { type: 'doc', id: 'topics/schema-extensions', label: 'Schema Extensions' },
        { type: 'doc', id: 'topics/schema-display', label: 'Schema Display' },
        { type: 'doc', id: 'topics/computed-attributes', label: 'Computed Attributes (Topic)' },
        { type: 'doc', id: 'guides/computed-attributes', label: 'Computed Attributes (Guide)' },
        { type: 'doc', id: 'topics/order-weight', label: 'Field Ordering (Topic)' },
        { type: 'doc', id: 'guides/customize-field-ordering', label: 'Field Ordering (Guide)' },
        { type: 'doc', id: 'topics/labels', label: 'Labels' },
        { type: 'link', label: 'Schema Library ↗', href: 'https://TODO-FILL-IN-schema-library.example.com' },
      ],
    },
    {
      type: 'category',
      label: 'Version Control & Branching',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/version-control', label: 'Version Control' },
        { type: 'doc', id: 'topics/branching', label: 'Branching' },
        { type: 'doc', id: 'topics/proposed-change', label: 'Proposed Changes' },
        { type: 'doc', id: 'guides/change-approval-workflow', label: 'Change Approval Workflow' },
        { type: 'doc', id: 'guides/selective-branch-sync', label: 'Selective Branch Sync' },
      ],
    },
    {
      type: 'category',
      label: 'Data Management',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/graphql', label: 'GraphQL' },
        { type: 'doc', id: 'guides/graphql-fragment', label: 'GraphQL Fragments' },
        { type: 'doc', id: 'guides/object-load', label: 'Loading Data' },
        { type: 'doc', id: 'topics/groups', label: 'Groups (Topic)' },
        { type: 'doc', id: 'guides/groups', label: 'Groups (Guide)' },
        { type: 'doc', id: 'topics/profiles', label: 'Profiles (Topic)' },
        { type: 'doc', id: 'guides/profiles', label: 'Profiles (Guide)' },
        { type: 'doc', id: 'topics/object-template', label: 'Object Templates (Topic)' },
        { type: 'doc', id: 'guides/object-template', label: 'Object Templates (Guide)' },
        { type: 'doc', id: 'topics/object-conversion', label: 'Object Conversion (Topic)' },
        { type: 'doc', id: 'guides/object-conversion', label: 'Object Conversion (Guide)' },
        { type: 'doc', id: 'topics/metadata', label: 'Metadata & Lineage' },
        { type: 'doc', id: 'topics/file-object', label: 'File Objects' },
        { type: 'doc', id: 'topics/check', label: 'Checks & Validation (Topic)' },
        { type: 'doc', id: 'guides/check', label: 'Checks & Validation (Guide)' },
        { type: 'link', label: 'Python SDK ↗', href: 'https://TODO-FILL-IN-python-sdk.example.com' },
      ],
    },
    {
      type: 'category',
      label: 'IPAM & Resource Management',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/ipam', label: 'IPAM Overview' },
        { type: 'doc', id: 'topics/resource-manager', label: 'Resource Manager (Topic)' },
        { type: 'doc', id: 'guides/resource-manager', label: 'Resource Manager (Guide)' },
      ],
    },
    {
      type: 'category',
      label: 'Transforms & Artifacts',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/transformation', label: 'Transformations' },
        { type: 'doc', id: 'guides/jinja2-transform', label: 'Jinja2 Transforms' },
        { type: 'doc', id: 'guides/python-transform', label: 'Python Transforms' },
        { type: 'doc', id: 'topics/artifact', label: 'Artifacts (Topic)' },
        { type: 'doc', id: 'guides/artifact', label: 'Artifacts (Guide)' },
        { type: 'doc', id: 'guides/artifact-content-composition', label: 'Artifact Content Composition' },
        { type: 'doc', id: 'topics/object-storage', label: 'Object Storage (Topic)' },
        { type: 'doc', id: 'guides/object-storage', label: 'Object Storage (Guide)' },
        { type: 'doc', id: 'topics/developer-guide', label: 'Developer Guide' },
        { type: 'doc', id: 'topics/resources-testing-framework', label: 'Testing Framework' },
      ],
    },
    {
      type: 'category',
      label: 'Generators',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/generator', label: 'Generator Overview (Topic)' },
        { type: 'doc', id: 'guides/generator', label: 'Generator Overview (Guide)' },
        { type: 'doc', id: 'guides/chaining-generators', label: 'Chaining Generators' },
        { type: 'doc', id: 'topics/modular-generators', label: 'Modular Generators (Topic)' },
        { type: 'doc', id: 'guides/modular-generator-best-practices', label: 'Modular Generator Best Practices' },
      ],
    },
    {
      type: 'category',
      label: 'Git Integration',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/repository', label: 'Repository Management (Topic)' },
        { type: 'doc', id: 'guides/repository', label: 'Repository Management (Guide)' },
        { type: 'doc', id: 'topics/infrahub-yml', label: 'Infrahub.yml Configuration' },
        { type: 'doc', id: 'topics/branch-synchronization', label: 'Branch Synchronization' },
      ],
    },
    {
      type: 'category',
      label: 'Events & Integrations',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/events', label: 'Events System' },
        { type: 'doc', id: 'topics/event-actions', label: 'Event Actions' },
        { type: 'doc', id: 'guides/events-rules-actions', label: 'Rules & Actions' },
        { type: 'doc', id: 'topics/webhooks', label: 'Webhooks (Topic)' },
        { type: 'doc', id: 'guides/webhooks', label: 'Webhooks (Guide)' },
        { type: 'doc', id: 'topics/activity-log', label: 'Activity Log' },
        // Open question for the team: keep Observability as a subgroup, or flatten?
        {
          type: 'category',
          label: 'Observability',
          collapsible: true,
          collapsed: false,
          items: [
            { type: 'doc', id: 'topics/log-forwarding', label: 'Log Forwarding (Topic)' },
            { type: 'doc', id: 'guides/log-forwarding', label: 'Log Forwarding (Guide)' },
            { type: 'doc', id: 'guides/telemetry', label: 'Telemetry' },
          ],
        },
        { type: 'link', label: 'Ansible Integration ↗', href: 'https://TODO-FILL-IN-ansible.example.com' },
        { type: 'link', label: 'Nornir Integration ↗', href: 'https://TODO-FILL-IN-nornir.example.com' },
        { type: 'link', label: 'Infrahub Sync ↗', href: 'https://TODO-FILL-IN-infrahub-sync.example.com' },
        { type: 'link', label: 'MCP Server ↗', href: 'https://TODO-FILL-IN-mcp-server.example.com' },
      ],
    },
    {
      type: 'category',
      label: 'User Management & Security',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'doc', id: 'topics/authentication', label: 'Authentication' },
        { type: 'doc', id: 'guides/sso', label: 'SSO' },
        { type: 'doc', id: 'topics/permissions-roles', label: 'Permissions & Roles (Topic)' },
        { type: 'doc', id: 'guides/accounts-permissions', label: 'Permissions & Roles (Guide)' },
        { type: 'doc', id: 'guides/managing-api-tokens', label: 'Managing API Tokens' },
        { type: 'doc', id: 'guides/menu', label: 'Menu Customization' },
      ],
    },
    {
      type: 'category',
      label: 'Solutions',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'link', label: 'AI Datacenter ↗', href: 'https://TODO-FILL-IN-ai-datacenter.example.com' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'reference',
      },
      items: [
        {
          type: 'category',
          label: 'API',
          link: { type: 'generated-index' },
          items: [
            'reference/api-server',
            'reference/message-bus-events',
          ],
        },
        {
          type: 'category',
          label: 'CLI',
          link: {
            type: 'generated-index',
            slug: 'reference/infrahub-cli',
          },
          items: [
            'reference/infrahub-cli/infrahub-db',
            'reference/infrahub-cli/infrahub-server',
            'reference/infrahub-cli/infrahub-dev',
            'reference/infrahub-cli/infrahub-upgrade',
          ],
        },
        {
          type: 'category',
          label: 'Configuration Files',
          link: { type: 'generated-index' },
          items: [
            { type: 'doc', id: 'reference/configuration', label: 'Infrahub Configuration' },
            { type: 'doc', id: 'reference/dotinfrahub', label: 'Repository Config' },
            { type: 'doc', id: 'reference/menu', label: 'Menu Configuration' },
            { type: 'doc', id: 'reference/infrahub-tests', label: 'Tests Configuration' },
          ],
        },
        {
          type: 'category',
          label: 'Schema Specification',
          link: {
            type: 'generated-index',
            slug: 'reference/schema',
          },
          items: [
            'reference/schema/node',
            'reference/schema/node-extension',
            'reference/schema/attribute',
            { type: 'doc', id: 'topics/schema-attr-kind-number-pool', label: 'Attribute - NumberPool' },
            'reference/schema/relationship',
            'reference/schema/generic',
            'reference/schema/groups',
            'reference/schema/validator-migration',
            'reference/schema-validation',
          ],
        },
        {
          type: 'category',
          label: 'Events',
          link: { type: 'generated-index' },
          items: [
            'reference/infrahub-events',
          ],
        },
        {
          type: 'category',
          label: 'Permissions',
          link: { type: 'generated-index' },
          items: [
            'reference/permissions',
          ],
        },
        {
          type: 'category',
          label: 'Authentication',
          link: { type: 'generated-index' },
          items: [
            { type: 'doc', id: 'reference/sso', label: 'SSO Reference' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Academy',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'academy/academy',
      },
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          link: { type: 'generated-index' },
          items: [
            'academy/getting-started/infrahub-introduction',
            'academy/getting-started/deploy-first-configuration',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'development',
      },
      items: [
        'development/git-best-practices',
        'development/editor',
        'development/changelog',
        'development/backend',
        {
          type: 'category',
          label: 'Frontend guide',
          link: { type: 'doc', id: 'development/frontend/readme' },
          items: [
            'development/frontend/getting-set-up',
            'development/frontend/testing-guidelines',
          ],
        },
        { type: 'doc', id: 'topics/local-demo-environment', label: 'Local Demo Environment' },
        'development/docs',
        'development/style-guide',
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'release-notes',
      },
      items: [
        {
          type: 'category',
          label: 'Infrahub',
          link: {
            type: 'generated-index',
            slug: 'release-notes/infrahub',
          },
          items: [
            'release-notes/infrahub/release-1_9_0',
            'release-notes/infrahub/release-1_8_6',
            'release-notes/infrahub/release-1_8_5',
            'release-notes/infrahub/release-1_8_4',
            'release-notes/infrahub/release-1_8_3',
            'release-notes/infrahub/release-1_8_2',
            'release-notes/infrahub/release-1_8_1',
            'release-notes/infrahub/release-1_8_0',
            'release-notes/infrahub/release-1_7_7',
            'release-notes/infrahub/release-1_7_6',
            'release-notes/infrahub/release-1_7_5',
            'release-notes/infrahub/release-1_7_4',
            'release-notes/infrahub/release-1_7_3',
            'release-notes/infrahub/release-1_7_2',
            'release-notes/infrahub/release-1_7_1',
            'release-notes/infrahub/release-1_7_0',
            'release-notes/infrahub/release-1_6_3',
            'release-notes/infrahub/release-1_6_2',
            'release-notes/infrahub/release-1_6_1',
            'release-notes/infrahub/release-1_6_0',
            'release-notes/infrahub/release-1_5_3',
            'release-notes/infrahub/release-1_5_2',
            'release-notes/infrahub/release-1_5_1',
            'release-notes/infrahub/release-1_5_0',
            'release-notes/infrahub/release-1_4_13',
            'release-notes/infrahub/release-1_4_12',
            'release-notes/infrahub/release-1_4_11',
            'release-notes/infrahub/release-1_4_10',
            'release-notes/infrahub/release-1_4_9',
            'release-notes/infrahub/release-1_4_8',
            'release-notes/infrahub/release-1_4_7',
            'release-notes/infrahub/release-1_4_6',
            'release-notes/infrahub/release-1_4_5',
            'release-notes/infrahub/release-1_4_4',
            'release-notes/infrahub/release-1_4_3',
            'release-notes/infrahub/release-1_4_2',
            'release-notes/infrahub/release-1_4_1',
            'release-notes/infrahub/release-1_4_0',
            'release-notes/infrahub/release-1_3_7',
            'release-notes/infrahub/release-1_3_6',
            'release-notes/infrahub/release-1_3_5',
            'release-notes/infrahub/release-1_3_3',
            'release-notes/infrahub/release-1_3_2',
            'release-notes/infrahub/release-1_3_1',
            'release-notes/infrahub/release-1_3_0',
            'release-notes/infrahub/release-1_2_12',
            'release-notes/infrahub/release-1_2_11',
            'release-notes/infrahub/release-1_2_10',
            'release-notes/infrahub/release-1_2_9',
            'release-notes/infrahub/release-1_2_8',
            'release-notes/infrahub/release-1_2_7',
            'release-notes/infrahub/release-1_2_6',
            'release-notes/infrahub/release-1_2_5',
            'release-notes/infrahub/release-1_2_4',
            'release-notes/infrahub/release-1_2_3',
            'release-notes/infrahub/release-1_2_2',
            'release-notes/infrahub/release-1_2_1',
            'release-notes/infrahub/release-1_2_0',
            'release-notes/infrahub/release-1_1_9',
            'release-notes/infrahub/release-1_1_8',
            'release-notes/infrahub/release-1_1_7',
            'release-notes/infrahub/release-1_1_6',
            'release-notes/infrahub/release-1_1_5',
            'release-notes/infrahub/release-1_1_4',
            'release-notes/infrahub/release-1_1_3',
            'release-notes/infrahub/release-1_1_2',
            'release-notes/infrahub/release-1_1_1',
            'release-notes/infrahub/release-1_1_0',
            'release-notes/infrahub/release-1_0_10',
            'release-notes/infrahub/release-1_0_9',
            'release-notes/infrahub/release-1_0_8',
            'release-notes/infrahub/release-1_0_7',
            'release-notes/infrahub/release-1_0_6',
            'release-notes/infrahub/release-1_0_5',
            'release-notes/infrahub/release-1_0_4',
            'release-notes/infrahub/release-1_0_3',
            'release-notes/infrahub/release-1_0_2',
            'release-notes/infrahub/release-1_0_1',
            'release-notes/infrahub/release-1_0_0',
            'release-notes/infrahub/release-0_16_4',
            'release-notes/infrahub/release-0_16_3',
            'release-notes/infrahub/release-0_16_2',
            'release-notes/infrahub/release-0_16_1',
            'release-notes/infrahub/release-0_16_0',
            'release-notes/infrahub/release-0_15_3',
            'release-notes/infrahub/release-0_15_2',
            'release-notes/infrahub/release-0_15_1',
            'release-notes/infrahub/release-0_15_0',
            'release-notes/infrahub/release-0_14',
            'release-notes/infrahub/release-0_13',
            'release-notes/infrahub/release-0_12',
            'release-notes/infrahub/release-0_11',
            'release-notes/infrahub/release-0_10',
            'release-notes/infrahub/release-0_9',
            'release-notes/infrahub/release-0_8',
            'release-notes/infrahub/release-0_7',
            'release-notes/infrahub/release-0_6',
          ],
        },
        {
          type: 'category',
          label: 'Deprecation Guides',
          link: {
            type: 'generated-index',
            slug: 'release-notes/deprecation-guides',
          },
          items: [
            'release-notes/deprecation-guides/display_labels',
          ],
        },
      ],
    },
    'faq/faq',
  ],
};

export default sidebars;
