---
# yamllint disable rule:truthy rule:truthy rule:line-length
name: 'Chromatic Publish'
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/packages/ui/**'
  push:
    branches:
      - develop
      - stable
      - release-*
    paths:
      - 'frontend/packages/ui/**'

permissions:
  contents: read

jobs:
  chromatic:
    defaults:
      run:
        working-directory: ./frontend/packages/ui
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # In order for Chromatic to correctly determine baseline commits, tot access the full Git history graph.
      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@4cc98810d00b34b8f9e89d454d64a8ac3d088340 # v18.7.1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./frontend/packages/ui
      - name: Outputs Storybook URL
        run: |
          echo "Storybook URL: ${{ steps.chromatic.outputs.storybookUrl }}"
