---
name: 'Chromatic Publish'
on:
  push:
    branches:
      - bab-deploy-storybook

permissions:
  contents: read

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls -la
      - name: "Check out repository code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Move to ui project
        run: cd ./frontend/packages/ui
      - name: Install dependencies
        run: npm install
      - name: Run Chromatic
        uses: chromaui/action@latest
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
