on:
  pull_request:
    branches:
      - lgu-stable
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - run: |
          gh pr create --title "test" --body "test body" --base lgu-develop
