---
name: "Keyword Scanner"
on: [push, pull_request]

env:
  KEYWORDS_LIST: ${{ secrets.KEYWORDS_LIST }}
  KEYWORDS_REGEX: ""

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create TruffleHog config
      run: |
        cat > custom-keywords.yaml << EOF
        detectors:
          - name: Internal keywords
            keywords:
              - ${{ env.KEYWORDS_LIST }}
            regex:
              adjective: '\b(${{ env.KEYWORDS_REGEX }})\b'
        EOF
      env:
        KEYWORDS_LIST: ${{ env.KEYWORDS_LIST }}

    - name: TruffleHog scan
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --config=custom-keywords.yaml
