---
# yamllint disable rule:truthy rule:truthy rule:line-length
name: "Poetry check"
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: "string"
        description: "Directory in which poetry check will be executed"
        default: "./"
jobs:
  poetry_check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: "Setup environment"
        run: |
          pipx install poetry
      - name: "Validate pyproject.toml and consistency with poetry.lock"
        run: |
          poetry check
        working-directory: ${{ github.event.inputs.directory }}
