---
# yamllint disable rule:truthy rule:line-length
name: Publish development docker image

on:
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish the image
        default: false
        required: true
      commit:
        type: string
        description: commit sha or branch name
        default: ''
        required: false
      platforms:
        type: string
        description: Comma separated platform list to build the image for
        default: "linux/amd64,linux/arm64"
      tag:
        type: string
        description: additional image tag
        default: ''
        required: false

permissions: {}

jobs:
  meta_data:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      ref: ${{ steps.ref.outputs.ref }}
      short_ref: ${{ steps.short_ref.outputs.short_ref }}
    steps:
      - name: Set GIT ref
        run: echo "ref=${COMMIT_INPUT:-$GITHUB_SHA}" >> "$GITHUB_OUTPUT"
        id: ref
        env:
          COMMIT_INPUT: ${{ inputs.commit }}
      - name: Set GIT short ref
        run: echo "short_ref=$(echo "$GIT_REF" | cut -c1-7)" >> "$GITHUB_OUTPUT"
        id: short_ref
        env:
          GIT_REF: ${{ steps.ref.outputs.ref }}
      - name: Set docker image meta data
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ vars.HARBOR_HOST }}/${{ github.repository }}
          tags: |
            type=raw,value=dev-${{ steps.short_ref.outputs.short_ref }}
            type=raw,value=${{ inputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=dev-${{ steps.short_ref.outputs.short_ref }}
          flavor: |
            latest=false


  publish-docker-image:
    permissions:
      contents: read
    uses: ./.github/workflows/ci-docker-image.yml
    needs: meta_data
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
    with:
      publish: ${{ inputs.publish }}
      version: dev-${{ needs.meta_data.outputs.short_ref }}
      ref: ${{ needs.meta_data.outputs.ref }}
      tags: ${{needs.meta_data.outputs.tags}}
      labels: ${{needs.meta_data.outputs.labels}}
      platforms: ${{ inputs.platforms }}
