---
# yamllint disable rule:truthy
name: Publish Infrahub-Server Package

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      publish:
        type: boolean
        description: Whether to publish the package to Pypi
        required: false
        default: false
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      publish:
        type: boolean
        description: Whether to publish the package to Pypi
        required: false
        default: false

jobs:
  publish_to_pypi:
    name: "Publish Infrahub SDK to PyPI"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install Poetry"
        uses: "snok/install-poetry@v1"
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - name: "Install Dependencies"
        run: "poetry install"

      - name: "Add PyPI secret"
        run: "poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}"

      - name: "Poetry build"
        run: "poetry build"

      - name: "show output"
        run: "ls -la dist/"

      - name: "Poetry push PyPI"
        if: ${{ inputs.publish }}
        run: "poetry publish"
