---
# yamllint disable rule:truthy
name: Publish Infrahub-Server, Infrahub-Testcontainers Packages
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      publish:
        type: boolean
        description: Whether to publish the package to Pypi
        required: false
        default: false
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      publish:
        type: boolean
        description: Whether to publish the package to Pypi
        required: false
        default: false

jobs:
  prepare-environment:
    uses: ./.github/workflows/define-versions.yml
  publish_to_pypi:
    name: "Publish Infrahub-Server and Infrahub-Testcontainers to PyPI"
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        package_dir: ["", "python_testcontainers"]
    needs: prepare-environment
    steps:
      - name: "Set up Python"
        id: python
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.12"

      - name: "Check out repository code"
        uses: "actions/checkout@v5"
        with:
          submodules: true

      - name: "Setup Python environment"
        run: |
          python -m pip install --user pipx
          pipx install -f poetry==${{ needs.prepare-environment.outputs.POETRY_VERSION }}
          poetry config virtualenvs.create true --local
          poetry env use 3.12
        env:
          PIPX_DEFAULT_PYTHON: ${{ steps.python.outputs.python-path }}

      - name: "Install Dependencies"
        run: "poetry install"
        working-directory: ${{ matrix.package_dir }}
      - name: "Add PyPI secret"
        run: "poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}"
        working-directory: ${{ matrix.package_dir }}
      - name: "Poetry build"
        run: "poetry build"
        working-directory: ${{ matrix.package_dir }}
      - name: "show output"
        run: "ls -la dist/"
        working-directory: ${{ matrix.package_dir }}
      - name: "Poetry push PyPI"
        if: ${{ inputs.publish }}
        run: "poetry publish"
        working-directory: ${{ matrix.package_dir }}
