---
# yamllint disable rule:truthy rule:line-length
name: New Release

on:
  release:
    types:
      - published

jobs:
  prepare-environment:
    uses: ./.github/workflows/define-versions.yml
  check_release:
    runs-on: ubuntu-22.04
    needs: prepare-environment
    outputs:
      is_prerelease: ${{ steps.release.outputs.is_prerelease }}
      is_devrelease: ${{ steps.release.outputs.is_devrelease }}
      version: ${{ steps.release.outputs.version }}
      major_minor_version: ${{ steps.release.outputs.major_minor_version }}
      latest_tag: ${{ steps.release.outputs.latest_tag }}
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v5"
        with:
          submodules: true

      - name: "Set up Python"
        id: python
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.12"

      - name: "Setup Python environment"
        run: |
          pipx install -f poetry==${{ needs.prepare-environment.outputs.POETRY_VERSION }}
          poetry config virtualenvs.create true --local
          poetry env use 3.12
        env:
          PIPX_DEFAULT_PYTHON: ${{ steps.python.outputs.python-path }}
      - name: "Install dependencies"
        run: "poetry install --no-interaction --no-ansi"

      - name: "Check prerelease type"
        id: release
        run: |
          echo is_prerelease=$(poetry run python -c "from packaging.version import Version; print(int(Version('$(poetry version -s)').is_prerelease))") >> "$GITHUB_OUTPUT"
          echo is_devrelease=$(poetry run python -c "from packaging.version import Version; print(int(Version('$(poetry version -s)').is_devrelease))") >> "$GITHUB_OUTPUT"
          echo "version=$(poetry version -s)" >> "$GITHUB_OUTPUT"
          echo major_minor_version=$(poetry run python -c "from packaging.version import Version; print(f\"{Version('$(poetry version -s)').major}.{Version('$(poetry version -s)').minor}\")") >> "$GITHUB_OUTPUT"
          echo latest_tag=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/releases/latest \
              | jq -r '.tag_name') >> "$GITHUB_OUTPUT"

      - name: Check tag version
        if: github.event.release.tag_name != format('infrahub-v{0}', steps.release.outputs.version)
        run: |
          echo "Tag version does not match python project version"
          exit 1

      - name: Check prerelease and project version
        if: github.event.release.prerelease == true && steps.release.outputs.is_prerelease == 0 && steps.release.outputs.is_devrelease == 0
        run: |
          echo "Cannot pre-release a non pre-release or non dev-release version (${{ steps.release.outputs.version }})"
          exit 1

      - name: Check release and project version
        if: github.event.release.prerelease == false && (steps.release.outputs.is_prerelease == 1 || steps.release.outputs.is_devrelease == 1)
        run: |
          echo "Cannot release a pre-release or dev-release version (${{ steps.release.outputs.version }})"
          exit 1


  meta_data:
    needs: check_release
    runs-on: ubuntu-22.04
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Set docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.HARBOR_HOST }}/${{ github.repository }}
          tags: |
            type=raw,value=${{ needs.check_release.outputs.version }}
            type=raw,value=${{ github.event.release.prerelease == false && needs.check_release.outputs.major_minor_version || '' }}
            type=raw,value=${{ github.event.release.prerelease == true && 'preview' || 'stable' }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
          flavor: |
            latest=${{ needs.check_release.outputs.latest_tag == github.event.release.tag_name }}

  publish-docker-image:
    uses: ./.github/workflows/ci-docker-image.yml
    secrets: inherit
    needs: meta_data
    with:
      publish: true
      version: ${{ github.ref_name }}
      ref: ${{ github.sha }}
      tags: ${{ needs.meta_data.outputs.tags }}
      labels: ${{ needs.meta_data.outputs.labels }}

  publish-helm-chart:
    needs: check_release
    if: github.event.release.prerelease == false
    uses: opsmill/infrahub-helm/.github/workflows/publish-helm-chart.yml@stable
    secrets: inherit
    with:
      publish: true
      chart: infrahub

  publish-pypi:
    needs: check_release
    uses: ./.github/workflows/publish-pypi.yml
    secrets: inherit
    with:
      publish: true

  repository-dispatch:
    needs:
      - check_release
      - publish-docker-image
    uses: ./.github/workflows/repository-dispatch.yml
    secrets: inherit
    with:
      version: ${{ needs.check_release.outputs.version }}
