---
# yamllint disable rule:truthy rule:line-length
name: Trigger Infrahub update in other repositories

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      version:
        type: string
        required: false
        description: The string to extract semver from.
        default: ''
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      version:
        type: string
        required: false
        description: The string to extract semver from.
        default: ''

jobs:
  repository-dispatch:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Either a literal path, or the name of a secret...
        repo:
          - "opsmill/infrahub-demo-dc"
          - "opsmill/infrahub-demo-sp"
          - "opsmill/infrahub-solution-ai-dc"
          - "INFRAHUB_PACKER_REPOSITORY"
          - "INFRAHUB_ENTERPRISE_REPOSITORY"
          - "INFRAHUB_CUSTOMER1_REPOSITORY"

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.GH_UPDATE_PACKAGE_OTTO }}
          # if matrix.repo contains a slash, use it literally; otherwise look up the secret named by matrix.repo
          repository: ${{ contains(matrix.repo, '/') && matrix.repo || secrets[matrix.repo] }}
          event-type: trigger-infrahub-update
          client-payload: |
            {"version":"${{ inputs.version }}"}
