---
# yamllint disable rule:truthy
name: Trigger Submodule update

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      version:
        type: string
        required: false
        description: The string to extract semver from.
        default: ''
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      version:
        type: string
        required: false
        description: The string to extract semver from.
        default: ''

jobs:
  trigger-submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger submodule update
        run: |
          echo "${{ inputs.version }}"
          curl -X POST \
              -H "Authorization: token ${{ secrets.GH_UPDATE_PACKAGE_OTTO }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ secrets.INFRAHUB_ENTERPRISE_REPOSITORY }}"/dispatches \
              -d "{\"event_type\":\"trigger-submodule-update\", \"client_payload\": {\"version\": \"${{ inputs.version }}\"}}"
