---
# yamllint disable rule:truthy rule:truthy rule:line-length
name: "uv check"
on:
  workflow_call:
    inputs:
      directory:
        type: "string"
        description: "Directory in which uv check will be executed"
        default: "./"
jobs:
  uv_check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          submodules: true
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
      - name: "Validate pyproject.toml and consistency with uv.lock"
        run: |
          uv lock --locked --offline
        working-directory: ${{ github.event.inputs.directory }}
