---
# yamllint disable rule:truthy rule:truthy rule:line-length
name: "uv check"
on:
  workflow_call:
    inputs:
      directory:
        type: "string"
        description: "Directory in which uv check will be executed"
        default: "./"
jobs:
  prepare-environment:
    uses: ./.github/workflows/define-versions.yml
  uv_check:
    needs: prepare-environment
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          submodules: true
      - name: "Set up Python"
        uses: "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97" # v7.0.0
        with:
          python-version: ${{ needs.prepare-environment.outputs.PYTHON_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          version: ${{ needs.prepare-environment.outputs.UV_VERSION }}
      - name: "Validate pyproject.toml and consistency with uv.lock"
        run: |
          uv lock --locked --offline
        working-directory: ${{ github.event.inputs.directory }}
