---
# yamllint disable rule:truthy rule:truthy rule:line-length
name: "Infrahub Version Upgrade testing"
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: commit sha or branch name
        default: ""
        required: false

env:
  INFRAHUB_DB_USERNAME: neo4j
  INFRAHUB_DB_PASSWORD: admin
  INFRAHUB_DB_ADDRESS: localhost
  INFRAHUB_DB_PORT: 7687
  INFRAHUB_DB_PROTOCOL: bolt
  INFRAHUB_BROKER_ADDRESS: message-queue
  INFRAHUB_LOG_LEVEL: CRITICAL
  INFRAHUB_IMAGE_NAME: "opsmill/infrahub"
  INFRAHUB_IMAGE_VER: "local"
  INFRAHUB_SERVER_PORT: 0
  INFRAHUB_DB_BACKUP_PORT: 0
  INFRAHUB_API_TOKEN: 06438eb2-8019-4776-878c-0941b1f1d1ec
  INFRAHUB_SCHEMA_STRICT_MODE: "false"
  INFRAHUB_TIMEOUT: 180
  VMAGENT_PORT: 0

jobs:
  prepare-environment:
    uses: ./.github/workflows/define-versions.yml
  migration-tests:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          # - name: From 1.1.0
          #   source_version: 1.1.0
          #   neo4j_image: "neo4j:5.20.0-enterprise"
          - name: From 1.3.0
            source_version: 1.3.0
            neo4j_image: "neo4j:2025.03.0-enterprise"
    name: ${{ matrix.name }}
    runs-on:
      group: huge-runners
    timeout-minutes: 120
    needs: prepare-environment
    env:
      INFRAHUB_DB_TYPE: neo4j
      UV_VERSION: ${{ needs.prepare-environment.outputs.UV_VERSION }}
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v5"
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ needs.prepare-environment.outputs.UV_VERSION }}
      - name: Install dependencies
        run: "uv sync --all-groups"
      - name: "Set environment variables"
        run: |
          echo INFRAHUB_BUILD_NAME=infrahub-${{ runner.name }} >> $GITHUB_ENV
          echo INFRAHUB_IMAGE_VER=${{ matrix.source_version }} >> $GITHUB_ENV
      - name: "Clear docker environment"
        run: docker compose -p $INFRAHUB_BUILD_NAME down -v --remove-orphans --rmi local
      - name: "Store start time"
        run: echo TEST_START_TIME=$(date +%s)000 >> $GITHUB_ENV

      # Initialize the demo environment with the Source Version
      - name: Pull External Docker Images
        run: uv run invoke demo.pull
        env:
          NEO4J_DOCKER_IMAGE: ${{ matrix.neo4j_image }}

      - name: Initialize Demo
        id: init-demo
        run: uv run invoke demo.start demo.load-infra-schema
        env:
          PREFECT_SERVER_COMMAND: "prefect server start --host 0.0.0.0 --ui"
          NEO4J_DOCKER_IMAGE: ${{ matrix.neo4j_image }}

      - name: Check Demo Status
        run: uv run invoke demo.status
        env:
          NEO4J_DOCKER_IMAGE: ${{ matrix.neo4j_image }}

      - name: Load Infra Data
        run: uv run invoke demo.load-infra-data
        env:
          PREFECT_SERVER_COMMAND: "prefect server start --host 0.0.0.0 --ui"
          NEO4J_DOCKER_IMAGE: ${{ matrix.neo4j_image }}

      - name: Run infra data patch scripts
        run: uv run invoke demo.run-infra-patch-scripts
        env:
          PREFECT_SERVER_COMMAND: "prefect server start --host 0.0.0.0 --ui"
          NEO4J_DOCKER_IMAGE: ${{ matrix.neo4j_image }}

      - name: Set infrahub address
        run: |
          PORT=$(docker compose -p $INFRAHUB_BUILD_NAME port server 8000 | cut -d: -f2)
          echo "INFRAHUB_ADDRESS=http://localhost:${PORT}" >> $GITHUB_ENV

      - name: Load custom data
        run: echo "DATA_NAME=$(uv run invoke dev.test-add-dummy-data)" >> $GITHUB_ENV

      - name: Stop Demo
        run: uv run invoke demo.stop

      # Build the local version and run the migrations
      - name: "Set environment variables"
        run: |
          echo INFRAHUB_IMAGE_VER=local-${{ runner.name }}-${{ github.sha }} >> $GITHUB_ENV

      - name: Build Demo
        run: uv run invoke dev.build

      - name: Upgrade Infrahub and apply the latest database migrations
        run: uv run invoke dev.upgrade --rebase-branches

      - name: Start Demo
        run: uv run invoke dev.start

      - name: Set infrahub address
        run: |
          PORT=$(docker compose -p $INFRAHUB_BUILD_NAME port server 8000 | cut -d: -f2)
          echo "INFRAHUB_ADDRESS=http://localhost:${PORT}" >> $GITHUB_ENV

      - name: Verify branch graph version
        run: uv run invoke dev.test-branch-graph-version --branch atl1-delete-upstream

      - name: Containers after tests
        if: always()
        run: docker ps -a

      - name: Display server logs
        if: always()
        run: docker logs "${INFRAHUB_BUILD_NAME}-server-1" || true

      - name: Display git 1 logs
        if: always()
        run: docker logs "${INFRAHUB_BUILD_NAME}-task-worker-1" || true

      - name: Display git 2 logs
        if: always()
        run: docker logs "${INFRAHUB_BUILD_NAME}-task-worker-2" || true

      - name: Display database logs
        if: always()
        run: docker logs "${INFRAHUB_BUILD_NAME}-database-1" || true

      - name: Display task-manager logs
        if: always()
        run: docker logs "${INFRAHUB_BUILD_NAME}-task-manager-1" || true

      - name: Display server status
        if: always()
        run: uv run invoke demo.status

      - name: "Clear docker environment and force vmagent to stop"
        if: always()
        run: docker compose -p $INFRAHUB_BUILD_NAME down -v --remove-orphans --rmi local
